// ================================================================
//  KIPL ProjectOS — Accounting Module Backend
//  Run: node scripts/modules/accounting/backend.js
// ================================================================
const fs   = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..', '..', '..')
const SRC  = path.join(ROOT, 'backend', 'src')
const ACC  = path.join(SRC, 'accounting')

const G = '\x1b[32m', B = '\x1b[34m', NC = '\x1b[0m'
const ok   = s => console.log(G + '  ✓' + NC + ' ' + s)
const info = s => console.log(B + '  →' + NC + ' ' + s)

function w(p, lines) {
  fs.mkdirSync(path.dirname(p), { recursive: true })
  fs.writeFileSync(p, lines.join('\n'), 'utf8')
}

if (!fs.existsSync(SRC)) { console.error('backend/src not found'); process.exit(1) }
fs.mkdirSync(ACC, { recursive: true })

console.log('\n\x1b[1mBuilding Accounting Module — Backend\x1b[0m\n')

// ── Vendor entity ──────────────────────────────────────────────
info('Writing entities...')
w(path.join(ACC, 'vendor.entity.ts'), [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum VendorCategory {",
  "  SUBCONTRACTOR = 'subcontractor',",
  "  MATERIAL      = 'material',",
  "  EQUIPMENT     = 'equipment',",
  "  LABOUR        = 'labour',",
  "  CONSULTANT    = 'consultant',",
  "  UTILITY       = 'utility',",
  "  OTHER         = 'other',",
  "}",
  "",
  "@Entity('vendors')",
  "export class Vendor extends BaseEntity {",
  "  @Column({ name: 'project_id', nullable: true })",
  "  projectId: string",
  "  @Column()",
  "  name: string",
  "  @Column({ nullable: true })",
  "  contactPerson: string",
  "  @Column({ nullable: true })",
  "  phone: string",
  "  @Column({ nullable: true })",
  "  email: string",
  "  @Column({ nullable: true })",
  "  address: string",
  "  @Column({ nullable: true })",
  "  gstin: string",
  "  @Column({ nullable: true })",
  "  pan: string",
  "  @Column({ type: 'enum', enum: VendorCategory, default: VendorCategory.OTHER })",
  "  category: VendorCategory",
  "  @Column({ name: 'bank_account', type: 'jsonb', nullable: true })",
  "  bankAccount: Record<string, string>",
  "  @Column({ name: 'tds_applicable', default: false })",
  "  tdsApplicable: boolean",
  "  @Column({ name: 'tds_section', nullable: true })",
  "  tdsSection: string",
  "  @Column({ name: 'tds_rate', type: 'decimal', precision: 5, scale: 2, default: 0 })",
  "  tdsRate: number",
  "  @Column({ name: 'is_active', default: true })",
  "  isActive: boolean",
  "  @CreateDateColumn({ name: 'created_at' })",
  "  createdAt: Date",
  "}",
])

w(path.join(ACC, 'transaction.entity.ts'), [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum TxType { INCOME = 'income', EXPENSE = 'expense' }",
  "",
  "export enum ExpenseCategory {",
  "  LABOUR         = 'labour',",
  "  MATERIAL       = 'material',",
  "  EQUIPMENT_HIRE = 'equipment_hire',",
  "  EQUIPMENT_FUEL = 'equipment_fuel',",
  "  SUBCONTRACTOR  = 'subcontractor',",
  "  TRANSPORT      = 'transport',",
  "  SITE_OFFICE    = 'site_office',",
  "  SAFETY         = 'safety',",
  "  TESTING_QA     = 'testing_qa',",
  "  LIAISON        = 'liaison',",
  "  SALARY         = 'salary',",
  "  PETTY_CASH     = 'petty_cash',",
  "  GST_PAYMENT    = 'gst_payment',",
  "  TDS_PAYMENT    = 'tds_payment',",
  "  BANK_CHARGES   = 'bank_charges',",
  "  OTHER          = 'other',",
  "}",
  "",
  "export enum PaymentMode {",
  "  RTGS = 'rtgs', NEFT = 'neft', CHEQUE = 'cheque',",
  "  CASH = 'cash', UPI = 'upi', OTHER = 'other',",
  "}",
  "",
  "export enum TxStatus { PENDING = 'pending', PAID = 'paid', CANCELLED = 'cancelled' }",
  "",
  "@Entity('transactions')",
  "export class Transaction extends BaseEntity {",
  "  @Column({ name: 'project_id', nullable: true }) projectId: string",
  "  @Column({ type: 'enum', enum: TxType }) type: TxType",
  "  @Column({ type: 'date' }) date: string",
  "  @Column({ type: 'text' }) description: string",
  "  @Column({ type: 'enum', enum: ExpenseCategory, nullable: true }) category: ExpenseCategory",
  "  @Column({ name: 'vendor_id', nullable: true }) vendorId: string",
  "  @Column({ name: 'vendor_name', nullable: true }) vendorName: string",
  "  @Column({ name: 'invoice_no', nullable: true }) invoiceNo: string",
  "  @Column({ name: 'invoice_date', type: 'date', nullable: true }) invoiceDate: string",
  "  @Column({ name: 'gross_amount', type: 'decimal', precision: 15, scale: 2, default: 0 }) grossAmount: number",
  "  @Column({ name: 'gst_rate', type: 'decimal', precision: 5, scale: 2, default: 0 }) gstRate: number",
  "  @Column({ name: 'gst_amount', type: 'decimal', precision: 15, scale: 2, default: 0 }) gstAmount: number",
  "  @Column({ name: 'tds_rate', type: 'decimal', precision: 5, scale: 2, default: 0 }) tdsRate: number",
  "  @Column({ name: 'tds_amount', type: 'decimal', precision: 15, scale: 2, default: 0 }) tdsAmount: number",
  "  @Column({ name: 'net_amount', type: 'decimal', precision: 15, scale: 2, default: 0 }) netAmount: number",
  "  @Column({ name: 'payment_mode', type: 'enum', enum: PaymentMode, nullable: true }) paymentMode: PaymentMode",
  "  @Column({ name: 'payment_ref', nullable: true }) paymentRef: string",
  "  @Column({ name: 'payment_date', type: 'date', nullable: true }) paymentDate: string",
  "  @Column({ type: 'enum', enum: TxStatus, default: TxStatus.PENDING }) status: TxStatus",
  "  @Column({ name: 'ra_bill_id', nullable: true }) raBillId: string",
  "  @Column({ type: 'text', nullable: true }) remarks: string",
  "  @Column({ name: 'approved_by', nullable: true }) approvedBy: string",
  "  @CreateDateColumn({ name: 'created_at' }) createdAt: Date",
  "}",
])

w(path.join(ACC, 'tds-ledger.entity.ts'), [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum TdsLedgerType { DEDUCTED = 'deducted', PAID = 'paid', ADJUSTED = 'adjusted' }",
  "",
  "@Entity('tds_ledger')",
  "export class TdsLedger extends BaseEntity {",
  "  @Column({ name: 'project_id', nullable: true }) projectId: string",
  "  @Column({ name: 'transaction_id', nullable: true }) transactionId: string",
  "  @Column({ name: 'vendor_id', nullable: true }) vendorId: string",
  "  @Column({ name: 'vendor_name', nullable: true }) vendorName: string",
  "  @Column({ name: 'deductee_pan', nullable: true }) deducteePan: string",
  "  @Column({ name: 'tds_section' }) tdsSection: string",
  "  @Column({ name: 'tds_rate', type: 'decimal', precision: 5, scale: 2 }) tdsRate: number",
  "  @Column({ name: 'taxable_amount', type: 'decimal', precision: 15, scale: 2 }) taxableAmount: number",
  "  @Column({ name: 'tds_amount', type: 'decimal', precision: 15, scale: 2 }) tdsAmount: number",
  "  @Column({ type: 'date' }) date: string",
  "  @Column({ type: 'enum', enum: TdsLedgerType, default: TdsLedgerType.DEDUCTED }) type: TdsLedgerType",
  "  @Column({ name: 'challan_no', nullable: true }) challanNo: string",
  "  @Column({ name: 'challan_date', type: 'date', nullable: true }) challanDate: string",
  "  @Column({ name: 'financial_year', nullable: true }) financialYear: string",
  "  @Column({ name: 'quarter', nullable: true }) quarter: string",
  "  @CreateDateColumn({ name: 'created_at' }) createdAt: Date",
  "}",
])
ok('3 entities — Vendor, Transaction, TdsLedger')

// ── Service ────────────────────────────────────────────────────
info('Writing AccountingService...')
w(path.join(ACC, 'accounting.service.ts'), [
  "import { Injectable, NotFoundException } from '@nestjs/common'",
  "import { InjectRepository } from '@nestjs/typeorm'",
  "import { Repository } from 'typeorm'",
  "import { Vendor } from './vendor.entity'",
  "import { Transaction, TxType, TxStatus } from './transaction.entity'",
  "import { TdsLedger, TdsLedgerType } from './tds-ledger.entity'",
  "",
  "@Injectable()",
  "export class AccountingService {",
  "  constructor(",
  "    @InjectRepository(Vendor)      private readonly vendorRepo: Repository<Vendor>,",
  "    @InjectRepository(Transaction) private readonly txRepo:     Repository<Transaction>,",
  "    @InjectRepository(TdsLedger)   private readonly tdsRepo:    Repository<TdsLedger>,",
  "  ) {}",
  "",
  "  // ── Vendors ────────────────────────────────────────────────",
  "  async createVendor(data: Partial<Vendor>): Promise<Vendor> {",
  "    return this.vendorRepo.save(this.vendorRepo.create(data))",
  "  }",
  "",
  "  async listVendors(p: { projectId?: string; category?: string; search?: string }) {",
  "    const qb = this.vendorRepo.createQueryBuilder('v')",
  "      .where('v.isActive = true').orderBy('v.name', 'ASC')",
  "    if (p.projectId) qb.andWhere('v.projectId = :pid OR v.projectId IS NULL', { pid: p.projectId })",
  "    if (p.category)  qb.andWhere('v.category = :cat', { cat: p.category })",
  "    if (p.search)    qb.andWhere('v.name ILIKE :s OR v.gstin ILIKE :s', { s: '%' + p.search + '%' })",
  "    return qb.getMany()",
  "  }",
  "",
  "  async updateVendor(id: string, data: Partial<Vendor>): Promise<Vendor> {",
  "    await this.vendorRepo.update(id, data)",
  "    const v = await this.vendorRepo.findOne({ where: { id } })",
  "    if (!v) throw new NotFoundException('Vendor not found')",
  "    return v",
  "  }",
  "",
  "  // ── Transactions ───────────────────────────────────────────",
  "  async createTransaction(data: Partial<Transaction>): Promise<Transaction> {",
  "    const gross  = Number(data.grossAmount ?? 0)",
  "    const gstPct = Number(data.gstRate ?? 0)",
  "    const tdsPct = Number(data.tdsRate ?? 0)",
  "    const gstAmt = parseFloat((gross * gstPct / 100).toFixed(2))",
  "    const tdsAmt = parseFloat((gross * tdsPct / 100).toFixed(2))",
  "    const netAmt = parseFloat((gross + gstAmt - tdsAmt).toFixed(2))",
  "",
  "    const tx = await this.txRepo.save(this.txRepo.create({",
  "      ...data, gstAmount: gstAmt, tdsAmount: tdsAmt, netAmount: netAmt,",
  "    }))",
  "",
  "    // Auto TDS ledger entry",
  "    if (tdsAmt > 0) {",
  "      const vendor = data.vendorId",
  "        ? await this.vendorRepo.findOne({ where: { id: data.vendorId } })",
  "        : null",
  "      const now = new Date()",
  "      const fy  = now.getMonth() >= 3",
  "        ? `${now.getFullYear()}-${now.getFullYear() + 1}`",
  "        : `${now.getFullYear() - 1}-${now.getFullYear()}`",
  "      const qtr = ['Q4','Q4','Q4','Q1','Q1','Q1','Q2','Q2','Q2','Q3','Q3','Q3'][now.getMonth()]",
  "      await this.tdsRepo.save(this.tdsRepo.create({",
  "        projectId: data.projectId, transactionId: tx.id,",
  "        vendorId: data.vendorId, vendorName: vendor?.name ?? data.vendorName,",
  "        deducteePan: vendor?.pan,",
  "        tdsSection: vendor?.tdsSection ?? '194C',",
  "        tdsRate: tdsPct, taxableAmount: gross, tdsAmount: tdsAmt,",
  "        date: data.date ?? new Date().toISOString().split('T')[0],",
  "        financialYear: fy, quarter: qtr,",
  "      }))",
  "    }",
  "    return tx",
  "  }",
  "",
  "  async listTransactions(p: { projectId?: string; type?: string; category?: string; status?: string; vendorId?: string; fromDate?: string; toDate?: string; limit?: number }) {",
  "    const qb = this.txRepo.createQueryBuilder('t').orderBy('t.date', 'DESC').addOrderBy('t.createdAt', 'DESC')",
  "    if (p.projectId) qb.andWhere('t.projectId = :pid', { pid: p.projectId })",
  "    if (p.type)      qb.andWhere('t.type = :type', { type: p.type })",
  "    if (p.category)  qb.andWhere('t.category = :cat', { cat: p.category })",
  "    if (p.status)    qb.andWhere('t.status = :s', { s: p.status })",
  "    if (p.vendorId)  qb.andWhere('t.vendorId = :vid', { vid: p.vendorId })",
  "    if (p.fromDate)  qb.andWhere('t.date >= :from', { from: p.fromDate })",
  "    if (p.toDate)    qb.andWhere('t.date <= :to', { to: p.toDate })",
  "    if (p.limit)     qb.limit(p.limit)",
  "    return qb.getMany()",
  "  }",
  "",
  "  async updateTransaction(id: string, data: Partial<Transaction>): Promise<Transaction> {",
  "    await this.txRepo.update(id, data)",
  "    const tx = await this.txRepo.findOne({ where: { id } })",
  "    if (!tx) throw new NotFoundException('Not found')",
  "    return tx",
  "  }",
  "",
  "  async markPaid(id: string, p: { paymentMode: string; paymentRef?: string; paymentDate?: string }): Promise<Transaction> {",
  "    await this.txRepo.update(id, {",
  "      status: TxStatus.PAID,",
  "      paymentMode: p.paymentMode as any,",
  "      paymentRef: p.paymentRef,",
  "      paymentDate: p.paymentDate ?? new Date().toISOString().split('T')[0],",
  "    })",
  "    return this.txRepo.findOne({ where: { id } }) as Promise<Transaction>",
  "  }",
  "",
  "  // ── TDS Ledger ─────────────────────────────────────────────",
  "  async listTds(p: { projectId?: string; vendorId?: string; financialYear?: string; quarter?: string }) {",
  "    const qb = this.tdsRepo.createQueryBuilder('t').orderBy('t.date', 'DESC')",
  "    if (p.projectId)     qb.andWhere('t.projectId = :pid', { pid: p.projectId })",
  "    if (p.vendorId)      qb.andWhere('t.vendorId = :vid', { vid: p.vendorId })",
  "    if (p.financialYear) qb.andWhere('t.financialYear = :fy', { fy: p.financialYear })",
  "    if (p.quarter)       qb.andWhere('t.quarter = :q', { q: p.quarter })",
  "    return qb.getMany()",
  "  }",
  "",
  "  async recordTdsPayment(data: Partial<TdsLedger>): Promise<TdsLedger> {",
  "    return this.tdsRepo.save(this.tdsRepo.create({ ...data, type: TdsLedgerType.PAID }))",
  "  }",
  "",
  "  // ── Dashboard ──────────────────────────────────────────────",
  "  async dashboard(projectId?: string) {",
  "    const txs      = await this.listTransactions({ projectId })",
  "    const expenses = txs.filter(t => t.type === TxType.EXPENSE)",
  "    const income   = txs.filter(t => t.type === TxType.INCOME)",
  "    const pending  = expenses.filter(t => t.status === 'pending')",
  "",
  "    const now = new Date()",
  "    const monthStart = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`",
  "",
  "    const byCategory: Record<string, number> = {}",
  "    for (const t of expenses) {",
  "      const c = t.category ?? 'other'",
  "      byCategory[c] = (byCategory[c] ?? 0) + Number(t.netAmount)",
  "    }",
  "",
  "    return {",
  "      totalExpenses:    expenses.reduce((s,t) => s + Number(t.netAmount), 0),",
  "      totalIncome:      income.reduce((s,t)   => s + Number(t.netAmount), 0),",
  "      totalPending:     pending.reduce((s,t)  => s + Number(t.netAmount), 0),",
  "      totalTds:         expenses.reduce((s,t) => s + Number(t.tdsAmount), 0),",
  "      totalGst:         expenses.reduce((s,t) => s + Number(t.gstAmount), 0),",
  "      thisMonthExpenses:expenses.filter(t => t.date >= monthStart).reduce((s,t) => s + Number(t.netAmount), 0),",
  "      pendingCount:     pending.length,",
  "      transactions:     txs.length,",
  "      byCategory,",
  "    }",
  "  }",
  "}",
])
ok('AccountingService')

// ── Controller ─────────────────────────────────────────────────
info('Writing AccountingController...')
w(path.join(ACC, 'accounting.controller.ts'), [
  "import { Controller, Get, Post, Patch, Param, Body, Query, UseGuards, HttpCode, HttpStatus } from '@nestjs/common'",
  "import { AccountingService } from './accounting.service'",
  "import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard'",
  "",
  "@Controller('accounting')",
  "@UseGuards(JwtAuthGuard)",
  "export class AccountingController {",
  "  constructor(private readonly svc: AccountingService) {}",
  "",
  "  @Get('dashboard')",
  "  dashboard(@Query('projectId') pid?: string) { return this.svc.dashboard(pid) }",
  "",
  "  @Get('vendors')",
  "  listVendors(@Query() q: any) {",
  "    return this.svc.listVendors({ projectId: q.projectId, category: q.category, search: q.search })",
  "  }",
  "  @Post('vendors') @HttpCode(HttpStatus.CREATED)",
  "  createVendor(@Body() body: any) { return this.svc.createVendor(body) }",
  "  @Patch('vendors/:id')",
  "  updateVendor(@Param('id') id: string, @Body() body: any) { return this.svc.updateVendor(id, body) }",
  "",
  "  @Get('transactions')",
  "  listTx(@Query() q: any) {",
  "    return this.svc.listTransactions({",
  "      projectId: q.projectId, type: q.type, category: q.category,",
  "      status: q.status, vendorId: q.vendorId,",
  "      fromDate: q.fromDate, toDate: q.toDate,",
  "      limit: q.limit ? parseInt(q.limit) : undefined,",
  "    })",
  "  }",
  "  @Post('transactions') @HttpCode(HttpStatus.CREATED)",
  "  createTx(@Body() body: any) { return this.svc.createTransaction(body) }",
  "  @Patch('transactions/:id')",
  "  updateTx(@Param('id') id: string, @Body() body: any) { return this.svc.updateTransaction(id, body) }",
  "  @Patch('transactions/:id/pay')",
  "  markPaid(@Param('id') id: string, @Body() body: any) {",
  "    return this.svc.markPaid(id, { paymentMode: body.paymentMode, paymentRef: body.paymentRef, paymentDate: body.paymentDate })",
  "  }",
  "",
  "  @Get('tds')",
  "  listTds(@Query() q: any) {",
  "    return this.svc.listTds({ projectId: q.projectId, vendorId: q.vendorId, financialYear: q.financialYear, quarter: q.quarter })",
  "  }",
  "  @Post('tds/payment') @HttpCode(HttpStatus.CREATED)",
  "  recordTdsPay(@Body() body: any) { return this.svc.recordTdsPayment(body) }",
  "}",
])
ok('AccountingController')

// ── Module ─────────────────────────────────────────────────────
w(path.join(ACC, 'accounting.module.ts'), [
  "import { Module } from '@nestjs/common'",
  "import { TypeOrmModule } from '@nestjs/typeorm'",
  "import { Vendor }      from './vendor.entity'",
  "import { Transaction } from './transaction.entity'",
  "import { TdsLedger }  from './tds-ledger.entity'",
  "import { AccountingService }    from './accounting.service'",
  "import { AccountingController } from './accounting.controller'",
  "",
  "@Module({",
  "  imports: [TypeOrmModule.forFeature([Vendor, Transaction, TdsLedger])],",
  "  providers: [AccountingService], controllers: [AccountingController], exports: [AccountingService],",
  "})",
  "export class AccountingModule {}",
])
ok('AccountingModule')

// ── Register in app.module.ts ──────────────────────────────────
info('Registering in app.module.ts...')
const appModulePath = path.join(SRC, 'app.module.ts')
let appModule = fs.readFileSync(appModulePath, 'utf8')
if (!appModule.includes("from './accounting/accounting.module'")) {
  appModule = appModule.replace(
    "import { EpcModule }",
    "import { AccountingModule } from './accounting/accounting.module'\nimport { EpcModule }"
  )
  appModule = appModule.replace('EpcModule,', 'EpcModule,\n    AccountingModule,')
  fs.writeFileSync(appModulePath, appModule)
  ok('AccountingModule registered')
} else { ok('Already registered') }

console.log('\n' + G + '\x1b[1m  Backend done. Run frontend next.\x1b[0m' + NC + '\n')
