// ================================================================
//  KIPL ProjectOS — EPC / BOQ Backend
//  Pre-loaded with actual Dal Lake project data
//  Run: node scripts/modules/epc/backend.js
// ================================================================
const fs   = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..', '..', '..')
const SRC  = path.join(ROOT, 'backend', 'src')
const EPC  = path.join(SRC, 'epc')

const G = '\x1b[32m', B = '\x1b[34m', NC = '\x1b[0m'
const ok   = s => console.log(G + '  ✓' + NC + ' ' + s)
const info = s => console.log(B + '  →' + NC + ' ' + s)
function w(p, lines) {
  fs.mkdirSync(path.dirname(p), { recursive: true })
  fs.writeFileSync(p, lines.join('\n'), 'utf8')
}

if (!fs.existsSync(SRC)) { console.error('backend/src not found'); process.exit(1) }
fs.mkdirSync(EPC, { recursive: true })
fs.mkdirSync(path.join(EPC, 'dto'), { recursive: true })

console.log('\n\x1b[1mBuilding EPC / BOQ Module — Backend\x1b[0m\n')

// ── BOQ Item entity ────────────────────────────────────────────
info('Writing entities...')
w('boq-item.entity.ts', [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum BoqCategory {",
  "  SEWER_NETWORK   = 'sewer_network',",
  "  IPS_CIVIL       = 'ips_civil',",
  "  IPS_EM          = 'ips_em',",
  "  STP_CIVIL       = 'stp_civil',",
  "  STP_EM          = 'stp_em',",
  "  RISING_MAIN     = 'rising_main',",
  "  ROAD_WORK       = 'road_work',",
  "  OTHER           = 'other',",
  "}",
  "",
  "@Entity('boq_items')",
  "export class BoqItem extends BaseEntity {",
  "  @Column({ name: 'project_id' }) projectId: string",
  "  @Column({ name: 'sl_no', nullable: true }) slNo: string",
  "  @Column({ name: 'sor_ref', nullable: true }) sorRef: string",
  "  @Column({ type: 'text' }) description: string",
  "  @Column({ nullable: true }) unit: string",
  "  @Column({ type: 'enum', enum: BoqCategory, default: BoqCategory.SEWER_NETWORK }) category: BoqCategory",
  "  @Column({ nullable: true }) subCategory: string",
  "  @Column({ type: 'decimal', precision: 15, scale: 3, default: 0 }) estimatedQty: number",
  "  @Column({ type: 'decimal', precision: 15, scale: 2, default: 0 }) rate: number",
  "  @Column({ type: 'decimal', precision: 15, scale: 2, default: 0 }) estimatedAmount: number",
  "  @Column({ type: 'decimal', precision: 15, scale: 2, default: 0 }) quotedRate: number",
  "  @Column({ type: 'decimal', precision: 15, scale: 2, default: 0 }) quotedAmount: number",
  "  @Column({ type: 'decimal', precision: 15, scale: 3, default: 0 }) measuredQty: number",
  "  @Column({ type: 'decimal', precision: 15, scale: 2, default: 0 }) measuredAmount: number",
  "  @Column({ name: 'payment_milestone', nullable: true }) paymentMilestone: string",
  "  @Column({ name: 'payment_pct', type: 'decimal', precision: 5, scale: 2, default: 0 }) paymentPct: number",
  "  @Column({ name: 'is_active', default: true }) isActive: boolean",
  "  @CreateDateColumn({ name: 'created_at' }) createdAt: Date",
  "}",
].map(l => l.startsWith('  ') || l.startsWith('@') || l.startsWith('import') || l.startsWith('export') || l === '' ? l : '  ' + l))

// Fix the entity properly
w(path.join(EPC, 'boq-item.entity.ts'), [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum BoqCategory {",
  "  SEWER_NETWORK = 'sewer_network',",
  "  IPS_CIVIL     = 'ips_civil',",
  "  IPS_EM        = 'ips_em',",
  "  STP_CIVIL     = 'stp_civil',",
  "  STP_EM        = 'stp_em',",
  "  RISING_MAIN   = 'rising_main',",
  "  ROAD_WORK     = 'road_work',",
  "  OTHER         = 'other',",
  "}",
  "",
  "@Entity('boq_items')",
  "export class BoqItem extends BaseEntity {",
  "  @Column({ name: 'project_id' })",
  "  projectId: string",
  "",
  "  @Column({ name: 'sl_no', nullable: true })",
  "  slNo: string",
  "",
  "  @Column({ name: 'sor_ref', nullable: true })",
  "  sorRef: string",
  "",
  "  @Column({ type: 'text' })",
  "  description: string",
  "",
  "  @Column({ nullable: true })",
  "  unit: string",
  "",
  "  @Column({ type: 'enum', enum: BoqCategory, default: BoqCategory.SEWER_NETWORK })",
  "  category: BoqCategory",
  "",
  "  @Column({ name: 'sub_category', nullable: true })",
  "  subCategory: string",
  "",
  "  @Column({ type: 'decimal', precision: 15, scale: 3, default: 0 })",
  "  estimatedQty: number",
  "",
  "  @Column({ type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  rate: number",
  "",
  "  @Column({ name: 'estimated_amount', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  estimatedAmount: number",
  "",
  "  @Column({ name: 'quoted_rate', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  quotedRate: number",
  "",
  "  @Column({ name: 'quoted_amount', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  quotedAmount: number",
  "",
  "  @Column({ name: 'measured_qty', type: 'decimal', precision: 15, scale: 3, default: 0 })",
  "  measuredQty: number",
  "",
  "  @Column({ name: 'measured_amount', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  measuredAmount: number",
  "",
  "  @Column({ name: 'payment_milestone', nullable: true })",
  "  paymentMilestone: string",
  "",
  "  @Column({ name: 'payment_pct', type: 'decimal', precision: 5, scale: 2, default: 0 })",
  "  paymentPct: number",
  "",
  "  @Column({ name: 'is_active', default: true })",
  "  isActive: boolean",
  "",
  "  @CreateDateColumn({ name: 'created_at' })",
  "  createdAt: Date",
  "}",
])
ok('BoqItem entity')

// ── RA Bill entity ─────────────────────────────────────────────
w(path.join(EPC, 'ra-bill.entity.ts'), [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum RaBillStatus {",
  "  DRAFT     = 'draft',",
  "  SUBMITTED = 'submitted',",
  "  VERIFIED  = 'verified',",
  "  APPROVED  = 'approved',",
  "  PAID      = 'paid',",
  "  REJECTED  = 'rejected',",
  "}",
  "",
  "@Entity('ra_bills')",
  "export class RaBill extends BaseEntity {",
  "  @Column({ name: 'project_id' })",
  "  projectId: string",
  "",
  "  @Column({ name: 'bill_no' })",
  "  billNo: string",
  "",
  "  @Column({ name: 'allotment_no', nullable: true })",
  "  allotmentNo: string",
  "",
  "  @Column({ name: 'bill_date', type: 'date' })",
  "  billDate: string",
  "",
  "  @Column({ name: 'period_from', type: 'date', nullable: true })",
  "  periodFrom: string",
  "",
  "  @Column({ name: 'period_to', type: 'date', nullable: true })",
  "  periodTo: string",
  "",
  "  // Array of line items: { boqItemId, description, unit, measuredQty, rate, amount, milestone, pct }",
  "  @Column({ type: 'jsonb', default: [] })",
  "  lineItems: any[]",
  "",
  "  @Column({ name: 'gross_amount', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  grossAmount: number",
  "",
  "  @Column({ name: 'prev_billed', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  prevBilled: number",
  "",
  "  @Column({ name: 'net_this_bill', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  netThisBill: number",
  "",
  "  @Column({ name: 'gst_pct', type: 'decimal', precision: 5, scale: 2, default: 0 })",
  "  gstPct: number",
  "",
  "  @Column({ name: 'gst_amount', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  gstAmount: number",
  "",
  "  @Column({ name: 'tds_pct', type: 'decimal', precision: 5, scale: 2, default: 0 })",
  "  tdsPct: number",
  "",
  "  @Column({ name: 'tds_amount', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  tdsAmount: number",
  "",
  "  @Column({ name: 'security_deposit_pct', type: 'decimal', precision: 5, scale: 2, default: 0 })",
  "  securityDepositPct: number",
  "",
  "  @Column({ name: 'security_deposit_amount', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  securityDepositAmount: number",
  "",
  "  @Column({ name: 'net_payable', type: 'decimal', precision: 15, scale: 2, default: 0 })",
  "  netPayable: number",
  "",
  "  @Column({ name: 'amount_in_words', nullable: true })",
  "  amountInWords: string",
  "",
  "  @Column({ type: 'enum', enum: RaBillStatus, default: RaBillStatus.DRAFT })",
  "  status: RaBillStatus",
  "",
  "  @Column({ name: 'submitted_date', type: 'date', nullable: true })",
  "  submittedDate: string",
  "",
  "  @Column({ name: 'approved_date', type: 'date', nullable: true })",
  "  approvedDate: string",
  "",
  "  @Column({ name: 'paid_date', type: 'date', nullable: true })",
  "  paidDate: string",
  "",
  "  @Column({ name: 'remarks', type: 'text', nullable: true })",
  "  remarks: string",
  "",
  "  @CreateDateColumn({ name: 'created_at' })",
  "  createdAt: Date",
  "}",
])
ok('RaBill entity')

// ── Measurement Book entity ────────────────────────────────────
w(path.join(EPC, 'measurement.entity.ts'), [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "@Entity('measurements')",
  "export class Measurement extends BaseEntity {",
  "  @Column({ name: 'project_id' }) projectId: string",
  "  @Column({ name: 'boq_item_id' }) boqItemId: string",
  "  @Column({ name: 'ra_bill_id', nullable: true }) raBillId: string",
  "  @Column({ name: 'mb_no', nullable: true }) mbNo: string",
  "  @Column({ name: 'mb_page', nullable: true }) mbPage: string",
  "  @Column({ type: 'date' }) date: string",
  "  @Column({ type: 'text' }) location: string",
  "  @Column({ type: 'jsonb', default: [] }) entries: any[] // [{no,l,b,h,qty,remarks}]",
  "  @Column({ type: 'decimal', precision: 15, scale: 3, default: 0 }) totalQty: number",
  "  @Column({ name: 'measured_by', nullable: true }) measuredBy: string",
  "  @Column({ name: 'checked_by', nullable: true }) checkedBy: string",
  "  @Column({ type: 'text', nullable: true }) remarks: string",
  "  @CreateDateColumn({ name: 'created_at' }) createdAt: Date",
  "}",
])
ok('Measurement entity')

// ── EPC Service ────────────────────────────────────────────────
info('Writing EpcService...')
w(path.join(EPC, 'epc.service.ts'), [
  "import { Injectable, NotFoundException } from '@nestjs/common'",
  "import { InjectRepository } from '@nestjs/typeorm'",
  "import { Repository } from 'typeorm'",
  "import { BoqItem, BoqCategory } from './boq-item.entity'",
  "import { RaBill, RaBillStatus } from './ra-bill.entity'",
  "import { Measurement } from './measurement.entity'",
  "",
  "// Dal Lake project pre-loaded BOQ items",
  "const DAL_LAKE_BOQ = [",
  "  // ── ITEM 1: Sewer Network ──────────────────────────────────",
  "  {",
  "    slNo: '1A', sorRef: 'NS',",
  "    description: 'Providing and Laying non-pressure (NP3) RCC socket & spigot pipes with rubber gasket joint incl. testing — 200mm dia',",
  "    unit: 'M', category: BoqCategory.SEWER_NETWORK, subCategory: 'RCC NP3 Pipes',",
  "    estimatedQty: 184793, rate: 566.40, estimatedAmount: 10466675.52,",
  "  },",
  "  {",
  "    slNo: '1B', sorRef: 'NS',",
  "    description: 'RCC NP3 pipes — 250mm dia',",
  "    unit: 'M', category: BoqCategory.SEWER_NETWORK, subCategory: 'RCC NP3 Pipes',",
  "    estimatedQty: 4016, rate: 666.00, estimatedAmount: 2674656,",
  "  },",
  "  {",
  "    slNo: '1C', sorRef: 'NS',",
  "    description: 'RCC NP3 pipes — 300mm dia',",
  "    unit: 'M', category: BoqCategory.SEWER_NETWORK, subCategory: 'RCC NP3 Pipes',",
  "    estimatedQty: 4938, rate: 1274.40, estimatedAmount: 6292987.20,",
  "  },",
  "  {",
  "    slNo: '1D', sorRef: 'NS',",
  "    description: 'RCC NP3 pipes — 700mm dia',",
  "    unit: 'M', category: BoqCategory.SEWER_NETWORK, subCategory: 'RCC NP3 Pipes',",
  "    estimatedQty: 5676, rate: 4536.00, estimatedAmount: 25746336,",
  "  },",
  "  {",
  "    slNo: '1E', sorRef: 'NS',",
  "    description: 'RCC NP3 pipes — 900mm dia',",
  "    unit: 'M', category: BoqCategory.SEWER_NETWORK, subCategory: 'RCC NP3 Pipes',",
  "    estimatedQty: 1180, rate: 5664.00, estimatedAmount: 6683520,",
  "  },",
  "  {",
  "    slNo: '1F', sorRef: 'NS',",
  "    description: 'RCC NP3 pipes — 1000mm dia',",
  "    unit: 'M', category: BoqCategory.SEWER_NETWORK, subCategory: 'RCC NP3 Pipes',",
  "    estimatedQty: 302, rate: 6372.00, estimatedAmount: 1924344,",
  "  },",
  "  {",
  "    slNo: '2', sorRef: 'J&K SOR 2022 2.9',",
  "    description: 'Earth work in excavation by mechanical means in trenches — 0.00 to 1.50m depth, ordinary soil',",
  "    unit: 'Cum', category: BoqCategory.SEWER_NETWORK, subCategory: 'Earthwork',",
  "    estimatedQty: 241513.56, rate: 256.85, estimatedAmount: 62032757.19,",
  "  },",
  "  {",
  "    slNo: '3', sorRef: 'J&K SOR 2022 2.11',",
  "    description: 'Filling available excavated earth in trenches — layer not exceeding 20cm, ramming and watering',",
  "    unit: 'Cum', category: BoqCategory.SEWER_NETWORK, subCategory: 'Earthwork',",
  "    estimatedQty: 524187.19, rate: 218.40, estimatedAmount: 114482481.47,",
  "  },",
  "  {",
  "    slNo: '4', sorRef: 'Unit Est.',",
  "    description: 'RCC circular Manholes — 910mm dia x 1670mm depth',",
  "    unit: 'Nos', category: BoqCategory.SEWER_NETWORK, subCategory: 'Manholes',",
  "    estimatedQty: 909, rate: 57022.72, estimatedAmount: 51833648,",
  "  },",
  "  {",
  "    slNo: '5', sorRef: 'Unit Est.',",
  "    description: 'RCC circular Manholes — 1220mm dia x 2290mm depth',",
  "    unit: 'Nos', category: BoqCategory.SEWER_NETWORK, subCategory: 'Manholes',",
  "    estimatedQty: 481, rate: 100439.78, estimatedAmount: 48311533.79,",
  "  },",
  "  {",
  "    slNo: '6', sorRef: 'Unit Est.',",
  "    description: 'RCC circular Manholes — 1520mm dia x 4950mm depth',",
  "    unit: 'Nos', category: BoqCategory.SEWER_NETWORK, subCategory: 'Manholes',",
  "    estimatedQty: 2071, rate: 275488.98, estimatedAmount: 570537669.32,",
  "  },",
  "  {",
  "    slNo: '7', sorRef: 'Unit Est.',",
  "    description: 'RCC circular Manholes — 1520mm dia x 9000mm depth',",
  "    unit: 'Nos', category: BoqCategory.SEWER_NETWORK, subCategory: 'Manholes',",
  "    estimatedQty: 267, rate: 643192.52, estimatedAmount: 171732403.41,",
  "  },",
  "  {",
  "    slNo: '8', sorRef: 'Unit Est.',",
  "    description: 'Drop arrangement in manholes — 200mm dia',",
  "    unit: 'M', category: BoqCategory.SEWER_NETWORK, subCategory: 'Drop Arrangements',",
  "    estimatedQty: 1299.87, rate: 23063.00, estimatedAmount: 29978901.81,",
  "  },",
  "  {",
  "    slNo: '9', sorRef: 'Unit Est.',",
  "    description: 'Masonry chamber 45x45x60cm with CI Cover — house sewer connecting chamber',",
  "    unit: 'Nos', category: BoqCategory.SEWER_NETWORK, subCategory: 'Masonry Chambers',",
  "    estimatedQty: 12651, rate: 16438.94, estimatedAmount: 207972313.37,",
  "  },",
  "  {",
  "    slNo: '10', sorRef: 'Unit Est.',",
  "    description: 'Masonry chamber 60x60x60cm with CI Cover',",
  "    unit: 'Nos', category: BoqCategory.SEWER_NETWORK, subCategory: 'Masonry Chambers',",
  "    estimatedQty: 3163, rate: 21228.33, estimatedAmount: 67140966.23,",
  "  },",
  "  {",
  "    slNo: '11', sorRef: 'J&K SOR 16.14.1',",
  "    description: 'Cutting bitumen road and making good — supply of aggregate, moorum, screening',",
  "    unit: 'Cum', category: BoqCategory.ROAD_WORK, subCategory: 'Road Cutting',",
  "    estimatedQty: 48046.17, rate: 4000.40, estimatedAmount: 192203910.47,",
  "  },",
  "  // ── ITEM 2: IPS (Turnkey Civil) ────────────────────────────",
  "  {",
  "    slNo: '12', sorRef: 'Det. Est.',",
  "    description: 'IPS-1 — Screen channel, pump house, sump RCC M-25 2.50m dia x 7.70m depth at Node 102',",
  "    unit: 'LS', category: BoqCategory.IPS_CIVIL, subCategory: 'IPS-1',",
  "    estimatedQty: 1, rate: 5451000, estimatedAmount: 5451000,",
  "  },",
  "  {",
  "    slNo: '13', sorRef: 'Det. Est.',",
  "    description: 'IPS-3 — Screen channel, pump house, sump RCC M-25 5.00m dia x 7.19m depth at Node 1053',",
  "    unit: 'LS', category: BoqCategory.IPS_CIVIL, subCategory: 'IPS-3',",
  "    estimatedQty: 1, rate: 8747000, estimatedAmount: 8747000,",
  "  },",
  "  {",
  "    slNo: '14', sorRef: 'Det. Est.',",
  "    description: 'IPS-5 — Screen channel, pump house, sump RCC M-25 8.00m dia x 9.89m depth at Node 1532',",
  "    unit: 'LS', category: BoqCategory.IPS_CIVIL, subCategory: 'IPS-5',",
  "    estimatedQty: 1, rate: 16293000, estimatedAmount: 16293000,",
  "  },",
  "  {",
  "    slNo: '15', sorRef: 'Det. Est.',",
  "    description: 'IPS-9 — Screen channel, pump house, sump RCC M-25 10.00m dia x 10.77m depth at Node 4011 (Largest)',",
  "    unit: 'LS', category: BoqCategory.IPS_CIVIL, subCategory: 'IPS-9',",
  "    estimatedQty: 1, rate: 22069000, estimatedAmount: 22069000,",
  "  },",
  "  // ── ITEM 2: STP (Turnkey Civil + E&M) ─────────────────────",
  "  {",
  "    slNo: '16', sorRef: 'Det. Est.',",
  "    description: 'STP 30 MLD — SBR Technology, including office building, lab & equipment, campus development, boundary wall, water supply, drainage, sewerage, electrification, SCADA',",
  "    unit: 'LS', category: BoqCategory.STP_CIVIL, subCategory: 'STP Civil',",
  "    estimatedQty: 1, rate: 204000000, estimatedAmount: 204000000,",
  "  },",
  "  {",
  "    slNo: '17', sorRef: 'Det. Est.',",
  "    description: 'STP 30 MLD — Electro-Mechanical components, SCADA, online monitoring system',",
  "    unit: 'LS', category: BoqCategory.STP_EM, subCategory: 'STP E&M',",
  "    estimatedQty: 1, rate: 306000000, estimatedAmount: 306000000,",
  "  },",
  "  {",
  "    slNo: '18', sorRef: 'Det. Est.',",
  "    description: 'Rising main — IPS-9 to MPS (Node 4011), 700mm dia, 870m',",
  "    unit: 'M', category: BoqCategory.RISING_MAIN, subCategory: 'Rising Mains',",
  "    estimatedQty: 870, rate: 15000, estimatedAmount: 13050000,",
  "  },",
  "  {",
  "    slNo: '19', sorRef: 'Det. Est.',",
  "    description: 'MPS (Main Pumping Station) at Habak — civil and E&M works',",
  "    unit: 'LS', category: BoqCategory.IPS_CIVIL, subCategory: 'MPS',",
  "    estimatedQty: 1, rate: 22500000, estimatedAmount: 22500000,",
  "  },",
  "  {",
  "    slNo: '20', sorRef: 'Det. Est.',",
  "    description: 'Staff quarters at STP site',",
  "    unit: 'LS', category: BoqCategory.STP_CIVIL, subCategory: 'STP Civil',",
  "    estimatedQty: 1, rate: 2318000, estimatedAmount: 2318000,",
  "  },",
  "]",
  "",
  "// Payment schedule milestones from tender Clause 23.3",
  "const PAYMENT_MILESTONES = {",
  "  sewer_network: [",
  "    { code: 'S1', name: 'Survey & Vetting of Design', pct: 5 },",
  "    { code: 'S2', name: 'Providing & Laying Pipes + Backfilling + Temp Reinstatement', pct: 55 },",
  "    { code: 'S3', name: 'Sectional Flow Testing', pct: 10 },",
  "    { code: 'S4', name: 'Permanent Road Reinstatement', pct: 20 },",
  "    { code: 'S5', name: 'Testing, Commissioning & Trial Run', pct: 5 },",
  "    { code: 'S6', name: 'O&M for 5 Years', pct: 5 },",
  "  ],",
  "  civil_stp_ips: [",
  "    { code: 'C1', name: 'Survey & Vetting of Design', pct: 5 },",
  "    { code: 'C2', name: 'Building to Plinth / 25% Completion', pct: 20 },",
  "    { code: 'C3', name: '60% Completion of Civil Structure', pct: 30 },",
  "    { code: 'C4', name: 'Complete Finishing as per Approved Drawings', pct: 30 },",
  "    { code: 'C5', name: 'Testing & Commissioning of STP/IPS', pct: 5 },",
  "    { code: 'C6', name: 'After Issuance of Completion Certificate by UEED', pct: 5 },",
  "    { code: 'C7', name: 'O&M for 5 Years', pct: 5 },",
  "  ],",
  "  electro_mechanical: [",
  "    { code: 'E1', name: 'Delivery of E&M Components at Site after TPI', pct: 40 },",
  "    { code: 'E2', name: 'Installation, Erection & Testing at Site', pct: 25 },",
  "    { code: 'E3', name: 'Commissioning of E&M Components', pct: 10 },",
  "    { code: 'E4', name: 'Successful Completion of 6 Months Free Trial Run', pct: 10 },",
  "    { code: 'E5', name: 'Successful Completion of Defect Liability Period', pct: 10 },",
  "    { code: 'E6', name: 'O&M for 5 Years', pct: 5 },",
  "  ],",
  "  om_component: [",
  "    { code: 'O1', name: '1st Year O&M', pct: 0.5 },",
  "    { code: 'O2', name: '2nd Year O&M', pct: 0.5 },",
  "    { code: 'O3', name: '3rd Year O&M', pct: 1.0 },",
  "    { code: 'O4', name: '4th Year O&M', pct: 1.5 },",
  "    { code: 'O5', name: '5th Year O&M', pct: 1.5 },",
  "  ],",
  "}",
  "",
  "@Injectable()",
  "export class EpcService {",
  "  constructor(",
  "    @InjectRepository(BoqItem)     private readonly boqRepo:  Repository<BoqItem>,",
  "    @InjectRepository(RaBill)      private readonly raRepo:   Repository<RaBill>,",
  "    @InjectRepository(Measurement) private readonly mbRepo:   Repository<Measurement>,",
  "  ) {}",
  "",
  "  getPaymentMilestones() { return PAYMENT_MILESTONES }",
  "",
  "  // ── BOQ Items ──────────────────────────────────────────────",
  "  async seedBoqItems(projectId: string): Promise<{ seeded: number }> {",
  "    const existing = await this.boqRepo.count({ where: { projectId } })",
  "    if (existing > 0) return { seeded: 0 }",
  "    const items = DAL_LAKE_BOQ.map(item => this.boqRepo.create({ ...item, projectId }))",
  "    await this.boqRepo.save(items)",
  "    return { seeded: items.length }",
  "  }",
  "",
  "  async listBoqItems(projectId: string, category?: string) {",
  "    const qb = this.boqRepo.createQueryBuilder('b')",
  "      .where('b.projectId = :pid', { pid: projectId })",
  "      .andWhere('b.isActive = true')",
  "      .orderBy('b.slNo', 'ASC')",
  "    if (category) qb.andWhere('b.category = :cat', { cat: category })",
  "    return qb.getMany()",
  "  }",
  "",
  "  async createBoqItem(data: Partial<BoqItem>): Promise<BoqItem> {",
  "    return this.boqRepo.save(this.boqRepo.create(data))",
  "  }",
  "",
  "  async updateBoqItem(id: string, data: Partial<BoqItem>): Promise<BoqItem> {",
  "    await this.boqRepo.update(id, data)",
  "    const item = await this.boqRepo.findOne({ where: { id } })",
  "    if (!item) throw new NotFoundException('BOQ item not found')",
  "    return item",
  "  }",
  "",
  "  async updateMeasuredQty(id: string, measuredQty: number): Promise<BoqItem> {",
  "    const item = await this.boqRepo.findOne({ where: { id } })",
  "    if (!item) throw new NotFoundException('BOQ item not found')",
  "    const measuredAmount = measuredQty * Number(item.rate)",
  "    await this.boqRepo.update(id, { measuredQty, measuredAmount })",
  "    return this.boqRepo.findOne({ where: { id } }) as Promise<BoqItem>",
  "  }",
  "",
  "  async boqSummary(projectId: string) {",
  "    const items = await this.listBoqItems(projectId)",
  "    const totalEstimated  = items.reduce((s, i) => s + Number(i.estimatedAmount), 0)",
  "    const totalMeasured   = items.reduce((s, i) => s + Number(i.measuredAmount), 0)",
  "    const totalQty = items.reduce((s, i) => s + Number(i.estimatedQty), 0)",
  "    const measuredQty = items.reduce((s, i) => s + Number(i.measuredQty), 0)",
  "",
  "    // By category",
  "    const byCategory: Record<string, any> = {}",
  "    for (const item of items) {",
  "      const cat = item.category",
  "      if (!byCategory[cat]) byCategory[cat] = { estimated: 0, measured: 0, items: 0 }",
  "      byCategory[cat].estimated += Number(item.estimatedAmount)",
  "      byCategory[cat].measured  += Number(item.measuredAmount)",
  "      byCategory[cat].items++",
  "    }",
  "",
  "    const raBills = await this.raRepo.find({ where: { projectId } })",
  "    const totalBilled = raBills.filter(b => b.status !== RaBillStatus.REJECTED)",
  "      .reduce((s, b) => s + Number(b.netPayable), 0)",
  "",
  "    return {",
  "      totalEstimated,",
  "      totalMeasured,",
  "      percentageComplete: totalEstimated > 0 ? (totalMeasured / totalEstimated * 100).toFixed(2) : '0',",
  "      totalBilled,",
  "      balance: totalEstimated - totalBilled,",
  "      items: items.length,",
  "      byCategory,",
  "      raBills: raBills.length,",
  "    }",
  "  }",
  "",
  "  // ── RA Bills ───────────────────────────────────────────────",
  "  async createRaBill(data: Partial<RaBill>): Promise<RaBill> {",
  "    // Auto-calculate deductions",
  "    const gross = Number(data.grossAmount ?? 0)",
  "    const prevBilled = Number(data.prevBilled ?? 0)",
  "    const netThisBill = gross - prevBilled",
  "    const gstPct = Number(data.gstPct ?? 0)",
  "    const tdsPct = Number(data.tdsPct ?? 2)",
  "    const sdPct  = Number(data.securityDepositPct ?? 5)",
  "    const gstAmt = netThisBill * gstPct / 100",
  "    const tdsAmt = (netThisBill + gstAmt) * tdsPct / 100",
  "    const sdAmt  = netThisBill * sdPct / 100",
  "    const netPayable = netThisBill + gstAmt - tdsAmt - sdAmt",
  "",
  "    return this.raRepo.save(this.raRepo.create({",
  "      ...data,",
  "      netThisBill,",
  "      gstAmount: gstAmt,",
  "      tdsAmount: tdsAmt,",
  "      securityDepositAmount: sdAmt,",
  "      netPayable,",
  "    }))",
  "  }",
  "",
  "  async listRaBills(projectId: string) {",
  "    return this.raRepo.find({",
  "      where: { projectId },",
  "      order: { createdAt: 'DESC' },",
  "    })",
  "  }",
  "",
  "  async getRaBill(id: string): Promise<RaBill> {",
  "    const bill = await this.raRepo.findOne({ where: { id } })",
  "    if (!bill) throw new NotFoundException('RA Bill not found')",
  "    return bill",
  "  }",
  "",
  "  async updateRaBillStatus(id: string, status: RaBillStatus, remarks?: string): Promise<RaBill> {",
  "    const update: any = { status }",
  "    if (status === RaBillStatus.SUBMITTED) update.submittedDate = new Date().toISOString().split('T')[0]",
  "    if (status === RaBillStatus.APPROVED)  update.approvedDate  = new Date().toISOString().split('T')[0]",
  "    if (status === RaBillStatus.PAID)      update.paidDate      = new Date().toISOString().split('T')[0]",
  "    if (remarks) update.remarks = remarks",
  "    await this.raRepo.update(id, update)",
  "    return this.getRaBill(id)",
  "  }",
  "",
  "  // ── Measurement Book ───────────────────────────────────────",
  "  async addMeasurement(data: Partial<Measurement>): Promise<Measurement> {",
  "    const m = await this.mbRepo.save(this.mbRepo.create(data))",
  "    // Update BOQ item measured qty",
  "    const all = await this.mbRepo.find({ where: { boqItemId: data.boqItemId } })",
  "    const totalQty = all.reduce((s, mb) => s + Number(mb.totalQty), 0)",
  "    await this.updateMeasuredQty(data.boqItemId!, totalQty)",
  "    return m",
  "  }",
  "",
  "  async listMeasurements(p: { projectId?: string; boqItemId?: string; raBillId?: string }) {",
  "    const qb = this.mbRepo.createQueryBuilder('m').orderBy('m.date', 'DESC')",
  "    if (p.projectId)  qb.andWhere('m.projectId = :pid', { pid: p.projectId })",
  "    if (p.boqItemId)  qb.andWhere('m.boqItemId = :bid', { bid: p.boqItemId })",
  "    if (p.raBillId)   qb.andWhere('m.raBillId = :rid', { rid: p.raBillId })",
  "    return qb.getMany()",
  "  }",
  "}",
])
ok('EpcService with real Dal Lake BOQ data')

// ── EPC Controller ─────────────────────────────────────────────
info('Writing EpcController...')
w(path.join(EPC, 'epc.controller.ts'), [
  "import { Controller, Get, Post, Patch, Param, Body, Query, UseGuards, HttpCode, HttpStatus } from '@nestjs/common'",
  "import { EpcService } from './epc.service'",
  "import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard'",
  "import { RaBillStatus } from './ra-bill.entity'",
  "",
  "@Controller('epc')",
  "@UseGuards(JwtAuthGuard)",
  "export class EpcController {",
  "  constructor(private readonly svc: EpcService) {}",
  "",
  "  @Get('payment-milestones')",
  "  milestones() { return this.svc.getPaymentMilestones() }",
  "",
  "  // BOQ",
  "  @Get('boq')",
  "  listBoq(@Query('projectId') pid: string, @Query('category') cat?: string) {",
  "    return this.svc.listBoqItems(pid, cat)",
  "  }",
  "",
  "  @Post('boq')",
  "  @HttpCode(HttpStatus.CREATED)",
  "  createBoq(@Body() body: any) { return this.svc.createBoqItem(body) }",
  "",
  "  @Patch('boq/:id')",
  "  updateBoq(@Param('id') id: string, @Body() body: any) { return this.svc.updateBoqItem(id, body) }",
  "",
  "  @Patch('boq/:id/measure')",
  "  measure(@Param('id') id: string, @Body('measuredQty') qty: number) {",
  "    return this.svc.updateMeasuredQty(id, qty)",
  "  }",
  "",
  "  @Get('boq/summary')",
  "  summary(@Query('projectId') pid: string) { return this.svc.boqSummary(pid) }",
  "",
  "  @Post('boq/seed')",
  "  @HttpCode(HttpStatus.CREATED)",
  "  seedBoq(@Body('projectId') projectId: string) { return this.svc.seedBoqItems(projectId) }",
  "",
  "  // RA Bills",
  "  @Get('ra-bills')",
  "  listRa(@Query('projectId') pid: string) { return this.svc.listRaBills(pid) }",
  "",
  "  @Post('ra-bills')",
  "  @HttpCode(HttpStatus.CREATED)",
  "  createRa(@Body() body: any) { return this.svc.createRaBill(body) }",
  "",
  "  @Get('ra-bills/:id')",
  "  getRa(@Param('id') id: string) { return this.svc.getRaBill(id) }",
  "",
  "  @Patch('ra-bills/:id/status')",
  "  updateStatus(@Param('id') id: string, @Body('status') status: RaBillStatus, @Body('remarks') remarks?: string) {",
  "    return this.svc.updateRaBillStatus(id, status, remarks)",
  "  }",
  "",
  "  // Measurements",
  "  @Get('measurements')",
  "  listMb(@Query() q: any) {",
  "    return this.svc.listMeasurements({ projectId: q.projectId, boqItemId: q.boqItemId, raBillId: q.raBillId })",
  "  }",
  "",
  "  @Post('measurements')",
  "  @HttpCode(HttpStatus.CREATED)",
  "  addMb(@Body() body: any) { return this.svc.addMeasurement(body) }",
  "}",
])
ok('EpcController')

// ── EPC Module ─────────────────────────────────────────────────
w(path.join(EPC, 'epc.module.ts'), [
  "import { Module } from '@nestjs/common'",
  "import { TypeOrmModule } from '@nestjs/typeorm'",
  "import { BoqItem }     from './boq-item.entity'",
  "import { RaBill }      from './ra-bill.entity'",
  "import { Measurement } from './measurement.entity'",
  "import { EpcService }  from './epc.service'",
  "import { EpcController } from './epc.controller'",
  "",
  "@Module({",
  "  imports: [TypeOrmModule.forFeature([BoqItem, RaBill, Measurement])],",
  "  providers:   [EpcService],",
  "  controllers: [EpcController],",
  "  exports:     [EpcService],",
  "})",
  "export class EpcModule {}",
])
ok('EpcModule')

// ── Register in app.module.ts ──────────────────────────────────
info('Registering EpcModule...')
const appModulePath = path.join(SRC, 'app.module.ts')
let appModule = fs.readFileSync(appModulePath, 'utf8')
if (!appModule.includes("from './epc/epc.module'")) {
  appModule = appModule.replace(
    "import { HrModule }",
    "import { EpcModule } from './epc/epc.module'\nimport { HrModule }"
  )
  appModule = appModule.replace('HrModule,', 'HrModule,\n    EpcModule,')
  fs.writeFileSync(appModulePath, appModule)
  ok('EpcModule registered in app.module.ts')
} else {
  ok('EpcModule already registered')
}

console.log('\n' + G + '\x1b[1m  EPC Backend complete!\x1b[0m' + NC)
console.log('\n  Endpoints:')
console.log('  POST /api/v1/epc/boq/seed          — Load Dal Lake BOQ items')
console.log('  GET  /api/v1/epc/boq?projectId=    — List all BOQ items')
console.log('  GET  /api/v1/epc/boq/summary       — Financial summary')
console.log('  PATCH /api/v1/epc/boq/:id/measure  — Update measured qty')
console.log('  POST /api/v1/epc/ra-bills          — Create RA bill')
console.log('  GET  /api/v1/epc/ra-bills          — List RA bills')
console.log('  PATCH /api/v1/epc/ra-bills/:id/status — Update bill status')
console.log('  POST /api/v1/epc/measurements      — Record MB entry')
console.log('  GET  /api/v1/epc/payment-milestones — Payment schedule')
console.log('\n  Run frontend script next.\n')
