#!/usr/bin/env bash
# ================================================================
#  Module: HR — Backend
#  Writes complete NestJS HR module:
#    Entities: Employee, Attendance, SalaryRecord, LeaveRequest
#    Service:  HR business logic, GPS geofence, salary calculation
#    Controller: All REST endpoints
#    Module: registered in app.module.ts
#  Usage: bash scripts/modules/hr/backend.sh
# ================================================================

set -euo pipefail

G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; R='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
ok()   { echo -e "${G}  ✓${NC} $1"; }
info() { echo -e "${B}  →${NC} $1"; }
err()  { echo -e "${R}  ✗ $1${NC}"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SRC="$ROOT/backend/src"
HR="$SRC/hr"

[[ -d "$SRC" ]] || err "backend/src not found — run setup.sh first"
mkdir -p "$HR"

echo -e "\n${BOLD}Building HR Module — Backend${NC}\n"

# ================================================================
# WRITE ALL FILES VIA NODE — no heredoc issues on Windows
# ================================================================
node << 'NODEEOF'
const fs   = require('fs')
const path = require('path')

const ROOT = process.env.ROOT_DIR
const HR   = path.join(ROOT, 'backend', 'src', 'hr')
fs.mkdirSync(HR, { recursive: true })
fs.mkdirSync(path.join(HR, 'dto'), { recursive: true })

function w(file, lines) {
  fs.writeFileSync(path.join(HR, file), lines.join('\n'), 'utf8')
}
function wAbs(file, lines) {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, lines.join('\n'), 'utf8')
}

// ── ENTITY: Employee ──────────────────────────────────────────
w('employee.entity.ts', [
  "import { Entity, Column, ManyToOne, JoinColumn, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum EmploymentType { FULL_TIME = 'full_time', CONTRACT = 'contract', DAILY_WAGE = 'daily_wage' }",
  "export enum EmployeeStatus { ACTIVE = 'active', INACTIVE = 'inactive', TERMINATED = 'terminated' }",
  "",
  "@Entity('employees')",
  "export class Employee extends BaseEntity {",
  "  @Column({ name: 'emp_code', unique: true, length: 20 })",
  "  empCode: string",
  "",
  "  @Column({ name: 'first_name', length: 100 })",
  "  firstName: string",
  "",
  "  @Column({ name: 'last_name', nullable: true })",
  "  lastName: string",
  "",
  "  @Column({ nullable: true })",
  "  designation: string",
  "",
  "  @Column({ nullable: true })",
  "  department: string",
  "",
  "  @Column({ nullable: true })",
  "  phone: string",
  "",
  "  @Column({ nullable: true })",
  "  email: string",
  "",
  "  @Column({ name: 'date_of_joining', type: 'date', nullable: true })",
  "  dateOfJoining: string",
  "",
  "  @Column({ name: 'date_of_birth', type: 'date', nullable: true })",
  "  dateOfBirth: string",
  "",
  "  @Column({ name: 'aadhar_no', unique: true, nullable: true })",
  "  aadharNo: string",
  "",
  "  @Column({ name: 'pan_no', nullable: true })",
  "  panNo: string",
  "",
  "  // { accountNo, ifsc, bankName, branch }",
  "  @Column({ name: 'bank_account', type: 'jsonb', default: {} })",
  "  bankAccount: Record<string, string>",
  "",
  "  @Column({ name: 'base_salary', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  baseSalary: number",
  "",
  "  @Column({ name: 'hra', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  hra: number",
  "",
  "  @Column({ name: 'allowances', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  allowances: number",
  "",
  "  @Column({ name: 'employment_type', type: 'enum', enum: EmploymentType, default: EmploymentType.CONTRACT })",
  "  employmentType: EmploymentType",
  "",
  "  @Column({ type: 'enum', enum: EmployeeStatus, default: EmployeeStatus.ACTIVE })",
  "  status: EmployeeStatus",
  "",
  "  @Column({ name: 'project_id', nullable: true })",
  "  projectId: string",
  "",
  "  @Column({ name: 'emergency_contact', type: 'jsonb', nullable: true })",
  "  emergencyContact: Record<string, string>",
  "",
  "  @Column({ name: 'photo_url', nullable: true })",
  "  photoUrl: string",
  "",
  "  @CreateDateColumn({ name: 'created_at' })",
  "  createdAt: Date",
  "}",
])

// ── ENTITY: Attendance ────────────────────────────────────────
w('attendance.entity.ts', [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum AttendanceStatus {",
  "  PRESENT  = 'present',",
  "  ABSENT   = 'absent',",
  "  HALF_DAY = 'half_day',",
  "  LEAVE    = 'leave',",
  "  HOLIDAY  = 'holiday',",
  "}",
  "",
  "export enum AttendanceSource {",
  "  MOBILE    = 'mobile',",
  "  MANUAL    = 'manual',",
  "  BIOMETRIC = 'biometric',",
  "}",
  "",
  "@Entity('attendance')",
  "export class Attendance extends BaseEntity {",
  "  @Column({ name: 'employee_id' })",
  "  employeeId: string",
  "",
  "  @Column({ name: 'project_id', nullable: true })",
  "  projectId: string",
  "",
  "  @Column({ type: 'date' })",
  "  date: string",
  "",
  "  @Column({ name: 'check_in_time', nullable: true })",
  "  checkInTime: Date",
  "",
  "  @Column({ name: 'check_in_lat', type: 'decimal', precision: 10, scale: 8, nullable: true })",
  "  checkInLat: number",
  "",
  "  @Column({ name: 'check_in_lng', type: 'decimal', precision: 11, scale: 8, nullable: true })",
  "  checkInLng: number",
  "",
  "  @Column({ name: 'check_out_time', nullable: true })",
  "  checkOutTime: Date",
  "",
  "  @Column({ name: 'check_out_lat', type: 'decimal', precision: 10, scale: 8, nullable: true })",
  "  checkOutLat: number",
  "",
  "  @Column({ name: 'check_out_lng', type: 'decimal', precision: 11, scale: 8, nullable: true })",
  "  checkOutLng: number",
  "",
  "  @Column({ name: 'hours_worked', type: 'decimal', precision: 5, scale: 2, nullable: true })",
  "  hoursWorked: number",
  "",
  "  @Column({ name: 'geo_verified', default: false })",
  "  geoVerified: boolean",
  "",
  "  @Column({ name: 'distance_from_site', type: 'integer', nullable: true })",
  "  distanceFromSite: number",
  "",
  "  @Column({ type: 'enum', enum: AttendanceStatus, default: AttendanceStatus.PRESENT })",
  "  status: AttendanceStatus",
  "",
  "  @Column({ type: 'enum', enum: AttendanceSource, default: AttendanceSource.MANUAL })",
  "  source: AttendanceSource",
  "",
  "  @Column({ name: 'check_in_photo_url', nullable: true })",
  "  checkInPhotoUrl: string",
  "",
  "  @Column({ type: 'text', nullable: true })",
  "  remarks: string",
  "",
  "  @CreateDateColumn({ name: 'created_at' })",
  "  createdAt: Date",
  "}",
])

// ── ENTITY: SalaryRecord ──────────────────────────────────────
w('salary-record.entity.ts', [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum SalaryStatus { DRAFT = 'draft', APPROVED = 'approved', PAID = 'paid' }",
  "",
  "@Entity('salary_records')",
  "export class SalaryRecord extends BaseEntity {",
  "  @Column({ name: 'employee_id' })",
  "  employeeId: string",
  "",
  "  @Column()",
  "  month: number",
  "",
  "  @Column()",
  "  year: number",
  "",
  "  @Column({ name: 'working_days', nullable: true })",
  "  workingDays: number",
  "",
  "  @Column({ name: 'days_present', type: 'decimal', precision: 5, scale: 2, nullable: true })",
  "  daysPresent: number",
  "",
  "  @Column({ name: 'days_absent', type: 'decimal', precision: 5, scale: 2, default: 0 })",
  "  daysAbsent: number",
  "",
  "  @Column({ name: 'base_salary', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  baseSalary: number",
  "",
  "  @Column({ name: 'hra', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  hra: number",
  "",
  "  @Column({ name: 'allowances', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  allowances: number",
  "",
  "  @Column({ name: 'gross_salary', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  grossSalary: number",
  "",
  "  @Column({ name: 'pf_amount', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  pfAmount: number",
  "",
  "  @Column({ name: 'esi_amount', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  esiAmount: number",
  "",
  "  @Column({ name: 'tds_amount', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  tdsAmount: number",
  "",
  "  @Column({ name: 'other_deductions', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  otherDeductions: number",
  "",
  "  @Column({ name: 'net_salary', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  netSalary: number",
  "",
  "  @Column({ type: 'enum', enum: SalaryStatus, default: SalaryStatus.DRAFT })",
  "  status: SalaryStatus",
  "",
  "  @Column({ name: 'paid_on', type: 'date', nullable: true })",
  "  paidOn: string",
  "",
  "  @Column({ name: 'payment_mode', nullable: true })",
  "  paymentMode: string",
  "",
  "  @Column({ name: 'approved_by', nullable: true })",
  "  approvedBy: string",
  "",
  "  @CreateDateColumn({ name: 'created_at' })",
  "  createdAt: Date",
  "}",
])

// ── ENTITY: LeaveRequest ──────────────────────────────────────
w('leave-request.entity.ts', [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum LeaveType { CASUAL = 'casual', EARNED = 'earned', SICK = 'sick', UNPAID = 'unpaid' }",
  "export enum LeaveStatus { PENDING = 'pending', APPROVED = 'approved', REJECTED = 'rejected' }",
  "",
  "@Entity('leave_requests')",
  "export class LeaveRequest extends BaseEntity {",
  "  @Column({ name: 'employee_id' })",
  "  employeeId: string",
  "",
  "  @Column({ type: 'enum', enum: LeaveType })",
  "  leaveType: LeaveType",
  "",
  "  @Column({ name: 'from_date', type: 'date' })",
  "  fromDate: string",
  "",
  "  @Column({ name: 'to_date', type: 'date' })",
  "  toDate: string",
  "",
  "  @Column({ type: 'text', nullable: true })",
  "  reason: string",
  "",
  "  @Column({ type: 'enum', enum: LeaveStatus, default: LeaveStatus.PENDING })",
  "  status: LeaveStatus",
  "",
  "  @Column({ name: 'approved_by', nullable: true })",
  "  approvedBy: string",
  "",
  "  @Column({ name: 'approved_at', nullable: true })",
  "  approvedAt: Date",
  "",
  "  @CreateDateColumn({ name: 'created_at' })",
  "  createdAt: Date",
  "}",
])

// ── DTOs ──────────────────────────────────────────────────────
w('dto/create-employee.dto.ts', [
  "import { IsEnum, IsNotEmpty, IsOptional, IsString, IsNumber } from 'class-validator'",
  "import { EmploymentType } from '../employee.entity'",
  "",
  "export class CreateEmployeeDto {",
  "  @IsString() @IsNotEmpty()  empCode:        string",
  "  @IsString() @IsNotEmpty()  firstName:      string",
  "  @IsOptional() @IsString()  lastName?:      string",
  "  @IsOptional() @IsString()  designation?:   string",
  "  @IsOptional() @IsString()  department?:    string",
  "  @IsOptional() @IsString()  phone?:         string",
  "  @IsOptional() @IsString()  email?:         string",
  "  @IsOptional() @IsString()  dateOfJoining?: string",
  "  @IsOptional() @IsString()  dateOfBirth?:   string",
  "  @IsOptional() @IsString()  aadharNo?:      string",
  "  @IsOptional() @IsString()  panNo?:         string",
  "  @IsOptional()              bankAccount?:   Record<string, string>",
  "  @IsNumber()                baseSalary:     number",
  "  @IsOptional() @IsNumber()  hra?:           number",
  "  @IsOptional() @IsNumber()  allowances?:    number",
  "  @IsOptional() @IsEnum(EmploymentType) employmentType?: EmploymentType",
  "  @IsOptional() @IsString()  projectId?:     string",
  "}",
])

w('dto/mark-attendance.dto.ts', [
  "import { IsDateString, IsEnum, IsNotEmpty, IsOptional, IsString, IsNumber } from 'class-validator'",
  "import { AttendanceStatus, AttendanceSource } from '../attendance.entity'",
  "",
  "export class MarkAttendanceDto {",
  "  @IsString() @IsNotEmpty()  employeeId: string",
  "  @IsDateString()            date:       string",
  "  @IsEnum(AttendanceStatus)  status:     AttendanceStatus",
  "  @IsOptional() @IsEnum(AttendanceSource) source?: AttendanceSource",
  "  @IsOptional() @IsNumber()  checkInLat?:  number",
  "  @IsOptional() @IsNumber()  checkInLng?:  number",
  "  @IsOptional() @IsString()  checkInTime?: string",
  "  @IsOptional() @IsString()  checkOutTime?: string",
  "  @IsOptional() @IsString()  remarks?:     string",
  "  @IsOptional() @IsString()  projectId?:   string",
  "}",
])

w('dto/generate-salary.dto.ts', [
  "import { IsInt, IsNotEmpty, IsString, Max, Min } from 'class-validator'",
  "",
  "export class GenerateSalaryDto {",
  "  @IsString() @IsNotEmpty() employeeId: string",
  "  @IsInt() @Min(1) @Max(12) month:      number",
  "  @IsInt() @Min(2020)       year:       number",
  "}",
])

w('dto/apply-leave.dto.ts', [
  "import { IsDateString, IsEnum, IsNotEmpty, IsOptional, IsString } from 'class-validator'",
  "import { LeaveType } from '../leave-request.entity'",
  "",
  "export class ApplyLeaveDto {",
  "  @IsString() @IsNotEmpty()  employeeId: string",
  "  @IsEnum(LeaveType)         leaveType:  LeaveType",
  "  @IsDateString()            fromDate:   string",
  "  @IsDateString()            toDate:     string",
  "  @IsOptional() @IsString()  reason?:    string",
  "}",
])

// ── SERVICE ───────────────────────────────────────────────────
w('hr.service.ts', [
  "import { Injectable, NotFoundException, ConflictException, Logger } from '@nestjs/common'",
  "import { InjectRepository } from '@nestjs/typeorm'",
  "import { Repository, Between } from 'typeorm'",
  "import { ConfigService } from '@nestjs/config'",
  "import { Employee, EmployeeStatus } from './employee.entity'",
  "import { Attendance, AttendanceStatus, AttendanceSource } from './attendance.entity'",
  "import { SalaryRecord, SalaryStatus } from './salary-record.entity'",
  "import { LeaveRequest, LeaveStatus } from './leave-request.entity'",
  "import { CreateEmployeeDto } from './dto/create-employee.dto'",
  "import { MarkAttendanceDto } from './dto/mark-attendance.dto'",
  "import { GenerateSalaryDto } from './dto/generate-salary.dto'",
  "import { ApplyLeaveDto } from './dto/apply-leave.dto'",
  "",
  "// Haversine formula — distance between two GPS coordinates in metres",
  "function gpsDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {",
  "  const R = 6371000",
  "  const toR = (d: number) => (d * Math.PI) / 180",
  "  const dLat = toR(lat2 - lat1)",
  "  const dLng = toR(lng2 - lng1)",
  "  const a = Math.sin(dLat/2)**2 + Math.cos(toR(lat1)) * Math.cos(toR(lat2)) * Math.sin(dLng/2)**2",
  "  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))",
  "}",
  "",
  "// Working days in a month (exclude Sundays only — J&K construction standard)",
  "function workingDaysInMonth(year: number, month: number): number {",
  "  const days = new Date(year, month, 0).getDate()",
  "  let count = 0",
  "  for (let d = 1; d <= days; d++) {",
  "    if (new Date(year, month - 1, d).getDay() !== 0) count++",
  "  }",
  "  return count",
  "}",
  "",
  "@Injectable()",
  "export class HrService {",
  "  private readonly log = new Logger(HrService.name)",
  "",
  "  constructor(",
  "    @InjectRepository(Employee)      private readonly empRepo:    Repository<Employee>",
  "    @InjectRepository(Attendance)    private readonly attRepo:    Repository<Attendance>",
  "    @InjectRepository(SalaryRecord)  private readonly salRepo:    Repository<SalaryRecord>",
  "    @InjectRepository(LeaveRequest)  private readonly leaveRepo:  Repository<LeaveRequest>",
  "    private readonly config: ConfigService",
  "  ) {}",
  "",
  "  // ── Employee CRUD ─────────────────────────────────────────",
  "  async createEmployee(dto: CreateEmployeeDto): Promise<Employee> {",
  "    const exists = await this.empRepo.findOne({ where: { empCode: dto.empCode } })",
  "    if (exists) throw new ConflictException(`Employee code ${dto.empCode} already exists`)",
  "    return this.empRepo.save(this.empRepo.create(dto))",
  "  }",
  "",
  "  async listEmployees(params: {",
  "    department?: string; status?: string; search?: string; projectId?: string",
  "  }) {",
  "    const qb = this.empRepo.createQueryBuilder('e').orderBy('e.createdAt', 'DESC')",
  "    if (params.department) qb.andWhere('e.department = :dept', { dept: params.department })",
  "    if (params.status)     qb.andWhere('e.status = :status', { status: params.status })",
  "    if (params.projectId)  qb.andWhere('e.projectId = :pid', { pid: params.projectId })",
  "    if (params.search) {",
  "      qb.andWhere(",
  "        '(e.firstName ILIKE :s OR e.lastName ILIKE :s OR e.empCode ILIKE :s OR e.designation ILIKE :s)',",
  "        { s: '%' + params.search + '%' }",
  "      )",
  "    }",
  "    return qb.getMany()",
  "  }",
  "",
  "  async getEmployee(id: string): Promise<Employee> {",
  "    const emp = await this.empRepo.findOne({ where: { id } })",
  "    if (!emp) throw new NotFoundException('Employee not found')",
  "    return emp",
  "  }",
  "",
  "  async updateEmployee(id: string, data: Partial<Employee>): Promise<Employee> {",
  "    await this.empRepo.update(id, data)",
  "    return this.getEmployee(id)",
  "  }",
  "",
  "  // ── Attendance ────────────────────────────────────────────",
  "  async markAttendance(dto: MarkAttendanceDto): Promise<Attendance> {",
  "    // Check for existing record",
  "    const existing = await this.attRepo.findOne({",
  "      where: { employeeId: dto.employeeId, date: dto.date },",
  "    })",
  "",
  "    // GPS verification (if coordinates provided)",
  "    let geoVerified = false",
  "    let distanceFromSite: number | undefined",
  "    const SITE_LAT = 34.0920  // Nishat, Srinagar",
  "    const SITE_LNG = 74.8740",
  "    const GEO_RADIUS = parseInt(this.config.get('GEO_FENCE_RADIUS') ?? '500')",
  "",
  "    if (dto.checkInLat && dto.checkInLng) {",
  "      distanceFromSite = Math.round(gpsDistance(dto.checkInLat, dto.checkInLng, SITE_LAT, SITE_LNG))",
  "      geoVerified = distanceFromSite <= GEO_RADIUS",
  "    }",
  "",
  "    const record = this.attRepo.create({",
  "      employeeId:      dto.employeeId,",
  "      date:            dto.date,",
  "      status:          dto.status,",
  "      source:          dto.source ?? AttendanceSource.MANUAL,",
  "      projectId:       dto.projectId,",
  "      checkInLat:      dto.checkInLat,",
  "      checkInLng:      dto.checkInLng,",
  "      checkInTime:     dto.checkInTime ? new Date(dto.checkInTime) : new Date(),",
  "      checkOutTime:    dto.checkOutTime ? new Date(dto.checkOutTime) : undefined,",
  "      geoVerified,",
  "      distanceFromSite,",
  "      remarks:         dto.remarks,",
  "    })",
  "",
  "    if (existing) {",
  "      await this.attRepo.update(existing.id, record)",
  "      return this.attRepo.findOne({ where: { id: existing.id } }) as Promise<Attendance>",
  "    }",
  "    return this.attRepo.save(record)",
  "  }",
  "",
  "  async bulkMarkAttendance(records: MarkAttendanceDto[]): Promise<{ saved: number; errors: string[] }> {",
  "    let saved = 0",
  "    const errors: string[] = []",
  "    for (const r of records) {",
  "      try { await this.markAttendance(r); saved++ }",
  "      catch (e: any) { errors.push(`${r.employeeId}: ${e.message}`) }",
  "    }",
  "    return { saved, errors }",
  "  }",
  "",
  "  async getAttendance(params: {",
  "    employeeId?: string; date?: string; month?: number",
  "    year?: number; projectId?: string",
  "  }) {",
  "    const qb = this.attRepo",
  "      .createQueryBuilder('a')",
  "      .orderBy('a.date', 'DESC')",
  "",
  "    if (params.employeeId) qb.andWhere('a.employeeId = :eid', { eid: params.employeeId })",
  "    if (params.date)       qb.andWhere('a.date = :date', { date: params.date })",
  "    if (params.projectId)  qb.andWhere('a.projectId = :pid', { pid: params.projectId })",
  "    if (params.month && params.year) {",
  "      qb.andWhere('EXTRACT(MONTH FROM a.date) = :m AND EXTRACT(YEAR FROM a.date) = :y',",
  "        { m: params.month, y: params.year })",
  "    }",
  "    return qb.getMany()",
  "  }",
  "",
  "  async getTodayAttendance(projectId?: string) {",
  "    const today = new Date().toISOString().split('T')[0]",
  "    const records = await this.getAttendance({ date: today, projectId })",
  "",
  "    // Get all active employees to find who is absent",
  "    const allEmp = await this.empRepo.find({",
  "      where: { status: EmployeeStatus.ACTIVE, ...(projectId ? { projectId } : {}) },",
  "    })",
  "",
  "    const markedIds = records.map(r => r.employeeId)",
  "    const absent = allEmp.filter(e => !markedIds.includes(e.id))",
  "",
  "    return {",
  "      date:    today,",
  "      present: records.filter(r => r.status === AttendanceStatus.PRESENT).length,",
  "      absent:  absent.length,",
  "      halfDay: records.filter(r => r.status === AttendanceStatus.HALF_DAY).length,",
  "      onLeave: records.filter(r => r.status === AttendanceStatus.LEAVE).length,",
  "      total:   allEmp.length,",
  "      records,",
  "      absentEmployees: absent.map(e => ({",
  "        id: e.id, empCode: e.empCode,",
  "        name: `${e.firstName} ${e.lastName ?? ''}`.trim(),",
  "        designation: e.designation,",
  "      })),",
  "    }",
  "  }",
  "",
  "  async getMonthlyReport(employeeId: string, year: number, month: number) {",
  "    const records = await this.getAttendance({ employeeId, month, year })",
  "",
  "    const summary = {",
  "      present:      records.filter(r => r.status === AttendanceStatus.PRESENT).length,",
  "      absent:       records.filter(r => r.status === AttendanceStatus.ABSENT).length,",
  "      halfDay:      records.filter(r => r.status === AttendanceStatus.HALF_DAY).length,",
  "      onLeave:      records.filter(r => r.status === AttendanceStatus.LEAVE).length,",
  "      geoUnverified:records.filter(r => !r.geoVerified && r.status === AttendanceStatus.PRESENT).length,",
  "      workingDays:  workingDaysInMonth(year, month),",
  "    }",
  "    return { records, summary }",
  "  }",
  "",
  "  // ── Salary generation ─────────────────────────────────────",
  "  async generateSalary(dto: GenerateSalaryDto, generatedBy: string): Promise<SalaryRecord> {",
  "    // Check not already generated",
  "    const existing = await this.salRepo.findOne({",
  "      where: { employeeId: dto.employeeId, month: dto.month, year: dto.year },",
  "    })",
  "    if (existing) throw new ConflictException('Salary already generated for this month')",
  "",
  "    const emp = await this.getEmployee(dto.employeeId)",
  "",
  "    // Attendance for this month",
  "    const { records, summary } = await this.getMonthlyReport(dto.employeeId, dto.year, dto.month)",
  "",
  "    const workingDays = summary.workingDays",
  "    const daysPresent = summary.present + (summary.halfDay * 0.5)",
  "",
  "    // Per-day rate based on working days",
  "    const perDay    = Number(emp.baseSalary) / workingDays",
  "    const earnedBasic = perDay * daysPresent",
  "    const earnedHra   = (Number(emp.hra) / workingDays) * daysPresent",
  "    const allowances  = Number(emp.allowances)",
  "    const gross       = earnedBasic + earnedHra + allowances",
  "",
  "    // PF — 12% of basic, capped at PF wage ceiling ₹15,000",
  "    const PF_RATE      = parseFloat(this.config.get('PF_RATE') ?? '0.12')",
  "    const PF_CEILING   = 15000",
  "    const pfBase       = Math.min(Number(emp.baseSalary), PF_CEILING)",
  "    const pfAmount     = pfBase * PF_RATE",
  "",
  "    // ESI — 0.75% if gross <= ₹21,000",
  "    const ESI_THRESHOLD = parseFloat(this.config.get('ESI_THRESHOLD') ?? '21000')",
  "    const ESI_RATE      = parseFloat(this.config.get('ESI_RATE') ?? '0.0075')",
  "    const esiAmount     = gross <= ESI_THRESHOLD ? gross * ESI_RATE : 0",
  "",
  "    const netSalary = gross - pfAmount - esiAmount",
  "",
  "    return this.salRepo.save(this.salRepo.create({",
  "      employeeId:   dto.employeeId,",
  "      month:        dto.month,",
  "      year:         dto.year,",
  "      workingDays,",
  "      daysPresent,",
  "      daysAbsent:   workingDays - daysPresent,",
  "      baseSalary:   parseFloat(earnedBasic.toFixed(2)),",
  "      hra:          parseFloat(earnedHra.toFixed(2)),",
  "      allowances,",
  "      grossSalary:  parseFloat(gross.toFixed(2)),",
  "      pfAmount:     parseFloat(pfAmount.toFixed(2)),",
  "      esiAmount:    parseFloat(esiAmount.toFixed(2)),",
  "      tdsAmount:    0,",
  "      otherDeductions: 0,",
  "      netSalary:    parseFloat(netSalary.toFixed(2)),",
  "      status:       SalaryStatus.DRAFT,",
  "      approvedBy:   generatedBy,",
  "    }))",
  "  }",
  "",
  "  async listSalary(params: { employeeId?: string; month?: number; year?: number; status?: string }) {",
  "    const qb = this.salRepo.createQueryBuilder('s').orderBy('s.year', 'DESC').addOrderBy('s.month', 'DESC')",
  "    if (params.employeeId) qb.andWhere('s.employeeId = :eid', { eid: params.employeeId })",
  "    if (params.month)      qb.andWhere('s.month = :m', { m: params.month })",
  "    if (params.year)       qb.andWhere('s.year = :y', { y: params.year })",
  "    if (params.status)     qb.andWhere('s.status = :s', { s: params.status })",
  "    return qb.getMany()",
  "  }",
  "",
  "  async approveSalary(id: string): Promise<SalaryRecord> {",
  "    await this.salRepo.update(id, { status: SalaryStatus.APPROVED })",
  "    const rec = await this.salRepo.findOne({ where: { id } })",
  "    if (!rec) throw new NotFoundException('Salary record not found')",
  "    return rec",
  "  }",
  "",
  "  async markPaid(id: string, paymentMode: string): Promise<SalaryRecord> {",
  "    const today = new Date().toISOString().split('T')[0]",
  "    await this.salRepo.update(id, {",
  "      status: SalaryStatus.PAID,",
  "      paidOn: today,",
  "      paymentMode,",
  "    })",
  "    const rec = await this.salRepo.findOne({ where: { id } })",
  "    if (!rec) throw new NotFoundException('Salary record not found')",
  "    return rec",
  "  }",
  "",
  "  // ── Leave management ──────────────────────────────────────",
  "  async applyLeave(dto: ApplyLeaveDto): Promise<LeaveRequest> {",
  "    return this.leaveRepo.save(this.leaveRepo.create(dto))",
  "  }",
  "",
  "  async listLeaves(params: { employeeId?: string; status?: string }) {",
  "    const qb = this.leaveRepo.createQueryBuilder('l').orderBy('l.createdAt', 'DESC')",
  "    if (params.employeeId) qb.andWhere('l.employeeId = :eid', { eid: params.employeeId })",
  "    if (params.status)     qb.andWhere('l.status = :s', { s: params.status })",
  "    return qb.getMany()",
  "  }",
  "",
  "  async processLeave(id: string, status: LeaveStatus, approvedBy: string): Promise<LeaveRequest> {",
  "    await this.leaveRepo.update(id, {",
  "      status,",
  "      approvedBy,",
  "      approvedAt: new Date(),",
  "    })",
  "    const leave = await this.leaveRepo.findOne({ where: { id } })",
  "    if (!leave) throw new NotFoundException('Leave request not found')",
  "    return leave",
  "  }",
  "",
  "  // ── Dashboard stats ───────────────────────────────────────",
  "  async dashboard(projectId?: string) {",
  "    const empFilter = { status: EmployeeStatus.ACTIVE, ...(projectId ? { projectId } : {}) }",
  "    const totalEmp  = await this.empRepo.count({ where: empFilter })",
  "    const today     = await this.getTodayAttendance(projectId)",
  "    const pendingLeaves = await this.leaveRepo.count({ where: { status: LeaveStatus.PENDING } })",
  "    const pendingSalaries = await this.salRepo.count({ where: { status: SalaryStatus.DRAFT } })",
  "",
  "    return {",
  "      totalEmployees: totalEmp,",
  "      presentToday:   today.present,",
  "      absentToday:    today.absent,",
  "      onLeaveToday:   today.onLeave,",
  "      attendancePct:  totalEmp > 0 ? Math.round((today.present / totalEmp) * 100) : 0,",
  "      pendingLeaves,",
  "      pendingSalaries,",
  "    }",
  "  }",
  "}",
])

// ── CONTROLLER ────────────────────────────────────────────────
w('hr.controller.ts', [
  "import {",
  "  Controller, Get, Post, Patch, Param, Body, Query,",
  "  UseGuards, Request, HttpCode, HttpStatus,",
  "} from '@nestjs/common'",
  "import { HrService } from './hr.service'",
  "import { CreateEmployeeDto } from './dto/create-employee.dto'",
  "import { MarkAttendanceDto } from './dto/mark-attendance.dto'",
  "import { GenerateSalaryDto } from './dto/generate-salary.dto'",
  "import { ApplyLeaveDto } from './dto/apply-leave.dto'",
  "import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard'",
  "import { LeaveStatus } from './leave-request.entity'",
  "",
  "@Controller('hr')",
  "@UseGuards(JwtAuthGuard)",
  "export class HrController {",
  "  constructor(private readonly svc: HrService) {}",
  "",
  "  // ── Dashboard ─────────────────────────────────────────────",
  "  @Get('dashboard')",
  "  dashboard(@Query('projectId') projectId?: string) {",
  "    return this.svc.dashboard(projectId)",
  "  }",
  "",
  "  // ── Employees ─────────────────────────────────────────────",
  "  @Get('employees')",
  "  listEmployees(@Query() q: any) {",
  "    return this.svc.listEmployees({",
  "      department: q.department,",
  "      status:     q.status,",
  "      search:     q.search,",
  "      projectId:  q.projectId,",
  "    })",
  "  }",
  "",
  "  @Post('employees')",
  "  @HttpCode(HttpStatus.CREATED)",
  "  createEmployee(@Body() dto: CreateEmployeeDto) {",
  "    return this.svc.createEmployee(dto)",
  "  }",
  "",
  "  @Get('employees/:id')",
  "  getEmployee(@Param('id') id: string) {",
  "    return this.svc.getEmployee(id)",
  "  }",
  "",
  "  @Patch('employees/:id')",
  "  updateEmployee(@Param('id') id: string, @Body() body: any) {",
  "    return this.svc.updateEmployee(id, body)",
  "  }",
  "",
  "  // ── Attendance ────────────────────────────────────────────",
  "  @Get('attendance')",
  "  getAttendance(@Query() q: any) {",
  "    return this.svc.getAttendance({",
  "      employeeId: q.employeeId,",
  "      date:       q.date,",
  "      month:      q.month  ? parseInt(q.month)  : undefined,",
  "      year:       q.year   ? parseInt(q.year)   : undefined,",
  "      projectId:  q.projectId,",
  "    })",
  "  }",
  "",
  "  @Get('attendance/today')",
  "  todayAttendance(@Query('projectId') projectId?: string) {",
  "    return this.svc.getTodayAttendance(projectId)",
  "  }",
  "",
  "  @Post('attendance')",
  "  @HttpCode(HttpStatus.CREATED)",
  "  markAttendance(@Body() dto: MarkAttendanceDto) {",
  "    return this.svc.markAttendance(dto)",
  "  }",
  "",
  "  @Post('attendance/bulk')",
  "  @HttpCode(HttpStatus.CREATED)",
  "  bulkAttendance(@Body() body: { records: MarkAttendanceDto[] }) {",
  "    return this.svc.bulkMarkAttendance(body.records)",
  "  }",
  "",
  "  @Get('attendance/report/:empId/:year/:month')",
  "  monthlyReport(",
  "    @Param('empId') empId: string,",
  "    @Param('year')  year:  string,",
  "    @Param('month') month: string,",
  "  ) {",
  "    return this.svc.getMonthlyReport(empId, parseInt(year), parseInt(month))",
  "  }",
  "",
  "  // ── Salary ────────────────────────────────────────────────",
  "  @Get('salary')",
  "  listSalary(@Query() q: any) {",
  "    return this.svc.listSalary({",
  "      employeeId: q.employeeId,",
  "      month:      q.month  ? parseInt(q.month)  : undefined,",
  "      year:       q.year   ? parseInt(q.year)   : undefined,",
  "      status:     q.status,",
  "    })",
  "  }",
  "",
  "  @Post('salary/generate')",
  "  @HttpCode(HttpStatus.CREATED)",
  "  generateSalary(@Body() dto: GenerateSalaryDto, @Request() req: any) {",
  "    return this.svc.generateSalary(dto, req.user.id)",
  "  }",
  "",
  "  @Patch('salary/:id/approve')",
  "  approveSalary(@Param('id') id: string) {",
  "    return this.svc.approveSalary(id)",
  "  }",
  "",
  "  @Patch('salary/:id/paid')",
  "  markPaid(@Param('id') id: string, @Body('paymentMode') paymentMode: string) {",
  "    return this.svc.markPaid(id, paymentMode ?? 'bank_transfer')",
  "  }",
  "",
  "  // ── Leave ─────────────────────────────────────────────────",
  "  @Get('leave')",
  "  listLeaves(@Query() q: any) {",
  "    return this.svc.listLeaves({ employeeId: q.employeeId, status: q.status })",
  "  }",
  "",
  "  @Post('leave')",
  "  @HttpCode(HttpStatus.CREATED)",
  "  applyLeave(@Body() dto: ApplyLeaveDto) {",
  "    return this.svc.applyLeave(dto)",
  "  }",
  "",
  "  @Patch('leave/:id/approve')",
  "  approveLeave(@Param('id') id: string, @Request() req: any) {",
  "    return this.svc.processLeave(id, LeaveStatus.APPROVED, req.user.id)",
  "  }",
  "",
  "  @Patch('leave/:id/reject')",
  "  rejectLeave(@Param('id') id: string, @Request() req: any) {",
  "    return this.svc.processLeave(id, LeaveStatus.REJECTED, req.user.id)",
  "  }",
  "}",
])

// ── MODULE ────────────────────────────────────────────────────
w('hr.module.ts', [
  "import { Module } from '@nestjs/common'",
  "import { TypeOrmModule } from '@nestjs/typeorm'",
  "import { Employee }     from './employee.entity'",
  "import { Attendance }   from './attendance.entity'",
  "import { SalaryRecord } from './salary-record.entity'",
  "import { LeaveRequest } from './leave-request.entity'",
  "import { HrService }    from './hr.service'",
  "import { HrController } from './hr.controller'",
  "",
  "@Module({",
  "  imports: [TypeOrmModule.forFeature([Employee, Attendance, SalaryRecord, LeaveRequest])],",
  "  providers:   [HrService],",
  "  controllers: [HrController],",
  "  exports:     [HrService],",
  "})",
  "export class HrModule {}",
])

// ── Register in app.module.ts ──────────────────────────────────
const appModulePath = path.join(ROOT, 'backend', 'src', 'app.module.ts')
let appModule = fs.readFileSync(appModulePath, 'utf8')

if (!appModule.includes("from './hr/hr.module'")) {
  // Add import statement
  appModule = appModule.replace(
    "import { LiaisonModule }",
    "import { HrModule } from './hr/hr.module'\nimport { LiaisonModule }"
  )
  // Add to imports array
  appModule = appModule.replace(
    'LiaisonModule,',
    'LiaisonModule,\n    HrModule,'
  )
  fs.writeFileSync(appModulePath, appModule)
  console.log('  ✓ HrModule registered in app.module.ts')
} else {
  console.log('  ✓ HrModule already registered')
}

// ── Add .env variables ────────────────────────────────────────
const envPath = path.join(ROOT, 'backend', '.env')
let env = fs.readFileSync(envPath, 'utf8')
if (!env.includes('PF_RATE')) {
  env += [
    '',
    '# ── Salary configuration ─────────────────────────────',
    'PF_RATE=0.12',
    'ESI_THRESHOLD=21000',
    'ESI_RATE=0.0075',
    'GEO_FENCE_RADIUS=500',
  ].join('\n')
  fs.writeFileSync(envPath, env)
  console.log('  ✓ Salary config added to .env')
}

console.log('  ✓ All HR backend files written')
NODEEOF

ok "HR entities written (Employee, Attendance, SalaryRecord, LeaveRequest)"
ok "HR service written (GPS geofence, salary calc PF/ESI, attendance)"
ok "HR controller written (employees, attendance, salary, leave)"
ok "HR module written and registered"

echo ""
echo -e "${G}${BOLD}HR Backend complete!${NC}"
echo ""
echo -e "  ${BOLD}Endpoints:${NC}"
echo -e "  GET    /api/v1/hr/dashboard"
echo -e "  GET    /api/v1/hr/employees"
echo -e "  POST   /api/v1/hr/employees"
echo -e "  GET    /api/v1/hr/attendance"
echo -e "  GET    /api/v1/hr/attendance/today"
echo -e "  POST   /api/v1/hr/attendance"
echo -e "  POST   /api/v1/hr/attendance/bulk"
echo -e "  GET    /api/v1/hr/attendance/report/:empId/:year/:month"
echo -e "  POST   /api/v1/hr/salary/generate"
echo -e "  PATCH  /api/v1/hr/salary/:id/approve"
echo -e "  PATCH  /api/v1/hr/salary/:id/paid"
echo -e "  POST   /api/v1/hr/leave"
echo -e "  PATCH  /api/v1/hr/leave/:id/approve"
echo ""
echo -e "  ${Y}Backend auto-reloads — check terminal for errors${NC}"
echo ""
