// ================================================================
//  Module: HR — Frontend
//  Run: node scripts/modules/hr/frontend.js
//  Writes:
//    - EmployeesPage (list, add, search, detail)
//    - AttendancePage (today's view, bulk mark, calendar)
//    - SalaryPage (generate, approve, pay)
//    - HR API client
// ================================================================
const fs   = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..', '..', '..')
const SRC  = path.join(ROOT, 'frontend', 'src')

const G = '\x1b[32m', B = '\x1b[34m', NC = '\x1b[0m'
const ok   = s => console.log(G + '  ✓' + NC + ' ' + s)
const info = s => console.log(B + '  →' + NC + ' ' + s)
function w(p, lines) {
  fs.mkdirSync(path.dirname(p), { recursive: true })
  fs.writeFileSync(p, lines.join('\n'), 'utf8')
}

console.log('\n\x1b[1mBuilding HR Module — Frontend\x1b[0m\n')

// ── HR API ────────────────────────────────────────────────────
info('Writing HR API...')
w(path.join(SRC, 'api/hr.api.ts'), [
  "import api from './client'",
  "",
  "export const hrApi = {",
  "  dashboard:        (projectId?: string) =>",
  "    api.get('/api/v1/hr/dashboard', { params: { projectId } }),",
  "",
  "  // Employees",
  "  employees:        (p?: any) => api.get('/api/v1/hr/employees', { params: p }),",
  "  employee:         (id: string) => api.get('/api/v1/hr/employees/' + id),",
  "  createEmployee:   (d: any) => api.post('/api/v1/hr/employees', d),",
  "  updateEmployee:   (id: string, d: any) => api.patch('/api/v1/hr/employees/' + id, d),",
  "",
  "  // Attendance",
  "  attendance:       (p?: any) => api.get('/api/v1/hr/attendance', { params: p }),",
  "  todayAttendance:  (projectId?: string) =>",
  "    api.get('/api/v1/hr/attendance/today', { params: { projectId } }),",
  "  markAttendance:   (d: any) => api.post('/api/v1/hr/attendance', d),",
  "  bulkAttendance:   (records: any[]) => api.post('/api/v1/hr/attendance/bulk', { records }),",
  "  monthlyReport:    (empId: string, year: number, month: number) =>",
  "    api.get('/api/v1/hr/attendance/report/' + empId + '/' + year + '/' + month),",
  "",
  "  // Salary",
  "  salaryList:       (p?: any) => api.get('/api/v1/hr/salary', { params: p }),",
  "  generateSalary:   (d: any) => api.post('/api/v1/hr/salary/generate', d),",
  "  approveSalary:    (id: string) => api.patch('/api/v1/hr/salary/' + id + '/approve', {}),",
  "  markPaid:         (id: string, paymentMode: string) =>",
  "    api.patch('/api/v1/hr/salary/' + id + '/paid', { paymentMode }),",
  "",
  "  // Leave",
  "  leaves:           (p?: any) => api.get('/api/v1/hr/leave', { params: p }),",
  "  applyLeave:       (d: any) => api.post('/api/v1/hr/leave', d),",
  "  approveLeave:     (id: string) => api.patch('/api/v1/hr/leave/' + id + '/approve', {}),",
  "  rejectLeave:      (id: string) => api.patch('/api/v1/hr/leave/' + id + '/reject', {}),",
  "}",
])
ok('hr.api.ts')

// ── Shared tokens ──────────────────────────────────────────────
const C = {
  blue:   '#2563eb', blueBg:   '#eff6ff', blueBorder:   '#bfdbfe',
  green:  '#059669', greenBg:  '#ecfdf5', greenBorder:  '#a7f3d0',
  amber:  '#d97706', amberBg:  '#fffbeb', amberBorder:  '#fde68a',
  red:    '#dc2626', redBg:    '#fef2f2', redBorder:    '#fecaca',
  purple: '#7c3aed', purpleBg: '#f5f3ff', purpleBorder: '#ddd6fe',
  text1:  '#0f172a', text2:    '#475569', text3:    '#94a3b8',
  border: '#e2e8f0', bg:       '#f0f2f5', card:     '#ffffff',
  navy:   '#1a2540',
}

// ── EMPLOYEES PAGE ────────────────────────────────────────────
info('Writing EmployeesPage...')
w(path.join(SRC, 'pages/hr/EmployeesPage.tsx'), [
  "import { useState } from 'react'",
  "import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'",
  "import { Users, Plus, MagnifyingGlass, UserCircle, Phone, EnvelopeSimple, Buildings } from '@phosphor-icons/react'",
  "import { hrApi } from '@/api/hr.api'",
  "import { useAuthStore } from '@/store/auth.store'",
  "import { Badge } from '@/components/ui/Badge'",
  "import { Modal } from '@/components/ui/Modal'",
  "import { Button } from '@/components/ui/Button'",
  "import { Input } from '@/components/ui/Input'",
  "import { Select } from '@/components/ui/Select'",
  "import { Spinner } from '@/components/ui/Spinner'",
  "",
  "const DEPTS = ['Civil','Electrical','Mechanical','HR','Admin','Security','Labour'].map(d => ({ value: d, label: d }))",
  "const EMP_TYPES = [",
  "  { value: 'full_time', label: 'Full Time' },",
  "  { value: 'contract',  label: 'Contract'  },",
  "  { value: 'daily_wage',label: 'Daily Wage'},",
  "]",
  "const BLANK = {",
  "  empCode: '', firstName: '', lastName: '', designation: '', department: 'Civil',",
  "  phone: '', email: '', dateOfJoining: '', baseSalary: '', hra: '0', allowances: '0',",
  "  employmentType: 'contract', aadharNo: '', panNo: '',",
  "  bankAccount: { accountNo: '', ifsc: '', bankName: '', branch: '' },",
  "}",
  "",
  "export default function EmployeesPage() {",
  "  const { activeProjectId } = useAuthStore()",
  "  const qc = useQueryClient()",
  "  const [search, setSearch]   = useState('')",
  "  const [dept, setDept]       = useState('')",
  "  const [showNew, setShowNew] = useState(false)",
  "  const [selected, setSelected] = useState<any>(null)",
  "  const [form, setForm]       = useState<any>(BLANK)",
  "  const [tab, setTab]         = useState<'info'|'bank'|'leave'>('info')",
  "",
  "  const { data: employees, isLoading } = useQuery({",
  "    queryKey: ['employees', activeProjectId, dept],",
  "    queryFn:  () => hrApi.employees({ projectId: activeProjectId, department: dept || undefined }).then(r => r.data),",
  "  })",
  "",
  "  const { data: hrDash } = useQuery({",
  "    queryKey: ['hr-dash', activeProjectId],",
  "    queryFn:  () => hrApi.dashboard(activeProjectId ?? undefined).then(r => r.data),",
  "    enabled:  !!activeProjectId,",
  "  })",
  "",
  "  const createM = useMutation({",
  "    mutationFn: (d: any) => hrApi.createEmployee({ ...d, projectId: activeProjectId, baseSalary: parseFloat(d.baseSalary), hra: parseFloat(d.hra || '0'), allowances: parseFloat(d.allowances || '0') }),",
  "    onSuccess: () => { qc.invalidateQueries({ queryKey: ['employees'] }); qc.invalidateQueries({ queryKey: ['hr-dash'] }); setShowNew(false); setForm(BLANK) },",
  "  })",
  "",
  "  const list = (employees ?? []).filter((e: any) =>",
  "    !search || [e.firstName, e.lastName, e.empCode, e.designation].join(' ').toLowerCase().includes(search.toLowerCase())",
  "  )",
  "",
  "  const setF = (key: string, val: any) => setForm((f: any) => ({ ...f, [key]: val }))",
  "  const setBank = (key: string, val: string) => setForm((f: any) => ({ ...f, bankAccount: { ...f.bankAccount, [key]: val } }))",
  "",
  "  // ── Colours per status ──────────────────────────────────",
  "  const STATUS_COLORS: Record<string, string> = {",
  "    active: '" + C.green + "', inactive: '" + C.amber + "', terminated: '" + C.red + "'",
  "  }",
  "",
  "  return (",
  "    <div className='fade-in' style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>",
  "",
  "      {/* Header */}",
  "      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>",
  "        <div>",
  "          <h1 style={{ fontSize: 24, fontWeight: 800, color: '" + C.text1 + "', margin: 0, letterSpacing: '-0.02em' }}>Employees</h1>",
  "          <p style={{ fontSize: 14, color: '" + C.text3 + "', marginTop: 4 }}>Manage team members and their records</p>",
  "        </div>",
  "        <Button variant='primary' size='md' icon={<Plus size={15} />} onClick={() => setShowNew(true)}>",
  "          Add Employee",
  "        </Button>",
  "      </div>",
  "",
  "      {/* Stats */}",
  "      {hrDash && (",
  "        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14 }}>",
  "          {[",
  "            { label: 'Total Employees', value: hrDash.totalEmployees, color: '" + C.blue + "' },",
  "            { label: 'Present Today',   value: hrDash.presentToday,   color: '" + C.green + "' },",
  "            { label: 'Absent Today',    value: hrDash.absentToday,    color: hrDash.absentToday > 0 ? '" + C.red + "' : '" + C.green + "' },",
  "            { label: 'Pending Leaves',  value: hrDash.pendingLeaves,  color: '" + C.amber + "' },",
  "          ].map(s => (",
  "            <div key={s.label} style={{ background: '" + C.card + "', border: '1.5px solid " + C.border + "', borderRadius: 12, padding: '16px 20px', boxShadow: '0 1px 4px rgba(0,0,0,0.05)' }}>",
  "              <div style={{ fontSize: 28, fontWeight: 800, color: s.color, fontVariantNumeric: 'tabular-nums' }}>{s.value}</div>",
  "              <div style={{ fontSize: 12, color: '" + C.text3 + "', marginTop: 4, fontWeight: 600 }}>{s.label}</div>",
  "            </div>",
  "          ))}",
  "        </div>",
  "      )}",
  "",
  "      {/* Filters */}",
  "      <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>",
  "        <div style={{ position: 'relative', flex: 1, maxWidth: 360 }}>",
  "          <MagnifyingGlass style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', color: '" + C.text3 + "' }} size={15} />",
  "          <input value={search} onChange={e => setSearch(e.target.value)} placeholder='Search name, code, designation...'",
  "            style={{ width: '100%', paddingLeft: 36, paddingRight: 14, paddingTop: 10, paddingBottom: 10, background: '#fff', border: '1.5px solid " + C.border + "', borderRadius: 8, fontSize: 13, color: '" + C.text1 + "', outline: 'none', fontFamily: 'inherit' }} />",
  "        </div>",
  "        <select value={dept} onChange={e => setDept(e.target.value)}",
  "          style={{ padding: '10px 14px', background: '#fff', border: '1.5px solid " + C.border + "', borderRadius: 8, fontSize: 13, color: '" + C.text1 + "', outline: 'none', cursor: 'pointer', fontFamily: 'inherit' }}>",
  "          <option value=''>All Departments</option>",
  "          {DEPTS.map(d => <option key={d.value} value={d.value}>{d.label}</option>)}",
  "        </select>",
  "        <span style={{ fontSize: 12, color: '" + C.text3 + "' }}>{list.length} employees</span>",
  "      </div>",
  "",
  "      {/* List + Detail */}",
  "      <div style={{ display: 'flex', gap: 16, alignItems: 'flex-start' }}>",
  "",
  "        {/* Employee list */}",
  "        <div style={{ flex: 1, background: '" + C.card + "', borderRadius: 16, border: '1.5px solid " + C.border + "', overflow: 'hidden', boxShadow: '0 1px 6px rgba(0,0,0,0.05)' }}>",
  "          {isLoading ? <div style={{ display: 'flex', justifyContent: 'center', padding: 48 }}><Spinner /></div>",
  "          : list.length === 0 ? (",
  "            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '56px 24px', gap: 10 }}>",
  "              <Users size={32} color='" + C.border + "' />",
  "              <p style={{ fontSize: 14, fontWeight: 600, color: '" + C.text3 + "', margin: 0 }}>No employees found</p>",
  "              <Button variant='secondary' size='sm' icon={<Plus size={13} />} onClick={() => setShowNew(true)}>Add first employee</Button>",
  "            </div>",
  "          ) : (",
  "            <>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '80px 1fr 120px 120px 90px', padding: '11px 20px', background: '#f8f9fc', borderBottom: '1.5px solid " + C.border + "' }}>",
  "                {['Code', 'Name & Role', 'Department', 'Employment', 'Status'].map(h => (",
  "                  <div key={h} style={{ fontSize: 10, fontWeight: 700, color: '" + C.text3 + "', textTransform: 'uppercase', letterSpacing: '0.07em' }}>{h}</div>",
  "                ))}",
  "              </div>",
  "              {list.map((emp: any, i: number) => (",
  "                <div key={emp.id} onClick={() => setSelected(emp)}",
  "                  style={{ display: 'grid', gridTemplateColumns: '80px 1fr 120px 120px 90px', padding: '14px 20px', cursor: 'pointer', alignItems: 'center', borderBottom: i < list.length - 1 ? '1px solid #f1f5f9' : 'none', background: selected?.id === emp.id ? '#f0f6ff' : 'transparent', borderLeft: selected?.id === emp.id ? '3px solid " + C.blue + "' : '3px solid transparent', transition: 'all 0.1s' }}",
  "                  onMouseEnter={e => { if (selected?.id !== emp.id) e.currentTarget.style.background = '#f8faff' }}",
  "                  onMouseLeave={e => { if (selected?.id !== emp.id) e.currentTarget.style.background = 'transparent' }}>",
  "                  <div style={{ fontSize: 11, fontWeight: 700, color: '" + C.blue + "', fontFamily: 'monospace' }}>{emp.empCode}</div>",
  "                  <div>",
  "                    <p style={{ fontSize: 13, fontWeight: 600, color: '" + C.text1 + "', margin: 0 }}>{emp.firstName} {emp.lastName ?? ''}</p>",
  "                    <p style={{ fontSize: 11, color: '" + C.text3 + "', margin: '2px 0 0' }}>{emp.designation ?? '—'}</p>",
  "                  </div>",
  "                  <div style={{ fontSize: 12, color: '" + C.text2 + "' }}>{emp.department ?? '—'}</div>",
  "                  <div style={{ fontSize: 11, color: '" + C.text2 + "', textTransform: 'capitalize' }}>{emp.employmentType?.replace(/_/g, ' ') ?? '—'}</div>",
  "                  <div style={{ display: 'inline-flex', padding: '2px 10px', borderRadius: 999, fontSize: 10, fontWeight: 700, background: (STATUS_COLORS[emp.status] ?? '" + C.text3 + "') + '18', color: STATUS_COLORS[emp.status] ?? '" + C.text3 + "', border: '1.5px solid ' + (STATUS_COLORS[emp.status] ?? '" + C.text3 + "') + '30' }}>{emp.status}</div>",
  "                </div>",
  "              ))}",
  "            </>",
  "          )}",
  "        </div>",
  "",
  "        {/* Detail panel */}",
  "        {selected && (",
  "          <div style={{ width: 280, flexShrink: 0, background: '" + C.card + "', border: '1.5px solid " + C.border + "', borderRadius: 16, overflow: 'hidden', boxShadow: '0 1px 6px rgba(0,0,0,0.05)' }}>",
  "            <div style={{ background: '" + C.navy + "', padding: '20px 18px', textAlign: 'center' }}>",
  "              <div style={{ width: 56, height: 56, borderRadius: '50%', background: 'rgba(59,130,246,0.2)', border: '2px solid rgba(59,130,246,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 10px', fontSize: 20, fontWeight: 700, color: '#93c5fd' }}>",
  "                {selected.firstName[0]}{selected.lastName?.[0] ?? ''}",
  "              </div>",
  "              <h3 style={{ fontSize: 15, fontWeight: 700, color: '#fff', margin: '0 0 3px' }}>{selected.firstName} {selected.lastName ?? ''}</h3>",
  "              <p style={{ fontSize: 12, color: 'rgba(255,255,255,0.5)', margin: 0 }}>{selected.designation ?? '—'}</p>",
  "              <p style={{ fontSize: 11, color: 'rgba(255,255,255,0.3)', margin: '4px 0 0', fontFamily: 'monospace' }}>{selected.empCode}</p>",
  "            </div>",
  "",
  "            <div style={{ padding: '16px 18px', borderBottom: '1.5px solid #f1f5f9' }}>",
  "              {[",
  "                ['Department', selected.department],",
  "                ['Employment', selected.employmentType?.replace(/_/g,' ')],",
  "                ['Joined', selected.dateOfJoining],",
  "                ['Phone', selected.phone],",
  "                ['Email', selected.email],",
  "              ].filter(([,v]) => v).map(([l, v]) => (",
  "                <div key={l as string} style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8, fontSize: 12 }}>",
  "                  <span style={{ color: '" + C.text3 + "' }}>{l}</span>",
  "                  <span style={{ color: '" + C.text1 + "', fontWeight: 600, maxWidth: 150, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', textAlign: 'right' }}>{v as string}</span>",
  "                </div>",
  "              ))}",
  "            </div>",
  "",
  "            <div style={{ padding: '14px 18px', borderBottom: '1.5px solid #f1f5f9' }}>",
  "              <p style={{ fontSize: 10, fontWeight: 700, color: '" + C.text3 + "', textTransform: 'uppercase', letterSpacing: '0.08em', margin: '0 0 10px' }}>Salary Structure</p>",
  "              {[",
  "                ['Basic', '₹' + Number(selected.baseSalary).toLocaleString('en-IN')],",
  "                ['HRA',   '₹' + Number(selected.hra || 0).toLocaleString('en-IN')],",
  "                ['Allowances', '₹' + Number(selected.allowances || 0).toLocaleString('en-IN')],",
  "                ['Gross CTC',  '₹' + (Number(selected.baseSalary) + Number(selected.hra||0) + Number(selected.allowances||0)).toLocaleString('en-IN')],",
  "              ].map(([l, v]) => (",
  "                <div key={l as string} style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6, fontSize: 12 }}>",
  "                  <span style={{ color: '" + C.text3 + "' }}>{l}</span>",
  "                  <span style={{ color: l === 'Gross CTC' ? '" + C.green + "' : '" + C.text1 + "', fontWeight: l === 'Gross CTC' ? 700 : 500 }}>{v}</span>",
  "                </div>",
  "              ))}",
  "            </div>",
  "",
  "            <div style={{ padding: '14px 18px', display: 'flex', justifyContent: 'flex-end' }}>",
  "              <button onClick={() => setSelected(null)} style={{ fontSize: 12, color: '" + C.text3 + "', background: 'none', border: 'none', cursor: 'pointer' }}>Close</button>",
  "            </div>",
  "          </div>",
  "        )}",
  "      </div>",
  "",
  "      {/* Add Employee Modal */}",
  "      <Modal open={showNew} onClose={() => setShowNew(false)} title='Add New Employee' width={640}",
  "        footer={<>",
  "          <Button variant='ghost' onClick={() => setShowNew(false)}>Cancel</Button>",
  "          <Button variant='primary' loading={createM.isPending} onClick={() => createM.mutate(form)} disabled={!form.empCode || !form.firstName || !form.baseSalary}>",
  "            Add Employee",
  "          </Button>",
  "        </>}>",
  "        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>",
  "          {/* Tabs */}",
  "          <div style={{ display: 'flex', borderBottom: '1.5px solid " + C.border + "', marginBottom: 4 }}>",
  "            {(['info', 'bank', 'leave'] as const).map(t => (",
  "              <button key={t} onClick={() => setTab(t)} style={{ padding: '8px 16px', fontSize: 13, fontWeight: 600, border: 'none', background: 'none', cursor: 'pointer', borderBottom: tab === t ? '2px solid " + C.blue + "' : '2px solid transparent', color: tab === t ? '" + C.blue + "' : '" + C.text3 + "', textTransform: 'capitalize' }}>",
  "                {t === 'info' ? 'Personal Info' : t === 'bank' ? 'Bank Details' : 'Employment'}",
  "              </button>",
  "            ))}",
  "          </div>",
  "",
  "          {tab === 'info' && (",
  "            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>",
  "                <Input label='Employee Code *' value={form.empCode} onChange={e => setF('empCode', e.target.value)} placeholder='EMP001' />",
  "                <Select label='Department *' value={form.department} onChange={e => setF('department', e.target.value)} options={DEPTS} />",
  "              </div>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>",
  "                <Input label='First Name *' value={form.firstName} onChange={e => setF('firstName', e.target.value)} placeholder='Ravi' />",
  "                <Input label='Last Name' value={form.lastName} onChange={e => setF('lastName', e.target.value)} placeholder='Kumar' />",
  "              </div>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>",
  "                <Input label='Designation' value={form.designation} onChange={e => setF('designation', e.target.value)} placeholder='Site Engineer' />",
  "                <Select label='Employment Type' value={form.employmentType} onChange={e => setF('employmentType', e.target.value)} options={EMP_TYPES} />",
  "              </div>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>",
  "                <Input label='Phone' value={form.phone} onChange={e => setF('phone', e.target.value)} placeholder='9876543210' />",
  "                <Input label='Email' type='email' value={form.email} onChange={e => setF('email', e.target.value)} placeholder='ravi@example.com' />",
  "              </div>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>",
  "                <Input label='Date of Joining' type='date' value={form.dateOfJoining} onChange={e => setF('dateOfJoining', e.target.value)} />",
  "                <Input label='Date of Birth' type='date' value={form.dateOfBirth} onChange={e => setF('dateOfBirth', e.target.value)} />",
  "              </div>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>",
  "                <Input label='Aadhar No' value={form.aadharNo} onChange={e => setF('aadharNo', e.target.value)} placeholder='123456789012' />",
  "                <Input label='PAN No' value={form.panNo} onChange={e => setF('panNo', e.target.value)} placeholder='ABCDE1234F' />",
  "              </div>",
  "            </div>",
  "          )}",
  "",
  "          {tab === 'bank' && (",
  "            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>",
  "                <Input label='Account Number' value={form.bankAccount.accountNo} onChange={e => setBank('accountNo', e.target.value)} placeholder='123456789' />",
  "                <Input label='IFSC Code' value={form.bankAccount.ifsc} onChange={e => setBank('ifsc', e.target.value)} placeholder='SBIN0001234' />",
  "              </div>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>",
  "                <Input label='Bank Name' value={form.bankAccount.bankName} onChange={e => setBank('bankName', e.target.value)} placeholder='State Bank of India' />",
  "                <Input label='Branch' value={form.bankAccount.branch} onChange={e => setBank('branch', e.target.value)} placeholder='Srinagar Main' />",
  "              </div>",
  "            </div>",
  "          )}",
  "",
  "          {tab === 'leave' && (",
  "            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>",
  "              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 }}>",
  "                <Input label='Basic Salary (₹) *' type='number' value={form.baseSalary} onChange={e => setF('baseSalary', e.target.value)} placeholder='25000' />",
  "                <Input label='HRA (₹)' type='number' value={form.hra} onChange={e => setF('hra', e.target.value)} placeholder='5000' />",
  "                <Input label='Allowances (₹)' type='number' value={form.allowances} onChange={e => setF('allowances', e.target.value)} placeholder='2000' />",
  "              </div>",
  "              {form.baseSalary && (",
  "                <div style={{ padding: '12px 14px', background: '" + C.blueBg + "', border: '1.5px solid " + C.blueBorder + "', borderRadius: 8, fontSize: 12 }}>",
  "                  <strong style={{ color: '" + C.blue + "' }}>Salary Preview</strong>",
  "                  <div style={{ marginTop: 8, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6, color: '" + C.text2 + "' }}>",
  "                    <span>Gross CTC: ₹{(parseFloat(form.baseSalary||'0') + parseFloat(form.hra||'0') + parseFloat(form.allowances||'0')).toLocaleString('en-IN')}</span>",
  "                    <span>PF (12%): ₹{(Math.min(parseFloat(form.baseSalary||'0'), 15000) * 0.12).toFixed(0)}</span>",
  "                    <span>ESI: {parseFloat(form.baseSalary||'0') <= 21000 ? '✓ Applicable' : '✗ Not applicable'}</span>",
  "                    <span>Net ≈ ₹{(parseFloat(form.baseSalary||'0') + parseFloat(form.hra||'0') + parseFloat(form.allowances||'0') - Math.min(parseFloat(form.baseSalary||'0'),15000)*0.12).toLocaleString('en-IN')}</span>",
  "                  </div>",
  "                </div>",
  "              )}",
  "            </div>",
  "          )}",
  "        </div>",
  "      </Modal>",
  "    </div>",
  "  )",
  "}",
])
ok('EmployeesPage')

// ── ATTENDANCE PAGE ───────────────────────────────────────────
info('Writing AttendancePage...')
w(path.join(SRC, 'pages/hr/AttendancePage.tsx'), [
  "import { useState } from 'react'",
  "import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'",
  "import { MapPin, CheckCircle, XCircle, Clock, Users, Warning, ArrowClockwise } from '@phosphor-icons/react'",
  "import { hrApi } from '@/api/hr.api'",
  "import { useAuthStore } from '@/store/auth.store'",
  "import { Badge } from '@/components/ui/Badge'",
  "import { Modal } from '@/components/ui/Modal'",
  "import { Button } from '@/components/ui/Button'",
  "import { Select } from '@/components/ui/Select'",
  "import { Spinner } from '@/components/ui/Spinner'",
  "",
  "const STATUS_OPTS = [",
  "  { value: 'present',  label: '✓ Present'  },",
  "  { value: 'absent',   label: '✗ Absent'   },",
  "  { value: 'half_day', label: '½ Half Day' },",
  "  { value: 'leave',    label: '⏸ On Leave' },",
  "]",
  "",
  "const STATUS_STYLE: Record<string, { bg: string; color: string; border: string }> = {",
  "  present:  { bg: '#ecfdf5', color: '#059669', border: '#a7f3d0' },",
  "  absent:   { bg: '#fef2f2', color: '#dc2626', border: '#fecaca' },",
  "  half_day: { bg: '#fffbeb', color: '#d97706', border: '#fde68a' },",
  "  leave:    { bg: '#f5f3ff', color: '#7c3aed', border: '#ddd6fe' },",
  "  holiday:  { bg: '#f0f9ff', color: '#0284c7', border: '#bae6fd' },",
  "}",
  "",
  "export default function AttendancePage() {",
  "  const { activeProjectId } = useAuthStore()",
  "  const qc = useQueryClient()",
  "  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0])",
  "  const [markModal, setMarkModal]   = useState(false)",
  "  const [bulkStatus, setBulkStatus] = useState('present')",
  "  const [overrides, setOverrides]   = useState<Record<string, string>>({}) // empId -> status",
  "",
  "  const { data: today, isLoading: todayLoading } = useQuery({",
  "    queryKey: ['attendance-today', activeProjectId],",
  "    queryFn:  () => hrApi.todayAttendance(activeProjectId ?? undefined).then(r => r.data),",
  "    refetchInterval: 60_000,",
  "  })",
  "",
  "  const { data: employees } = useQuery({",
  "    queryKey: ['employees', activeProjectId],",
  "    queryFn:  () => hrApi.employees({ projectId: activeProjectId, status: 'active' }).then(r => r.data),",
  "  })",
  "",
  "  const { data: dateRecords, isLoading: dateLoading } = useQuery({",
  "    queryKey: ['attendance-date', selectedDate, activeProjectId],",
  "    queryFn:  () => hrApi.attendance({ date: selectedDate, projectId: activeProjectId }).then(r => r.data),",
  "  })",
  "",
  "  const bulkM = useMutation({",
  "    mutationFn: (records: any[]) => hrApi.bulkAttendance(records),",
  "    onSuccess: () => {",
  "      qc.invalidateQueries({ queryKey: ['attendance-today'] })",
  "      qc.invalidateQueries({ queryKey: ['attendance-date'] })",
  "      setMarkModal(false)",
  "      setOverrides({})",
  "    },",
  "  })",
  "",
  "  function submitBulk() {",
  "    const all = employees ?? []",
  "    const records = all.map((e: any) => ({",
  "      employeeId: e.id,",
  "      date:       selectedDate,",
  "      status:     overrides[e.id] ?? bulkStatus,",
  "      source:     'manual',",
  "      projectId:  activeProjectId,",
  "    }))",
  "    bulkM.mutate(records)",
  "  }",
  "",
  "  const todayStr = new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long' })",
  "",
  "  return (",
  "    <div className='fade-in' style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>",
  "",
  "      {/* Header */}",
  "      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>",
  "        <div>",
  "          <h1 style={{ fontSize: 24, fontWeight: 800, color: '#0f172a', margin: 0, letterSpacing: '-0.02em' }}>Attendance</h1>",
  "          <p style={{ fontSize: 14, color: '#94a3b8', marginTop: 4 }}>{todayStr}</p>",
  "        </div>",
  "        <div style={{ display: 'flex', gap: 10 }}>",
  "          <input type='date' value={selectedDate} onChange={e => setSelectedDate(e.target.value)}",
  "            style={{ padding: '9px 13px', background: '#fff', border: '1.5px solid #e2e8f0', borderRadius: 8, fontSize: 13, color: '#0f172a', outline: 'none', fontFamily: 'inherit' }} />",
  "          <Button variant='primary' size='md' icon={<MapPin size={15} />} onClick={() => setMarkModal(true)}>",
  "            Mark Attendance",
  "          </Button>",
  "        </div>",
  "      </div>",
  "",
  "      {/* Today summary */}",
  "      {today && (",
  "        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 14 }}>",
  "          {[",
  "            { label: 'Total',    value: today.total,    color: '#2563eb' },",
  "            { label: 'Present',  value: today.present,  color: '#059669' },",
  "            { label: 'Absent',   value: today.absent,   color: today.absent > 0 ? '#dc2626' : '#059669' },",
  "            { label: 'Half Day', value: today.halfDay,  color: '#d97706' },",
  "            { label: 'On Leave', value: today.onLeave,  color: '#7c3aed' },",
  "          ].map(s => (",
  "            <div key={s.label} style={{ background: '#fff', border: '1.5px solid #e2e8f0', borderRadius: 12, padding: '14px 18px', boxShadow: '0 1px 4px rgba(0,0,0,0.05)' }}>",
  "              <div style={{ fontSize: 26, fontWeight: 800, color: s.color, fontVariantNumeric: 'tabular-nums' }}>{s.value}</div>",
  "              <div style={{ fontSize: 12, fontWeight: 600, color: '#94a3b8', marginTop: 3 }}>{s.label}</div>",
  "            </div>",
  "          ))}",
  "        </div>",
  "      )}",
  "",
  "      {/* Attendance table for selected date */}",
  "      <div style={{ background: '#fff', borderRadius: 16, border: '1.5px solid #e2e8f0', overflow: 'hidden', boxShadow: '0 1px 6px rgba(0,0,0,0.05)' }}>",
  "        <div style={{ padding: '16px 22px', borderBottom: '1.5px solid #e2e8f0', background: '#f8f9fc', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>",
  "          <h2 style={{ fontSize: 14, fontWeight: 700, color: '#0f172a', margin: 0 }}>",
  "            Records for {selectedDate}",
  "          </h2>",
  "          <span style={{ fontSize: 12, color: '#94a3b8' }}>{(dateRecords ?? []).length} records</span>",
  "        </div>",
  "        {dateLoading ? <div style={{ display: 'flex', justifyContent: 'center', padding: 40 }}><Spinner /></div>",
  "        : (dateRecords ?? []).length === 0 ? (",
  "          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '48px 24px', gap: 10 }}>",
  "            <MapPin size={32} color='#e2e8f0' />",
  "            <p style={{ fontSize: 14, color: '#94a3b8', margin: 0, fontWeight: 600 }}>No attendance marked for this date</p>",
  "            <Button variant='secondary' size='sm' onClick={() => setMarkModal(true)} icon={<MapPin size={13} />}>Mark attendance</Button>",
  "          </div>",
  "        ) : (",
  "          <table style={{ width: '100%', borderCollapse: 'collapse' }}>",
  "            <thead>",
  "              <tr style={{ background: '#f8f9fc', borderBottom: '1.5px solid #e2e8f0' }}>",
  "                {['Employee', 'Status', 'Check In', 'Check Out', 'Hours', 'GPS Verified', 'Source'].map(h => (",
  "                  <th key={h} style={{ padding: '10px 18px', textAlign: 'left', fontSize: 10, fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.07em', whiteSpace: 'nowrap' }}>{h}</th>",
  "                ))}",
  "              </tr>",
  "            </thead>",
  "            <tbody>",
  "              {(dateRecords ?? []).map((r: any, i: number) => {",
  "                const emp = (employees ?? []).find((e: any) => e.id === r.employeeId)",
  "                const ss = STATUS_STYLE[r.status] ?? STATUS_STYLE.absent",
  "                return (",
  "                  <tr key={r.id} style={{ borderBottom: i < (dateRecords ?? []).length - 1 ? '1px solid #f1f5f9' : 'none' }}>",
  "                    <td style={{ padding: '12px 18px' }}>",
  "                      <p style={{ fontSize: 13, fontWeight: 600, color: '#0f172a', margin: 0 }}>{emp ? `${emp.firstName} ${emp.lastName ?? ''}` : r.employeeId}</p>",
  "                      <p style={{ fontSize: 11, color: '#94a3b8', margin: '2px 0 0', fontFamily: 'monospace' }}>{emp?.empCode ?? ''}</p>",
  "                    </td>",
  "                    <td style={{ padding: '12px 18px' }}>",
  "                      <span style={{ display: 'inline-flex', padding: '3px 10px', borderRadius: 999, fontSize: 11, fontWeight: 700, background: ss.bg, color: ss.color, border: '1.5px solid ' + ss.border }}>",
  "                        {r.status.replace(/_/g,' ')}",
  "                      </span>",
  "                    </td>",
  "                    <td style={{ padding: '12px 18px', fontSize: 12, color: '#475569' }}>{r.checkInTime ? new Date(r.checkInTime).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : '—'}</td>",
  "                    <td style={{ padding: '12px 18px', fontSize: 12, color: '#475569' }}>{r.checkOutTime ? new Date(r.checkOutTime).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : '—'}</td>",
  "                    <td style={{ padding: '12px 18px', fontSize: 12, color: '#475569' }}>{r.hoursWorked ? Number(r.hoursWorked).toFixed(1) + 'h' : '—'}</td>",
  "                    <td style={{ padding: '12px 18px' }}>",
  "                      {r.geoVerified",
  "                        ? <span style={{ color: '#059669', fontSize: 12, fontWeight: 600 }}>✓ Yes</span>",
  "                        : <span style={{ color: '#94a3b8', fontSize: 12 }}>—</span>}",
  "                    </td>",
  "                    <td style={{ padding: '12px 18px', fontSize: 11, color: '#94a3b8', textTransform: 'capitalize' }}>{r.source}</td>",
  "                  </tr>",
  "                )",
  "              })}",
  "            </tbody>",
  "          </table>",
  "        )}",
  "      </div>",
  "",
  "      {/* Absent employees today */}",
  "      {today?.absentEmployees?.length > 0 && (",
  "        <div style={{ background: '#fff', borderRadius: 16, border: '1.5px solid #fecaca', overflow: 'hidden' }}>",
  "          <div style={{ padding: '14px 22px', background: '#fef2f2', borderBottom: '1.5px solid #fecaca', display: 'flex', alignItems: 'center', gap: 8 }}>",
  "            <Warning size={15} color='#dc2626' />",
  "            <h2 style={{ fontSize: 13, fontWeight: 700, color: '#b91c1c', margin: 0 }}>Not Marked Today ({today.absentEmployees.length})</h2>",
  "          </div>",
  "          <div style={{ padding: '12px 22px', display: 'flex', gap: 10, flexWrap: 'wrap' }}>",
  "            {today.absentEmployees.map((e: any) => (",
  "              <div key={e.id} style={{ padding: '6px 12px', background: '#f8fafc', border: '1.5px solid #e2e8f0', borderRadius: 8, fontSize: 12 }}>",
  "                <span style={{ fontWeight: 700, color: '#0f172a' }}>{e.name}</span>",
  "                <span style={{ color: '#94a3b8', marginLeft: 6 }}>{e.designation}</span>",
  "              </div>",
  "            ))}",
  "          </div>",
  "        </div>",
  "      )}",
  "",
  "      {/* Mark Attendance Modal */}",
  "      <Modal open={markModal} onClose={() => setMarkModal(false)} title='Mark Attendance' width={680}",
  "        footer={<>",
  "          <Button variant='ghost' onClick={() => setMarkModal(false)}>Cancel</Button>",
  "          <Button variant='primary' loading={bulkM.isPending} onClick={submitBulk} icon={<CheckCircle size={14} />}>",
  "            Save Attendance",
  "          </Button>",
  "        </>}>",
  "        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>",
  "          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>",
  "            <input type='date' value={selectedDate} onChange={e => setSelectedDate(e.target.value)}",
  "              style={{ padding: '9px 13px', background: '#fff', border: '1.5px solid #e2e8f0', borderRadius: 8, fontSize: 13, color: '#0f172a', outline: 'none', fontFamily: 'inherit' }} />",
  "            <Select label='' value={bulkStatus} onChange={e => setBulkStatus(e.target.value)} options={STATUS_OPTS} />",
  "            <button onClick={() => setOverrides({})} style={{ fontSize: 12, color: '#94a3b8', background: 'none', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4 }}>",
  "              <ArrowClockwise size={13} /> Reset all",
  "            </button>",
  "          </div>",
  "          <p style={{ fontSize: 12, color: '#94a3b8', margin: 0 }}>Default status is <strong>{bulkStatus}</strong>. Click individual rows to override.</p>",
  "          <div style={{ maxHeight: 360, overflowY: 'auto', border: '1.5px solid #e2e8f0', borderRadius: 10, overflow: 'hidden' }}>",
  "            {(employees ?? []).map((emp: any, i: number) => {",
  "              const st = overrides[emp.id] ?? bulkStatus",
  "              const ss = STATUS_STYLE[st] ?? STATUS_STYLE.present",
  "              return (",
  "                <div key={emp.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 16px', borderBottom: i < (employees ?? []).length - 1 ? '1px solid #f1f5f9' : 'none' }}>",
  "                  <div>",
  "                    <p style={{ fontSize: 13, fontWeight: 600, color: '#0f172a', margin: 0 }}>{emp.firstName} {emp.lastName ?? ''}</p>",
  "                    <p style={{ fontSize: 11, color: '#94a3b8', margin: '2px 0 0' }}>{emp.empCode} · {emp.designation}</p>",
  "                  </div>",
  "                  <div style={{ display: 'flex', gap: 6 }}>",
  "                    {STATUS_OPTS.map(opt => (",
  "                      <button key={opt.value} onClick={() => setOverrides(o => ({ ...o, [emp.id]: opt.value }))}",
  "                        style={{ padding: '5px 12px', borderRadius: 8, fontSize: 11, fontWeight: 600, cursor: 'pointer', border: '1.5px solid', transition: 'all 0.1s',",
  "                          background: st === opt.value ? (STATUS_STYLE[opt.value]?.bg ?? '#f8f9fc') : '#fff',",
  "                          color: st === opt.value ? (STATUS_STYLE[opt.value]?.color ?? '#374151') : '#94a3b8',",
  "                          borderColor: st === opt.value ? (STATUS_STYLE[opt.value]?.border ?? '#e2e8f0') : '#e2e8f0',",
  "                        }}>",
  "                        {opt.value === 'present' ? 'P' : opt.value === 'absent' ? 'A' : opt.value === 'half_day' ? '½' : 'L'}",
  "                      </button>",
  "                    ))}",
  "                  </div>",
  "                </div>",
  "              )",
  "            })}",
  "          </div>",
  "        </div>",
  "      </Modal>",
  "    </div>",
  "  )",
  "}",
])
ok('AttendancePage')

// ── SALARY PAGE ───────────────────────────────────────────────
info('Writing SalaryPage...')
w(path.join(SRC, 'pages/hr/SalaryPage.tsx'), [
  "import { useState } from 'react'",
  "import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'",
  "import { Receipt, Plus, CheckCircle, CurrencyInr } from '@phosphor-icons/react'",
  "import { hrApi } from '@/api/hr.api'",
  "import { useAuthStore } from '@/store/auth.store'",
  "import { Modal } from '@/components/ui/Modal'",
  "import { Button } from '@/components/ui/Button'",
  "import { Select } from '@/components/ui/Select'",
  "import { Spinner } from '@/components/ui/Spinner'",
  "",
  "const MONTHS = [",
  "  {value:'1',label:'January'},{value:'2',label:'February'},{value:'3',label:'March'},",
  "  {value:'4',label:'April'},{value:'5',label:'May'},{value:'6',label:'June'},",
  "  {value:'7',label:'July'},{value:'8',label:'August'},{value:'9',label:'September'},",
  "  {value:'10',label:'October'},{value:'11',label:'November'},{value:'12',label:'December'},",
  "]",
  "",
  "const STATUS_STYLE: Record<string, { bg: string; color: string; border: string }> = {",
  "  draft:    { bg: '#f8fafc', color: '#64748b', border: '#e2e8f0' },",
  "  approved: { bg: '#eff6ff', color: '#1d4ed8', border: '#bfdbfe' },",
  "  paid:     { bg: '#ecfdf5', color: '#047857', border: '#a7f3d0' },",
  "}",
  "",
  "export default function SalaryPage() {",
  "  const { activeProjectId } = useAuthStore()",
  "  const qc = useQueryClient()",
  "  const now = new Date()",
  "  const [month, setMonth] = useState(String(now.getMonth() + 1))",
  "  const [year,  setYear]  = useState(String(now.getFullYear()))",
  "  const [genModal, setGenModal] = useState(false)",
  "  const [genEmpId, setGenEmpId] = useState('')",
  "",
  "  const { data: salaries, isLoading } = useQuery({",
  "    queryKey: ['salary', month, year],",
  "    queryFn:  () => hrApi.salaryList({ month: parseInt(month), year: parseInt(year) }).then(r => r.data),",
  "  })",
  "",
  "  const { data: employees } = useQuery({",
  "    queryKey: ['employees', activeProjectId],",
  "    queryFn:  () => hrApi.employees({ projectId: activeProjectId, status: 'active' }).then(r => r.data),",
  "  })",
  "",
  "  const genM = useMutation({",
  "    mutationFn: () => hrApi.generateSalary({ employeeId: genEmpId, month: parseInt(month), year: parseInt(year) }),",
  "    onSuccess: () => { qc.invalidateQueries({ queryKey: ['salary'] }); setGenModal(false) },",
  "  })",
  "",
  "  const approveM = useMutation({",
  "    mutationFn: (id: string) => hrApi.approveSalary(id),",
  "    onSuccess: () => qc.invalidateQueries({ queryKey: ['salary'] }),",
  "  })",
  "",
  "  const payM = useMutation({",
  "    mutationFn: (id: string) => hrApi.markPaid(id, 'bank_transfer'),",
  "    onSuccess: () => qc.invalidateQueries({ queryKey: ['salary'] }),",
  "  })",
  "",
  "  const empOptions = (employees ?? []).map((e: any) => ({",
  "    value: e.id,",
  "    label: `${e.empCode} — ${e.firstName} ${e.lastName ?? ''}`,",
  "  }))",
  "",
  "  const monthName = MONTHS.find(m => m.value === month)?.label",
  "  const totalNet  = (salaries ?? []).reduce((s: number, r: any) => s + Number(r.netSalary), 0)",
  "",
  "  return (",
  "    <div className='fade-in' style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>",
  "",
  "      {/* Header */}",
  "      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>",
  "        <div>",
  "          <h1 style={{ fontSize: 24, fontWeight: 800, color: '#0f172a', margin: 0, letterSpacing: '-0.02em' }}>Salary</h1>",
  "          <p style={{ fontSize: 14, color: '#94a3b8', marginTop: 4 }}>Generate, approve and pay monthly salaries</p>",
  "        </div>",
  "        <Button variant='primary' size='md' icon={<Plus size={15} />} onClick={() => setGenModal(true)}>",
  "          Generate Salary",
  "        </Button>",
  "      </div>",
  "",
  "      {/* Month/Year filter */}",
  "      <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>",
  "        <Select label='' value={month} onChange={e => setMonth(e.target.value)} options={MONTHS} />",
  "        <Select label='' value={year} onChange={e => setYear(e.target.value)} options={",
  "          [2024,2025,2026,2027].map(y => ({ value: String(y), label: String(y) }))",
  "        } />",
  "        {totalNet > 0 && (",
  "          <div style={{ marginLeft: 'auto', padding: '8px 16px', background: '#ecfdf5', border: '1.5px solid #a7f3d0', borderRadius: 10, fontSize: 13, fontWeight: 700, color: '#047857', display: 'flex', alignItems: 'center', gap: 6 }}>",
  "            <CurrencyInr size={14} />",
  "            Total Payable: ₹{totalNet.toLocaleString('en-IN', { minimumFractionDigits: 2 })}",
  "          </div>",
  "        )}",
  "      </div>",
  "",
  "      {/* Salary table */}",
  "      <div style={{ background: '#fff', borderRadius: 16, border: '1.5px solid #e2e8f0', overflow: 'hidden', boxShadow: '0 1px 6px rgba(0,0,0,0.05)' }}>",
  "        <div style={{ padding: '16px 22px', borderBottom: '1.5px solid #e2e8f0', background: '#f8f9fc' }}>",
  "          <h2 style={{ fontSize: 14, fontWeight: 700, color: '#0f172a', margin: 0 }}>",
  "            {monthName} {year} — {(salaries ?? []).length} records",
  "          </h2>",
  "        </div>",
  "        {isLoading ? <div style={{ display: 'flex', justifyContent: 'center', padding: 40 }}><Spinner /></div>",
  "        : (salaries ?? []).length === 0 ? (",
  "          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '56px 24px', gap: 10 }}>",
  "            <Receipt size={32} color='#e2e8f0' />",
  "            <p style={{ fontSize: 14, color: '#94a3b8', margin: 0, fontWeight: 600 }}>No salary records for {monthName} {year}</p>",
  "            <Button variant='secondary' size='sm' icon={<Plus size={13} />} onClick={() => setGenModal(true)}>Generate salary</Button>",
  "          </div>",
  "        ) : (",
  "          <table style={{ width: '100%', borderCollapse: 'collapse' }}>",
  "            <thead>",
  "              <tr style={{ background: '#f8f9fc', borderBottom: '1.5px solid #e2e8f0' }}>",
  "                {['Employee','Days','Gross (₹)','PF','ESI','Net Pay (₹)','Status','Actions'].map(h => (",
  "                  <th key={h} style={{ padding: '10px 16px', textAlign: 'left', fontSize: 10, fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.07em', whiteSpace: 'nowrap' }}>{h}</th>",
  "                ))}",
  "              </tr>",
  "            </thead>",
  "            <tbody>",
  "              {(salaries ?? []).map((s: any, i: number) => {",
  "                const emp = (employees ?? []).find((e: any) => e.id === s.employeeId)",
  "                const ss = STATUS_STYLE[s.status] ?? STATUS_STYLE.draft",
  "                return (",
  "                  <tr key={s.id} style={{ borderBottom: i < (salaries ?? []).length - 1 ? '1px solid #f1f5f9' : 'none' }}>",
  "                    <td style={{ padding: '13px 16px' }}>",
  "                      <p style={{ fontSize: 13, fontWeight: 600, color: '#0f172a', margin: 0 }}>{emp ? `${emp.firstName} ${emp.lastName ?? ''}` : s.employeeId}</p>",
  "                      <p style={{ fontSize: 11, color: '#94a3b8', margin: '2px 0 0', fontFamily: 'monospace' }}>{emp?.empCode ?? ''}</p>",
  "                    </td>",
  "                    <td style={{ padding: '13px 16px', fontSize: 12, color: '#475569' }}>{Number(s.daysPresent).toFixed(1)} / {s.workingDays}</td>",
  "                    <td style={{ padding: '13px 16px', fontSize: 13, fontWeight: 600, color: '#0f172a' }}>₹{Number(s.grossSalary).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td>",
  "                    <td style={{ padding: '13px 16px', fontSize: 12, color: '#dc2626' }}>₹{Number(s.pfAmount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td>",
  "                    <td style={{ padding: '13px 16px', fontSize: 12, color: '#dc2626' }}>₹{Number(s.esiAmount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td>",
  "                    <td style={{ padding: '13px 16px', fontSize: 14, fontWeight: 800, color: '#059669' }}>₹{Number(s.netSalary).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td>",
  "                    <td style={{ padding: '13px 16px' }}>",
  "                      <span style={{ display: 'inline-flex', padding: '3px 10px', borderRadius: 999, fontSize: 11, fontWeight: 700, background: ss.bg, color: ss.color, border: '1.5px solid ' + ss.border }}>",
  "                        {s.status}",
  "                      </span>",
  "                    </td>",
  "                    <td style={{ padding: '13px 16px' }}>",
  "                      <div style={{ display: 'flex', gap: 6 }}>",
  "                        {s.status === 'draft' && (",
  "                          <Button variant='secondary' size='xs' icon={<CheckCircle size={11} />}",
  "                            onClick={() => approveM.mutate(s.id)} loading={approveM.isPending}>",
  "                            Approve",
  "                          </Button>",
  "                        )}",
  "                        {s.status === 'approved' && (",
  "                          <Button variant='success' size='xs' icon={<CurrencyInr size={11} />}",
  "                            onClick={() => payM.mutate(s.id)} loading={payM.isPending}>",
  "                            Mark Paid",
  "                          </Button>",
  "                        )}",
  "                        {s.status === 'paid' && (",
  "                          <span style={{ fontSize: 12, color: '#059669', fontWeight: 600 }}>✓ Paid</span>",
  "                        )}",
  "                      </div>",
  "                    </td>",
  "                  </tr>",
  "                )",
  "              })}",
  "            </tbody>",
  "          </table>",
  "        )}",
  "      </div>",
  "",
  "      {/* Generate Salary Modal */}",
  "      <Modal open={genModal} onClose={() => setGenModal(false)} title='Generate Salary' width={460}",
  "        footer={<>",
  "          <Button variant='ghost' onClick={() => setGenModal(false)}>Cancel</Button>",
  "          <Button variant='primary' loading={genM.isPending} onClick={() => genM.mutate()} disabled={!genEmpId}>",
  "            Generate",
  "          </Button>",
  "        </>}>",
  "        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>",
  "          <div style={{ padding: '12px 14px', background: '#eff6ff', border: '1.5px solid #bfdbfe', borderRadius: 8, fontSize: 12, color: '#1d4ed8' }}>",
  "            Salary will be calculated based on attendance records for {monthName} {year}.",
  "            PF (12% of basic) and ESI (0.75% if applicable) will be auto-deducted.",
  "          </div>",
  "          <Select label='Select Employee' value={genEmpId} onChange={e => setGenEmpId(e.target.value)}",
  "            options={empOptions} placeholder='Choose employee...' />",
  "          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>",
  "            <Select label='Month' value={month} onChange={e => setMonth(e.target.value)} options={MONTHS} />",
  "            <Select label='Year' value={year} onChange={e => setYear(e.target.value)}",
  "              options={[2024,2025,2026,2027].map(y => ({ value: String(y), label: String(y) }))} />",
  "          </div>",
  "        </div>",
  "      </Modal>",
  "    </div>",
  "  )",
  "}",
])
ok('SalaryPage')

console.log('\n' + G + '\x1b[1m  HR Frontend complete!\x1b[0m' + NC)
console.log('\n  Pages:')
console.log('  /hr/employees  → Add employees, view records, salary structure')
console.log('  /hr/attendance → Mark daily attendance, bulk mark, absent list')
console.log('  /hr/salary     → Generate payroll, approve, mark paid')
console.log('\n  Run frontend: cd frontend && npm run dev\n')
