// ================================================================
//  Module: HR — Backend (Node.js version)
//  Run: node scripts/modules/hr/backend.js
// ================================================================
const fs   = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..', '..', '..')
const SRC  = path.join(ROOT, 'backend', 'src')
const HR   = path.join(SRC, 'hr')

const G = '\x1b[32m', B = '\x1b[34m', NC = '\x1b[0m'
const ok   = s => console.log(G + '  ✓' + NC + ' ' + s)
const info = s => console.log(B + '  →' + NC + ' ' + s)

if (!fs.existsSync(SRC)) {
  console.error('\x1b[31m  ✗ backend/src not found — run setup.sh first\x1b[0m')
  process.exit(1)
}

fs.mkdirSync(HR, { recursive: true })
fs.mkdirSync(path.join(HR, 'dto'), { recursive: true })

console.log('\n\x1b[1mBuilding HR Module — Backend\x1b[0m\n')

function w(file, lines) {
  fs.writeFileSync(path.join(HR, file), lines.join('\n'), 'utf8')
}

// ── ENTITY: Employee ──────────────────────────────────────────
info('Writing entities...')
w('employee.entity.ts', [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum EmploymentType { FULL_TIME = 'full_time', CONTRACT = 'contract', DAILY_WAGE = 'daily_wage' }",
  "export enum EmployeeStatus { ACTIVE = 'active', INACTIVE = 'inactive', TERMINATED = 'terminated' }",
  "",
  "@Entity('employees')",
  "export class Employee extends BaseEntity {",
  "  @Column({ name: 'emp_code', unique: true, length: 20 })",
  "  empCode: string",
  "  @Column({ name: 'first_name', length: 100 })",
  "  firstName: string",
  "  @Column({ name: 'last_name', nullable: true })",
  "  lastName: string",
  "  @Column({ nullable: true })",
  "  designation: string",
  "  @Column({ nullable: true })",
  "  department: string",
  "  @Column({ nullable: true })",
  "  phone: string",
  "  @Column({ nullable: true })",
  "  email: string",
  "  @Column({ name: 'date_of_joining', type: 'date', nullable: true })",
  "  dateOfJoining: string",
  "  @Column({ name: 'date_of_birth', type: 'date', nullable: true })",
  "  dateOfBirth: string",
  "  @Column({ name: 'aadhar_no', unique: true, nullable: true })",
  "  aadharNo: string",
  "  @Column({ name: 'pan_no', nullable: true })",
  "  panNo: string",
  "  @Column({ name: 'bank_account', type: 'jsonb', default: {} })",
  "  bankAccount: Record<string, string>",
  "  @Column({ name: 'base_salary', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  baseSalary: number",
  "  @Column({ name: 'hra', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  hra: number",
  "  @Column({ name: 'allowances', type: 'decimal', precision: 10, scale: 2, default: 0 })",
  "  allowances: number",
  "  @Column({ name: 'employment_type', type: 'enum', enum: EmploymentType, default: EmploymentType.CONTRACT })",
  "  employmentType: EmploymentType",
  "  @Column({ type: 'enum', enum: EmployeeStatus, default: EmployeeStatus.ACTIVE })",
  "  status: EmployeeStatus",
  "  @Column({ name: 'project_id', nullable: true })",
  "  projectId: string",
  "  @Column({ name: 'photo_url', nullable: true })",
  "  photoUrl: string",
  "  @CreateDateColumn({ name: 'created_at' })",
  "  createdAt: Date",
  "}",
])

w('attendance.entity.ts', [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum AttendanceStatus { PRESENT='present', ABSENT='absent', HALF_DAY='half_day', LEAVE='leave', HOLIDAY='holiday' }",
  "export enum AttendanceSource { MOBILE='mobile', MANUAL='manual', BIOMETRIC='biometric' }",
  "",
  "@Entity('attendance')",
  "export class Attendance extends BaseEntity {",
  "  @Column({ name: 'employee_id' }) employeeId: string",
  "  @Column({ name: 'project_id', nullable: true }) projectId: string",
  "  @Column({ type: 'date' }) date: string",
  "  @Column({ name: 'check_in_time', nullable: true }) checkInTime: Date",
  "  @Column({ name: 'check_in_lat', type: 'decimal', precision: 10, scale: 8, nullable: true }) checkInLat: number",
  "  @Column({ name: 'check_in_lng', type: 'decimal', precision: 11, scale: 8, nullable: true }) checkInLng: number",
  "  @Column({ name: 'check_out_time', nullable: true }) checkOutTime: Date",
  "  @Column({ name: 'check_out_lat', type: 'decimal', precision: 10, scale: 8, nullable: true }) checkOutLat: number",
  "  @Column({ name: 'check_out_lng', type: 'decimal', precision: 11, scale: 8, nullable: true }) checkOutLng: number",
  "  @Column({ name: 'hours_worked', type: 'decimal', precision: 5, scale: 2, nullable: true }) hoursWorked: number",
  "  @Column({ name: 'geo_verified', default: false }) geoVerified: boolean",
  "  @Column({ name: 'distance_from_site', type: 'integer', nullable: true }) distanceFromSite: number",
  "  @Column({ type: 'enum', enum: AttendanceStatus, default: AttendanceStatus.PRESENT }) status: AttendanceStatus",
  "  @Column({ type: 'enum', enum: AttendanceSource, default: AttendanceSource.MANUAL }) source: AttendanceSource",
  "  @Column({ type: 'text', nullable: true }) remarks: string",
  "  @CreateDateColumn({ name: 'created_at' }) createdAt: Date",
  "}",
])

w('salary-record.entity.ts', [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum SalaryStatus { DRAFT='draft', APPROVED='approved', PAID='paid' }",
  "",
  "@Entity('salary_records')",
  "export class SalaryRecord extends BaseEntity {",
  "  @Column({ name: 'employee_id' }) employeeId: string",
  "  @Column() month: number",
  "  @Column() year: number",
  "  @Column({ name: 'working_days', nullable: true }) workingDays: number",
  "  @Column({ name: 'days_present', type: 'decimal', precision: 5, scale: 2, nullable: true }) daysPresent: number",
  "  @Column({ name: 'days_absent', type: 'decimal', precision: 5, scale: 2, default: 0 }) daysAbsent: number",
  "  @Column({ name: 'base_salary', type: 'decimal', precision: 10, scale: 2, default: 0 }) baseSalary: number",
  "  @Column({ name: 'hra', type: 'decimal', precision: 10, scale: 2, default: 0 }) hra: number",
  "  @Column({ name: 'allowances', type: 'decimal', precision: 10, scale: 2, default: 0 }) allowances: number",
  "  @Column({ name: 'gross_salary', type: 'decimal', precision: 10, scale: 2, default: 0 }) grossSalary: number",
  "  @Column({ name: 'pf_amount', type: 'decimal', precision: 10, scale: 2, default: 0 }) pfAmount: number",
  "  @Column({ name: 'esi_amount', type: 'decimal', precision: 10, scale: 2, default: 0 }) esiAmount: number",
  "  @Column({ name: 'tds_amount', type: 'decimal', precision: 10, scale: 2, default: 0 }) tdsAmount: number",
  "  @Column({ name: 'other_deductions', type: 'decimal', precision: 10, scale: 2, default: 0 }) otherDeductions: number",
  "  @Column({ name: 'net_salary', type: 'decimal', precision: 10, scale: 2, default: 0 }) netSalary: number",
  "  @Column({ type: 'enum', enum: SalaryStatus, default: SalaryStatus.DRAFT }) status: SalaryStatus",
  "  @Column({ name: 'paid_on', type: 'date', nullable: true }) paidOn: string",
  "  @Column({ name: 'payment_mode', nullable: true }) paymentMode: string",
  "  @Column({ name: 'approved_by', nullable: true }) approvedBy: string",
  "  @CreateDateColumn({ name: 'created_at' }) createdAt: Date",
  "}",
])

w('leave-request.entity.ts', [
  "import { Entity, Column, CreateDateColumn } from 'typeorm'",
  "import { BaseEntity } from '../shared/entities/base.entity'",
  "",
  "export enum LeaveType { CASUAL='casual', EARNED='earned', SICK='sick', UNPAID='unpaid' }",
  "export enum LeaveStatus { PENDING='pending', APPROVED='approved', REJECTED='rejected' }",
  "",
  "@Entity('leave_requests')",
  "export class LeaveRequest extends BaseEntity {",
  "  @Column({ name: 'employee_id' }) employeeId: string",
  "  @Column({ type: 'enum', enum: LeaveType }) leaveType: LeaveType",
  "  @Column({ name: 'from_date', type: 'date' }) fromDate: string",
  "  @Column({ name: 'to_date', type: 'date' }) toDate: string",
  "  @Column({ type: 'text', nullable: true }) reason: string",
  "  @Column({ type: 'enum', enum: LeaveStatus, default: LeaveStatus.PENDING }) status: LeaveStatus",
  "  @Column({ name: 'approved_by', nullable: true }) approvedBy: string",
  "  @Column({ name: 'approved_at', nullable: true }) approvedAt: Date",
  "  @CreateDateColumn({ name: 'created_at' }) createdAt: Date",
  "}",
])
ok('4 entities (Employee, Attendance, SalaryRecord, LeaveRequest)')

// ── DTOs ──────────────────────────────────────────────────────
info('Writing DTOs...')
w('dto/create-employee.dto.ts', [
  "import { IsEnum, IsNotEmpty, IsOptional, IsString, IsNumber } from 'class-validator'",
  "import { EmploymentType } from '../employee.entity'",
  "export class CreateEmployeeDto {",
  "  @IsString() @IsNotEmpty()  empCode:        string",
  "  @IsString() @IsNotEmpty()  firstName:      string",
  "  @IsOptional() @IsString()  lastName?:      string",
  "  @IsOptional() @IsString()  designation?:   string",
  "  @IsOptional() @IsString()  department?:    string",
  "  @IsOptional() @IsString()  phone?:         string",
  "  @IsOptional() @IsString()  email?:         string",
  "  @IsOptional() @IsString()  dateOfJoining?: string",
  "  @IsOptional() @IsString()  dateOfBirth?:   string",
  "  @IsOptional() @IsString()  aadharNo?:      string",
  "  @IsOptional() @IsString()  panNo?:         string",
  "  @IsOptional()              bankAccount?:   Record<string, string>",
  "  @IsNumber()                baseSalary:     number",
  "  @IsOptional() @IsNumber()  hra?:           number",
  "  @IsOptional() @IsNumber()  allowances?:    number",
  "  @IsOptional() @IsEnum(EmploymentType) employmentType?: EmploymentType",
  "  @IsOptional() @IsString()  projectId?:     string",
  "}",
])
w('dto/mark-attendance.dto.ts', [
  "import { IsDateString, IsEnum, IsNotEmpty, IsOptional, IsString, IsNumber } from 'class-validator'",
  "import { AttendanceStatus, AttendanceSource } from '../attendance.entity'",
  "export class MarkAttendanceDto {",
  "  @IsString() @IsNotEmpty()  employeeId: string",
  "  @IsDateString()            date:       string",
  "  @IsEnum(AttendanceStatus)  status:     AttendanceStatus",
  "  @IsOptional() @IsEnum(AttendanceSource) source?: AttendanceSource",
  "  @IsOptional() @IsNumber()  checkInLat?:   number",
  "  @IsOptional() @IsNumber()  checkInLng?:   number",
  "  @IsOptional() @IsString()  checkInTime?:  string",
  "  @IsOptional() @IsString()  checkOutTime?: string",
  "  @IsOptional() @IsString()  remarks?:      string",
  "  @IsOptional() @IsString()  projectId?:    string",
  "}",
])
w('dto/generate-salary.dto.ts', [
  "import { IsInt, IsNotEmpty, IsString, Max, Min } from 'class-validator'",
  "export class GenerateSalaryDto {",
  "  @IsString() @IsNotEmpty() employeeId: string",
  "  @IsInt() @Min(1) @Max(12) month:      number",
  "  @IsInt() @Min(2020)       year:       number",
  "}",
])
w('dto/apply-leave.dto.ts', [
  "import { IsDateString, IsEnum, IsNotEmpty, IsOptional, IsString } from 'class-validator'",
  "import { LeaveType } from '../leave-request.entity'",
  "export class ApplyLeaveDto {",
  "  @IsString() @IsNotEmpty()  employeeId: string",
  "  @IsEnum(LeaveType)         leaveType:  LeaveType",
  "  @IsDateString()            fromDate:   string",
  "  @IsDateString()            toDate:     string",
  "  @IsOptional() @IsString()  reason?:    string",
  "}",
])
ok('DTOs written')

// ── SERVICE ───────────────────────────────────────────────────
info('Writing HrService...')
w('hr.service.ts', [
  "import { Injectable, NotFoundException, ConflictException, Logger } from '@nestjs/common'",
  "import { InjectRepository } from '@nestjs/typeorm'",
  "import { Repository } from 'typeorm'",
  "import { ConfigService } from '@nestjs/config'",
  "import { Employee, EmployeeStatus } from './employee.entity'",
  "import { Attendance, AttendanceStatus, AttendanceSource } from './attendance.entity'",
  "import { SalaryRecord, SalaryStatus } from './salary-record.entity'",
  "import { LeaveRequest, LeaveStatus } from './leave-request.entity'",
  "import { CreateEmployeeDto } from './dto/create-employee.dto'",
  "import { MarkAttendanceDto } from './dto/mark-attendance.dto'",
  "import { GenerateSalaryDto } from './dto/generate-salary.dto'",
  "import { ApplyLeaveDto } from './dto/apply-leave.dto'",
  "",
  "function gpsDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {",
  "  const R = 6371000",
  "  const toR = (d: number) => (d * Math.PI) / 180",
  "  const dLat = toR(lat2 - lat1)",
  "  const dLng = toR(lng2 - lng1)",
  "  const a = Math.sin(dLat/2)**2 + Math.cos(toR(lat1)) * Math.cos(toR(lat2)) * Math.sin(dLng/2)**2",
  "  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))",
  "}",
  "",
  "function workingDaysInMonth(year: number, month: number): number {",
  "  const days = new Date(year, month, 0).getDate()",
  "  let count = 0",
  "  for (let d = 1; d <= days; d++) {",
  "    if (new Date(year, month - 1, d).getDay() !== 0) count++",
  "  }",
  "  return count",
  "}",
  "",
  "@Injectable()",
  "export class HrService {",
  "  private readonly log = new Logger(HrService.name)",
  "  constructor(",
  "    @InjectRepository(Employee)      private readonly empRepo:   Repository<Employee>,",
  "    @InjectRepository(Attendance)    private readonly attRepo:   Repository<Attendance>,",
  "    @InjectRepository(SalaryRecord)  private readonly salRepo:   Repository<SalaryRecord>,",
  "    @InjectRepository(LeaveRequest)  private readonly leaveRepo: Repository<LeaveRequest>,",
  "    private readonly config: ConfigService,",
  "  ) {}",
  "",
  "  async createEmployee(dto: CreateEmployeeDto): Promise<Employee> {",
  "    const exists = await this.empRepo.findOne({ where: { empCode: dto.empCode } })",
  "    if (exists) throw new ConflictException('Employee code already exists')",
  "    return this.empRepo.save(this.empRepo.create(dto))",
  "  }",
  "",
  "  async listEmployees(p: { department?: string; status?: string; search?: string; projectId?: string }) {",
  "    const qb = this.empRepo.createQueryBuilder('e').orderBy('e.createdAt', 'DESC')",
  "    if (p.department) qb.andWhere('e.department = :dept', { dept: p.department })",
  "    if (p.status)     qb.andWhere('e.status = :status', { status: p.status })",
  "    if (p.projectId)  qb.andWhere('e.projectId = :pid', { pid: p.projectId })",
  "    if (p.search)     qb.andWhere('(e.firstName ILIKE :s OR e.lastName ILIKE :s OR e.empCode ILIKE :s)', { s: '%' + p.search + '%' })",
  "    return qb.getMany()",
  "  }",
  "",
  "  async getEmployee(id: string): Promise<Employee> {",
  "    const emp = await this.empRepo.findOne({ where: { id } })",
  "    if (!emp) throw new NotFoundException('Employee not found')",
  "    return emp",
  "  }",
  "",
  "  async updateEmployee(id: string, data: Partial<Employee>): Promise<Employee> {",
  "    await this.empRepo.update(id, data)",
  "    return this.getEmployee(id)",
  "  }",
  "",
  "  async markAttendance(dto: MarkAttendanceDto): Promise<Attendance> {",
  "    const existing = await this.attRepo.findOne({ where: { employeeId: dto.employeeId, date: dto.date } })",
  "    let geoVerified = false",
  "    let distanceFromSite: number | undefined",
  "    const SITE_LAT = 34.0920",
  "    const SITE_LNG = 74.8740",
  "    const GEO_RADIUS = parseInt(this.config.get('GEO_FENCE_RADIUS') ?? '500')",
  "    if (dto.checkInLat && dto.checkInLng) {",
  "      distanceFromSite = Math.round(gpsDistance(dto.checkInLat, dto.checkInLng, SITE_LAT, SITE_LNG))",
  "      geoVerified = distanceFromSite <= GEO_RADIUS",
  "    }",
  "    const record = this.attRepo.create({",
  "      employeeId: dto.employeeId, date: dto.date, status: dto.status,",
  "      source: dto.source ?? AttendanceSource.MANUAL, projectId: dto.projectId,",
  "      checkInLat: dto.checkInLat, checkInLng: dto.checkInLng,",
  "      checkInTime: dto.checkInTime ? new Date(dto.checkInTime) : new Date(),",
  "      checkOutTime: dto.checkOutTime ? new Date(dto.checkOutTime) : undefined,",
  "      geoVerified, distanceFromSite, remarks: dto.remarks,",
  "    })",
  "    if (existing) {",
  "      await this.attRepo.update(existing.id, record)",
  "      return this.attRepo.findOne({ where: { id: existing.id } }) as Promise<Attendance>",
  "    }",
  "    return this.attRepo.save(record)",
  "  }",
  "",
  "  async bulkMarkAttendance(records: MarkAttendanceDto[]): Promise<{ saved: number; errors: string[] }> {",
  "    let saved = 0; const errors: string[] = []",
  "    for (const r of records) {",
  "      try { await this.markAttendance(r); saved++ }",
  "      catch (e: any) { errors.push(r.employeeId + ': ' + e.message) }",
  "    }",
  "    return { saved, errors }",
  "  }",
  "",
  "  async getAttendance(p: { employeeId?: string; date?: string; month?: number; year?: number; projectId?: string }) {",
  "    const qb = this.attRepo.createQueryBuilder('a').orderBy('a.date', 'DESC')",
  "    if (p.employeeId) qb.andWhere('a.employeeId = :eid', { eid: p.employeeId })",
  "    if (p.date)       qb.andWhere('a.date = :date', { date: p.date })",
  "    if (p.projectId)  qb.andWhere('a.projectId = :pid', { pid: p.projectId })",
  "    if (p.month && p.year) qb.andWhere('EXTRACT(MONTH FROM a.date) = :m AND EXTRACT(YEAR FROM a.date) = :y', { m: p.month, y: p.year })",
  "    return qb.getMany()",
  "  }",
  "",
  "  async getTodayAttendance(projectId?: string) {",
  "    const today = new Date().toISOString().split('T')[0]",
  "    const records = await this.getAttendance({ date: today, projectId })",
  "    const allEmp  = await this.empRepo.find({ where: { status: EmployeeStatus.ACTIVE, ...(projectId ? { projectId } : {}) } })",
  "    const markedIds = records.map(r => r.employeeId)",
  "    const absent = allEmp.filter(e => !markedIds.includes(e.id))",
  "    return {",
  "      date: today,",
  "      present: records.filter(r => r.status === AttendanceStatus.PRESENT).length,",
  "      absent: absent.length,",
  "      halfDay: records.filter(r => r.status === AttendanceStatus.HALF_DAY).length,",
  "      onLeave: records.filter(r => r.status === AttendanceStatus.LEAVE).length,",
  "      total: allEmp.length,",
  "      records,",
  "      absentEmployees: absent.map(e => ({ id: e.id, empCode: e.empCode, name: (e.firstName + ' ' + (e.lastName ?? '')).trim(), designation: e.designation })),",
  "    }",
  "  }",
  "",
  "  async getMonthlyReport(employeeId: string, year: number, month: number) {",
  "    const records = await this.getAttendance({ employeeId, month, year })",
  "    return {",
  "      records,",
  "      summary: {",
  "        present:       records.filter(r => r.status === AttendanceStatus.PRESENT).length,",
  "        absent:        records.filter(r => r.status === AttendanceStatus.ABSENT).length,",
  "        halfDay:       records.filter(r => r.status === AttendanceStatus.HALF_DAY).length,",
  "        onLeave:       records.filter(r => r.status === AttendanceStatus.LEAVE).length,",
  "        geoUnverified: records.filter(r => !r.geoVerified && r.status === AttendanceStatus.PRESENT).length,",
  "        workingDays:   workingDaysInMonth(year, month),",
  "      },",
  "    }",
  "  }",
  "",
  "  async generateSalary(dto: GenerateSalaryDto, generatedBy: string): Promise<SalaryRecord> {",
  "    const existing = await this.salRepo.findOne({ where: { employeeId: dto.employeeId, month: dto.month, year: dto.year } })",
  "    if (existing) throw new ConflictException('Salary already generated for this month')",
  "    const emp = await this.getEmployee(dto.employeeId)",
  "    const { summary } = await this.getMonthlyReport(dto.employeeId, dto.year, dto.month)",
  "    const workingDays = summary.workingDays",
  "    const daysPresent = summary.present + (summary.halfDay * 0.5)",
  "    const perDay      = Number(emp.baseSalary) / workingDays",
  "    const earnedBasic = perDay * daysPresent",
  "    const earnedHra   = (Number(emp.hra) / workingDays) * daysPresent",
  "    const allowances  = Number(emp.allowances)",
  "    const gross       = earnedBasic + earnedHra + allowances",
  "    const PF_RATE     = parseFloat(this.config.get('PF_RATE') ?? '0.12')",
  "    const pfAmount    = Math.min(Number(emp.baseSalary), 15000) * PF_RATE",
  "    const ESI_THRESHOLD = parseFloat(this.config.get('ESI_THRESHOLD') ?? '21000')",
  "    const ESI_RATE    = parseFloat(this.config.get('ESI_RATE') ?? '0.0075')",
  "    const esiAmount   = gross <= ESI_THRESHOLD ? gross * ESI_RATE : 0",
  "    const netSalary   = gross - pfAmount - esiAmount",
  "    return this.salRepo.save(this.salRepo.create({",
  "      employeeId: dto.employeeId, month: dto.month, year: dto.year,",
  "      workingDays, daysPresent, daysAbsent: workingDays - daysPresent,",
  "      baseSalary: +earnedBasic.toFixed(2), hra: +earnedHra.toFixed(2), allowances,",
  "      grossSalary: +gross.toFixed(2), pfAmount: +pfAmount.toFixed(2),",
  "      esiAmount: +esiAmount.toFixed(2), tdsAmount: 0, otherDeductions: 0,",
  "      netSalary: +netSalary.toFixed(2), status: SalaryStatus.DRAFT, approvedBy: generatedBy,",
  "    }))",
  "  }",
  "",
  "  async listSalary(p: { employeeId?: string; month?: number; year?: number; status?: string }) {",
  "    const qb = this.salRepo.createQueryBuilder('s').orderBy('s.year','DESC').addOrderBy('s.month','DESC')",
  "    if (p.employeeId) qb.andWhere('s.employeeId = :eid', { eid: p.employeeId })",
  "    if (p.month)      qb.andWhere('s.month = :m', { m: p.month })",
  "    if (p.year)       qb.andWhere('s.year = :y', { y: p.year })",
  "    if (p.status)     qb.andWhere('s.status = :s', { s: p.status })",
  "    return qb.getMany()",
  "  }",
  "",
  "  async approveSalary(id: string): Promise<SalaryRecord> {",
  "    await this.salRepo.update(id, { status: SalaryStatus.APPROVED })",
  "    const rec = await this.salRepo.findOne({ where: { id } })",
  "    if (!rec) throw new NotFoundException('Not found')",
  "    return rec",
  "  }",
  "",
  "  async markPaid(id: string, paymentMode: string): Promise<SalaryRecord> {",
  "    await this.salRepo.update(id, { status: SalaryStatus.PAID, paidOn: new Date().toISOString().split('T')[0], paymentMode })",
  "    const rec = await this.salRepo.findOne({ where: { id } })",
  "    if (!rec) throw new NotFoundException('Not found')",
  "    return rec",
  "  }",
  "",
  "  async applyLeave(dto: ApplyLeaveDto): Promise<LeaveRequest> {",
  "    return this.leaveRepo.save(this.leaveRepo.create(dto))",
  "  }",
  "",
  "  async listLeaves(p: { employeeId?: string; status?: string }) {",
  "    const qb = this.leaveRepo.createQueryBuilder('l').orderBy('l.createdAt','DESC')",
  "    if (p.employeeId) qb.andWhere('l.employeeId = :eid', { eid: p.employeeId })",
  "    if (p.status)     qb.andWhere('l.status = :s', { s: p.status })",
  "    return qb.getMany()",
  "  }",
  "",
  "  async processLeave(id: string, status: LeaveStatus, approvedBy: string): Promise<LeaveRequest> {",
  "    await this.leaveRepo.update(id, { status, approvedBy, approvedAt: new Date() })",
  "    const leave = await this.leaveRepo.findOne({ where: { id } })",
  "    if (!leave) throw new NotFoundException('Not found')",
  "    return leave",
  "  }",
  "",
  "  async dashboard(projectId?: string) {",
  "    const empFilter: any = { status: EmployeeStatus.ACTIVE }",
  "    if (projectId) empFilter.projectId = projectId",
  "    const totalEmp = await this.empRepo.count({ where: empFilter })",
  "    const today    = await this.getTodayAttendance(projectId)",
  "    const pendingLeaves    = await this.leaveRepo.count({ where: { status: LeaveStatus.PENDING } })",
  "    const pendingSalaries  = await this.salRepo.count({ where: { status: SalaryStatus.DRAFT } })",
  "    return {",
  "      totalEmployees: totalEmp,",
  "      presentToday:   today.present,",
  "      absentToday:    today.absent,",
  "      onLeaveToday:   today.onLeave,",
  "      attendancePct:  totalEmp > 0 ? Math.round((today.present / totalEmp) * 100) : 0,",
  "      pendingLeaves,",
  "      pendingSalaries,",
  "    }",
  "  }",
  "}",
])
ok('HrService written')

// ── CONTROLLER ────────────────────────────────────────────────
info('Writing HrController...')
w('hr.controller.ts', [
  "import { Controller, Get, Post, Patch, Param, Body, Query, UseGuards, Request, HttpCode, HttpStatus } from '@nestjs/common'",
  "import { HrService } from './hr.service'",
  "import { CreateEmployeeDto } from './dto/create-employee.dto'",
  "import { MarkAttendanceDto } from './dto/mark-attendance.dto'",
  "import { GenerateSalaryDto } from './dto/generate-salary.dto'",
  "import { ApplyLeaveDto } from './dto/apply-leave.dto'",
  "import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard'",
  "import { LeaveStatus } from './leave-request.entity'",
  "",
  "@Controller('hr')",
  "@UseGuards(JwtAuthGuard)",
  "export class HrController {",
  "  constructor(private readonly svc: HrService) {}",
  "  @Get('dashboard')",
  "  dashboard(@Query('projectId') projectId?: string) { return this.svc.dashboard(projectId) }",
  "  @Get('employees')",
  "  listEmployees(@Query() q: any) { return this.svc.listEmployees({ department: q.department, status: q.status, search: q.search, projectId: q.projectId }) }",
  "  @Post('employees') @HttpCode(HttpStatus.CREATED)",
  "  createEmployee(@Body() dto: CreateEmployeeDto) { return this.svc.createEmployee(dto) }",
  "  @Get('employees/:id')",
  "  getEmployee(@Param('id') id: string) { return this.svc.getEmployee(id) }",
  "  @Patch('employees/:id')",
  "  updateEmployee(@Param('id') id: string, @Body() body: any) { return this.svc.updateEmployee(id, body) }",
  "  @Get('attendance')",
  "  getAttendance(@Query() q: any) { return this.svc.getAttendance({ employeeId: q.employeeId, date: q.date, month: q.month ? parseInt(q.month) : undefined, year: q.year ? parseInt(q.year) : undefined, projectId: q.projectId }) }",
  "  @Get('attendance/today')",
  "  todayAttendance(@Query('projectId') projectId?: string) { return this.svc.getTodayAttendance(projectId) }",
  "  @Post('attendance') @HttpCode(HttpStatus.CREATED)",
  "  markAttendance(@Body() dto: MarkAttendanceDto) { return this.svc.markAttendance(dto) }",
  "  @Post('attendance/bulk') @HttpCode(HttpStatus.CREATED)",
  "  bulkAttendance(@Body() body: { records: MarkAttendanceDto[] }) { return this.svc.bulkMarkAttendance(body.records) }",
  "  @Get('attendance/report/:empId/:year/:month')",
  "  monthlyReport(@Param('empId') empId: string, @Param('year') year: string, @Param('month') month: string) { return this.svc.getMonthlyReport(empId, parseInt(year), parseInt(month)) }",
  "  @Get('salary')",
  "  listSalary(@Query() q: any) { return this.svc.listSalary({ employeeId: q.employeeId, month: q.month ? parseInt(q.month) : undefined, year: q.year ? parseInt(q.year) : undefined, status: q.status }) }",
  "  @Post('salary/generate') @HttpCode(HttpStatus.CREATED)",
  "  generateSalary(@Body() dto: GenerateSalaryDto, @Request() req: any) { return this.svc.generateSalary(dto, req.user.id) }",
  "  @Patch('salary/:id/approve')",
  "  approveSalary(@Param('id') id: string) { return this.svc.approveSalary(id) }",
  "  @Patch('salary/:id/paid')",
  "  markPaid(@Param('id') id: string, @Body('paymentMode') pm: string) { return this.svc.markPaid(id, pm ?? 'bank_transfer') }",
  "  @Get('leave')",
  "  listLeaves(@Query() q: any) { return this.svc.listLeaves({ employeeId: q.employeeId, status: q.status }) }",
  "  @Post('leave') @HttpCode(HttpStatus.CREATED)",
  "  applyLeave(@Body() dto: ApplyLeaveDto) { return this.svc.applyLeave(dto) }",
  "  @Patch('leave/:id/approve')",
  "  approveLeave(@Param('id') id: string, @Request() req: any) { return this.svc.processLeave(id, LeaveStatus.APPROVED, req.user.id) }",
  "  @Patch('leave/:id/reject')",
  "  rejectLeave(@Param('id') id: string, @Request() req: any) { return this.svc.processLeave(id, LeaveStatus.REJECTED, req.user.id) }",
  "}",
])
ok('HrController written')

// ── MODULE ────────────────────────────────────────────────────
info('Writing HrModule...')
w('hr.module.ts', [
  "import { Module } from '@nestjs/common'",
  "import { TypeOrmModule } from '@nestjs/typeorm'",
  "import { Employee }     from './employee.entity'",
  "import { Attendance }   from './attendance.entity'",
  "import { SalaryRecord } from './salary-record.entity'",
  "import { LeaveRequest } from './leave-request.entity'",
  "import { HrService }    from './hr.service'",
  "import { HrController } from './hr.controller'",
  "@Module({",
  "  imports:     [TypeOrmModule.forFeature([Employee, Attendance, SalaryRecord, LeaveRequest])],",
  "  providers:   [HrService],",
  "  controllers: [HrController],",
  "  exports:     [HrService],",
  "})",
  "export class HrModule {}",
])
ok('HrModule written')

// ── Register in app.module.ts ──────────────────────────────────
info('Registering in app.module.ts...')
const appModulePath = path.join(SRC, 'app.module.ts')
let appModule = fs.readFileSync(appModulePath, 'utf8')

if (!appModule.includes("from './hr/hr.module'")) {
  appModule = appModule.replace(
    "import { LiaisonModule }",
    "import { HrModule } from './hr/hr.module'\nimport { LiaisonModule }"
  )
  appModule = appModule.replace('LiaisonModule,', 'LiaisonModule,\n    HrModule,')
  fs.writeFileSync(appModulePath, appModule)
  ok('HrModule registered in app.module.ts')
} else {
  ok('HrModule already registered')
}

// ── .env variables ─────────────────────────────────────────────
info('Updating .env...')
const envPath = path.join(ROOT, 'backend', '.env')
let env = fs.readFileSync(envPath, 'utf8')
if (!env.includes('PF_RATE')) {
  env += '\n# Salary config\nPF_RATE=0.12\nESI_THRESHOLD=21000\nESI_RATE=0.0075\nGEO_FENCE_RADIUS=500\n'
  fs.writeFileSync(envPath, env)
  ok('.env updated with salary config')
} else {
  ok('.env already has salary config')
}

console.log('\n' + G + '\x1b[1m  HR Backend complete!\x1b[0m' + NC)
console.log('\n  Endpoints:')
console.log('  GET  /api/v1/hr/dashboard')
console.log('  GET  /api/v1/hr/employees')
console.log('  POST /api/v1/hr/employees')
console.log('  GET  /api/v1/hr/attendance/today')
console.log('  POST /api/v1/hr/attendance')
console.log('  POST /api/v1/hr/attendance/bulk')
console.log('  POST /api/v1/hr/salary/generate')
console.log('\n  Backend will auto-reload.\n')
