import { jsPDF } from 'jspdf'
import * as echarts from 'echarts'
import { cpmOption, pertOption, ganttOption } from './WbsCharts'

// Render an echarts option into an off-screen canvas and return a PNG data URL
async function renderChart(option: any, w: number, h: number): Promise<string> {
  const div = document.createElement('div')
  div.style.cssText = `position:fixed;left:-99999px;top:0;width:${w}px;height:${h}px;background:#fff;`
  document.body.appendChild(div)
  const chart = echarts.init(div, undefined, { renderer: 'canvas', width: w, height: h })
  chart.setOption(option)
  await new Promise(r => setTimeout(r, 120)) // brief tick for synchronous canvas render
  const url = chart.getDataURL({ pixelRatio: 2, backgroundColor: '#ffffff' })
  chart.dispose()
  div.remove()
  return url
}

export interface ReportInput {
  projectName: string
  client: string
  allotment: string
  projectStart: string
  gantt: any[]
  cpm: any        // cpmData: { allTasks, criticalPath }
  pert: any       // pertData: { projectExpectedDuration, projectStdDeviation, probability68, probability95, contractOnTimeProbPct }
  kpis: { overallProgress: number; contractPct: number; daysRemaining: number; completed: number; total: number; milestonesHit: string }
}

// A3 landscape: 420 × 297 mm
export async function generateMonthlyReport(d: ReportInput) {
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a3' })
  const W = 420, M = 15
  const month = new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })
  const NAVY = '#0a1e28'

  const header = (title: string) => {
    pdf.setFillColor(NAVY); pdf.rect(0, 0, W, 26, 'F')
    pdf.setTextColor('#ffffff'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(15)
    pdf.text(d.projectName, M, 12)
    pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); pdf.setTextColor('#9DB4C6')
    pdf.text(`${title}  ·  ${month}`, M, 20)
    pdf.setTextColor('#9DB4C6'); pdf.setFontSize(8)
    pdf.text(`Client: ${d.client}   ·   Allotment: ${d.allotment}`, W - M, 12, { align: 'right' })
    pdf.text('kiplstpsrinagar.com · Tender Clause 17 Submission', W - M, 20, { align: 'right' })
  }
  const footer = () => {
    pdf.setDrawColor('#dbe6e0'); pdf.line(M, 285, W - M, 285)
    pdf.setFontSize(7.5); pdf.setTextColor('#6b8592')
    pdf.text('Generated by KIPL ProjectOS — Clause 17 & Clause 16.3 Schedule Submission (CPM · PERT · Gantt)', M, 291)
    pdf.text(new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }), W - M, 291, { align: 'right' })
  }

  // Pre-render all 3 charts in parallel for maximum performance
  const [ganttImg, cpmImg, pertImg] = await Promise.all([
    renderChart(ganttOption(d.gantt, d.projectStart), 1600, 950),
    renderChart(cpmOption(d.cpm?.allTasks ?? []), 1600, 900),
    renderChart(pertOption({
      mean: d.pert?.projectExpectedDuration,
      sigma: d.pert?.projectStdDeviation,
      p68: d.pert?.probability68,
      p95: d.pert?.probability95,
      contractTargetDays: 912,
    }), 1600, 800),
  ])

  // ── Page 1 · Cover + KPIs + Clause 16.3 Benchmarks ──
  header('Monthly Progress Report — Schedule & Contract Compliance')
  pdf.setTextColor('#0a1e28'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(28)
  pdf.text('Project Programme & Risk Report', M, 64)
  pdf.setFont('helvetica', 'normal'); pdf.setFontSize(12); pdf.setTextColor('#3f5763')
  pdf.text('Critical Path Method (CPM) · PERT Completion Analysis · Gantt Baseline (Clause 16 & 17)', M, 75)

  const kpiRows: [string, string][] = [
    ['Contract Time Elapsed', d.kpis.contractPct + '%'],
    ['Physical Work Executed', d.kpis.overallProgress + '%'],
    ['Tasks Completed', `${d.kpis.completed} / ${d.kpis.total}`],
    ['Milestones Achieved', d.kpis.milestonesHit],
    ['Days Remaining', `${d.kpis.daysRemaining} days`],
    ['Critical Tasks Identified', String(d.cpm?.criticalPath?.length ?? 0)],
    ['PERT Expected Duration (TE)', `${d.pert?.projectExpectedDuration ?? 912} days`],
    ['On-Time Completion Confidence', `${d.pert?.contractOnTimeProbPct ?? 90}%`],
  ]

  let ky = 95
  kpiRows.forEach((r, i) => {
    const col = i % 2, x = M + col * 200, y = ky + Math.floor(i / 2) * 28
    pdf.setDrawColor('#dbe6e0'); pdf.setFillColor('#f4f7f5'); pdf.roundedRect(x, y, 190, 22, 2.5, 2.5, 'FD')
    pdf.setFontSize(8); pdf.setTextColor('#6b8592'); pdf.text(r[0].toUpperCase(), x + 8, y + 8)
    pdf.setFont('helvetica', 'bold'); pdf.setFontSize(13.5); pdf.setTextColor('#0a1e28'); pdf.text(r[1], x + 8, y + 17)
    pdf.setFont('helvetica', 'normal')
  })

  // Clause 16.3 Milestone Table on Cover Page
  let my = 220
  pdf.setFont('helvetica', 'bold'); pdf.setFontSize(11); pdf.setTextColor(NAVY)
  pdf.text('STATUTORY CLAUSE 16.3 PROGRESS MILESTONES (DELAY COMPENSATION BENCHMARKS)', M, my)
  my += 6

  const stages = [
    ['Stage 1 (1/4 Time)', 'Month 7.5 (228 Days)', '12.5% (1/8th of Work)', 'Mandatory Progress Threshold (Clause 16.3)'],
    ['Stage 2 (1/2 Time)', 'Month 15.0 (456 Days)', '37.5% (3/8ths of Work)', 'Mandatory Progress Threshold (Clause 16.3)'],
    ['Stage 3 (3/4 Time)', 'Month 22.5 (684 Days)', '75.0% (3/4ths of Work)', 'Mandatory Progress Threshold (Clause 16.3)'],
    ['Stage 4 (Full Completion)', 'Month 30.0 (912 Days)', '100.0% of Work', 'Contract Completion Deadline (07-05-2028)'],
  ]

  pdf.setFillColor('#1e293b'); pdf.rect(M, my, W - 2 * M, 7, 'F')
  pdf.setTextColor('#ffffff'); pdf.setFontSize(8.5); pdf.setFont('helvetica', 'bold')
  pdf.text('Contract Stage', M + 4, my + 5)
  pdf.text('Elapsed Time Target', M + 70, my + 5)
  pdf.text('Minimum Work Required', M + 150, my + 5)
  pdf.text('Statutory Implication (Clause 8.1 / 16.3)', M + 230, my + 5)
  my += 7

  stages.forEach((stg, idx) => {
    const rowBg = idx % 2 === 0 ? '#f8fafc' : '#ffffff'
    pdf.setFillColor(rowBg); pdf.rect(M, my, W - 2 * M, 8, 'F')
    pdf.setDrawColor('#e2e8f0'); pdf.rect(M, my, W - 2 * M, 8, 'S')
    pdf.setTextColor('#1e293b'); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(8)
    pdf.text(stg[0], M + 4, my + 5.5)
    pdf.text(stg[1], M + 70, my + 5.5)
    pdf.setFont('helvetica', 'bold')
    pdf.text(stg[2], M + 150, my + 5.5)
    pdf.setFont('helvetica', 'normal'); pdf.setTextColor('#64748b')
    pdf.text(stg[3], M + 230, my + 5.5)
    my += 8
  })

  footer()

  // ── Page 2 · Gantt ──
  pdf.addPage(); header('Gantt Chart Programme — Baseline & Critical Path')
  pdf.addImage(ganttImg, 'PNG', M, 32, W - 2 * M, 246)
  footer()

  // ── Page 3 · CPM network ──
  pdf.addPage(); header('Critical Path Method — Activity-on-Node Network Diagram')
  pdf.setFontSize(9); pdf.setTextColor('#7f1d1d')
  pdf.text(`Red nodes & links indicate the Critical Path (${d.cpm?.criticalPath?.length ?? 0} activities) — float ≤ 0 days. Any delay extends project completion.`, M, 31)
  pdf.addImage(cpmImg, 'PNG', M, 35, W - 2 * M, 242)
  footer()

  // ── Page 4 · PERT ──
  pdf.addPage(); header('PERT — Probabilistic Completion Analysis (Bell Curve & S-Curve)')
  pdf.setFontSize(9); pdf.setTextColor('#3f5763')
  pdf.text(`Expected duration TE = ${d.pert?.projectExpectedDuration ?? 912}d. Contractual 30-month target probability: ${d.pert?.contractOnTimeProbPct ?? 90}%.`, M, 31)
  pdf.addImage(pertImg, 'PNG', M, 35, W - 2 * M, 240)
  footer()

  pdf.save(`KIPL-Clause17-Schedule-Report-${month.replace(' ', '-')}.pdf`)
}
