import { jsPDF } from 'jspdf'
import * as echarts from 'echarts'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { pertOption } from './WbsCharts'
import { CpmTimeline, CpmNetwork } from './CpmViews'
import { svgMarkupToPng } from './cpmExport'
import type { CpmData } from './CpmViews'
import { clause16Checkpoints, describeVariance } from './cpmLayout'

// Render an echarts option into an off-screen canvas and return a PNG data URL
async function renderChart(option: any, w: number, h: number): Promise<string> {
  const div = document.createElement('div')
  div.style.cssText = `position:fixed;left:-99999px;top:0;width:${w}px;height:${h}px;background:#fff;`
  document.body.appendChild(div)
  const chart = echarts.init(div, undefined, { renderer: 'canvas', width: w, height: h })
  chart.setOption(option)
  await new Promise(r => setTimeout(r, 120)) // brief tick for synchronous canvas render
  const url = chart.getDataURL({ pixelRatio: 2, backgroundColor: '#ffffff' })
  chart.dispose()
  div.remove()
  return url
}

/** Draw one of the CPM views off-screen, exactly as the page does, and rasterise it. */
async function renderView(element: ReturnType<typeof createElement>) {
  const html = renderToStaticMarkup(element)
  const svg = html.slice(html.indexOf('<svg'), html.lastIndexOf('</svg>') + 6)
  const w = Number(/width="([\d.]+)"/.exec(svg)?.[1] ?? 1600)
  const h = Number(/height="([\d.]+)"/.exec(svg)?.[1] ?? 900)
  return svgMarkupToPng(svg, w, h, 2)
}

/** A same-origin image as a PNG data URL for jsPDF, or null if it cannot be loaded. */
function toDataUrl(url: string): Promise<string | null> {
  return new Promise(resolve => {
    const img = new Image()
    img.crossOrigin = 'anonymous'
    img.onload = () => {
      try {
        const c = document.createElement('canvas')
        c.width = img.naturalWidth; c.height = img.naturalHeight
        c.getContext('2d')!.drawImage(img, 0, 0)
        resolve(c.toDataURL('image/png'))
      } catch { resolve(null) }
    }
    img.onerror = () => resolve(null)
    img.src = url
  })
}

/** The KIPL logo at the top left of a 26 mm header banner; returns where the title text starts. */
async function headerLogo(pdf: jsPDF, margin: number): Promise<(draw: boolean) => number> {
  const logo = await toDataUrl('/assets/kipl-logo.png')
  return (draw: boolean) => {
    if (logo && draw) { try { pdf.addImage(logo, 'PNG', margin, 4.5, 18, 17) } catch { /* header prints without it */ } }
    return logo ? margin + 22 : margin
  }
}

/** Place an image inside a box on the page without stretching it. */
function fitImage(pdf: jsPDF, img: { dataUrl: string; width: number; height: number }, x: number, y: number, w: number, h: number) {
  const k = Math.min(w / img.width, h / img.height)
  pdf.addImage(img.dataUrl, 'PNG', x, y, img.width * k, img.height * k)
}

const fmt = (iso: string | null | undefined) => iso
  ? new Date(iso + 'T00:00:00Z').toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' })
  : '—'

export interface ReportInput {
  projectName: string
  client: string
  allotment: string
  cpm: CpmData
  pert: any       // GET /wbs/pert
  kpis: { overallProgress: number; contractPct: number; daysRemaining: number; completed: number; total: number; milestonesHit: string }
}

// A3 landscape: 420 × 297 mm
export async function generateMonthlyReport(d: ReportInput) {
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a3' })
  const W = 420, M = 15
  const month = new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })
  const NAVY = '#0a1e28'
  const variance = describeVariance(d.cpm.contractVarianceDays)
  const mu: number | null = d.pert?.projectExpectedDuration ?? null
  const sigma: number | null = d.pert?.projectStdDeviation ?? null
  const onTime: number | null = d.pert?.contractOnTimeProbPct ?? null

  const logo = await headerLogo(pdf, M)
  const header = (title: string) => {
    pdf.setFillColor(NAVY); pdf.rect(0, 0, W, 26, 'F')
    const tx = logo(true)
    pdf.setTextColor('#ffffff'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(15)
    pdf.text(d.projectName, tx, 12)
    pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); pdf.setTextColor('#9DB4C6')
    pdf.text(`${title}  ·  ${month}`, tx, 20)
    pdf.setTextColor('#9DB4C6'); pdf.setFontSize(8)
    pdf.text(`Client: ${d.client}   ·   Allotment: ${d.allotment}`, W - M, 12, { align: 'right' })
    pdf.text(`Data date ${fmt(d.cpm.dataDate)}  ·  Contract completion ${fmt(d.cpm.contractCompletion)}`, W - M, 20, { align: 'right' })
  }
  const footer = () => {
    pdf.setDrawColor('#dbe6e0'); pdf.line(M, 285, W - M, 285)
    pdf.setFontSize(7.5); pdf.setTextColor('#6b8592')
    pdf.text('Generated by KIPL ProjectOS — Clause 17 & Clause 16.3 Schedule Submission (CPM · PERT)', M, 291)
    pdf.text(new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }), W - M, 291, { align: 'right' })
  }

  // The network page shows the logic still to be worked: finished activities are
  // on the timeline page, and drawing them here shrinks the rest past legibility.
  const remainingRows = d.cpm.allTasks.filter(t => t.scope !== 'post_completion' && t.status !== 'complete')
  const doneCount = d.cpm.allTasks.filter(t => !t.isSummary && t.status === 'complete').length
  const [timelineImg, networkImg, pertImg] = await Promise.all([
    d.cpm.ok ? renderView(createElement(CpmTimeline, {
      cpm: d.cpm, rows: d.cpm.allTasks, width: 2000,
      checkpoints: clause16Checkpoints(d.cpm.projectStart, d.cpm.contractCompletion),
    })) : null,
    d.cpm.ok && remainingRows.length ? renderView(createElement(CpmNetwork, { rows: remainingRows })) : null,
    mu !== null && sigma !== null && sigma > 0
      ? renderChart(pertOption({ mean: mu, sigma, p68: d.pert?.probability68, p95: d.pert?.probability95, contractTargetDays: d.pert.contractTargetDays }), 1600, 800)
      : null,
  ])

  // ── Page 1 · Cover + KPIs + Clause 16.3 ──
  header('Monthly Progress Report — Schedule & Contract Compliance')
  pdf.setTextColor('#0a1e28'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(28)
  pdf.text('Project Programme & Risk Report', M, 64)
  pdf.setFont('helvetica', 'normal'); pdf.setFontSize(12); pdf.setTextColor('#3f5763')
  pdf.text('Critical Path Method (CPM) forecast · PERT completion analysis · Clause 16.3 progress stages', M, 75)

  const kpiRows: [string, string][] = [
    ['Contract Time Elapsed', d.kpis.contractPct + '%'],
    ['Physical Work Executed', d.kpis.overallProgress + '%'],
    ['Forecast Completion', d.cpm.forecastFinish ? fmt(d.cpm.forecastFinish) : 'not computed'],
    ['Against the Contract', variance.text],
    ['Tasks Completed', `${d.kpis.completed} / ${d.kpis.total}`],
    ['Milestones Achieved', d.kpis.milestonesHit],
    ['Activities on the Longest Path', String(d.cpm.longestPath.length)],
    ['On-Time Chance (single-path PERT)', onTime === null ? 'not computed' : `${onTime}%`],
  ]

  const ky = 92
  kpiRows.forEach((r, i) => {
    const col = i % 2, x = M + col * 200, y = ky + Math.floor(i / 2) * 26
    const late = r[0] === 'Against the Contract' && variance.tone === 'late'
    pdf.setDrawColor('#dbe6e0'); pdf.setFillColor(late ? '#fef2f2' : '#f4f7f5'); pdf.roundedRect(x, y, 190, 21, 2.5, 2.5, 'FD')
    pdf.setFontSize(8); pdf.setTextColor('#6b8592'); pdf.text(r[0].toUpperCase(), x + 8, y + 8)
    pdf.setFont('helvetica', 'bold'); pdf.setFontSize(13.5); pdf.setTextColor(late ? '#b91c1c' : '#0a1e28'); pdf.text(r[1], x + 8, y + 16.5)
    pdf.setFont('helvetica', 'normal')
  })

  let my = 206
  pdf.setFont('helvetica', 'bold'); pdf.setFontSize(11); pdf.setTextColor(NAVY)
  pdf.text('CLAUSE 16.3 PROGRESS STAGES — REQUIRED vs FORECAST', M, my)
  my += 6
  pdf.setFillColor('#1e293b'); pdf.rect(M, my, W - 2 * M, 7, 'F')
  pdf.setTextColor('#ffffff'); pdf.setFontSize(8.5); pdf.setFont('helvetica', 'bold')
  const cols = [M + 4, M + 70, M + 150, M + 230, M + 310]
  ;['Stage', 'Date', 'Work required', 'Forecast progress by then', 'Verdict'].forEach((h, i) => pdf.text(h, cols[i], my + 5))
  my += 7
  ;(d.pert?.clause16Milestones ?? []).forEach((s: any, idx: number) => {
    pdf.setFillColor(idx % 2 === 0 ? '#f8fafc' : '#ffffff'); pdf.rect(M, my, W - 2 * M, 8, 'F')
    pdf.setDrawColor('#e2e8f0'); pdf.rect(M, my, W - 2 * M, 8, 'S')
    pdf.setTextColor('#1e293b'); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(8)
    pdf.text(s.stage, cols[0], my + 5.5)
    pdf.text(`${fmt(s.date)} (day ${s.elapsedDays})`, cols[1], my + 5.5)
    pdf.setFont('helvetica', 'bold'); pdf.text(`${s.targetProgressPct}% (${s.rule})`, cols[2], my + 5.5)
    pdf.setFont('helvetica', 'normal')
    pdf.text(s.forecastProgressPct === null ? 'not computed' : `${Number(s.forecastProgressPct).toFixed(1)}%`, cols[3], my + 5.5)
    const verdict = s.forecastMeets === null ? 'Not computed' : s.forecastMeets ? (s.status === 'passed' ? 'Met' : 'On course') : (s.status === 'passed' ? 'Missed' : 'Forecast short')
    pdf.setTextColor(s.forecastMeets === false ? '#b91c1c' : s.forecastMeets ? '#166534' : '#64748b'); pdf.setFont('helvetica', 'bold')
    pdf.text(verdict, cols[4], my + 5.5)
    my += 8
  })
  footer()

  const unavailable = (why: string) => {
    pdf.setFontSize(12); pdf.setTextColor('#b91c1c')
    pdf.text(why, M, 50)
  }

  // ── Page 2 · Forecast timeline ──
  pdf.addPage(); header('Time-Scaled Logic Diagram — Forecast against Contract')
  if (timelineImg) fitImage(pdf, timelineImg, M, 32, W - 2 * M, 248)
  else unavailable('The schedule has errors, so no dates are calculated. See Schedule health in ProjectOS.')
  footer()

  // ── Page 3 · Network ──
  pdf.addPage(); header('Critical Path Method — Activity-on-Node Network (remaining contract work)')
  pdf.setFontSize(9); pdf.setTextColor('#7f1d1d')
  pdf.text(`Red boxes and links are the longest path (${d.cpm.longestPath.length} activities). Forecast completion ${fmt(d.cpm.forecastFinish)} — ${variance.text}. ${doneCount} completed activities are shown on the timeline page.`, M, 31)
  if (networkImg) fitImage(pdf, networkImg, M, 35, W - 2 * M, 244)
  else unavailable('The schedule has errors, so the network cannot be drawn.')
  footer()

  // ── Page 4 · PERT ──
  pdf.addPage(); header('PERT — Spread of the Forecast Finish')
  pdf.setFontSize(9); pdf.setTextColor('#3f5763')
  pdf.text(mu === null ? 'Expected finish not computed.' : `Expected finish day ${Math.round(mu)} against contract day ${d.pert.contractTargetDays}. On-time chance: ${onTime === null ? 'not computed' : onTime + '%'}.`, M, 31)
  pdf.setFontSize(8); pdf.setTextColor('#64748b')
  pdf.text(pdf.splitTextToSize(String(d.pert?.probabilityNote ?? ''), W - 2 * M), M, 37)
  if (pertImg) pdf.addImage(pertImg, 'PNG', M, 44, W - 2 * M, 200)
  else unavailable('No spread on the remaining longest path to draw.')
  footer()

  pdf.save(`KIPL-Clause17-Schedule-Report-${month.replace(' ', '-')}.pdf`)
}

export interface CpmPdfInput {
  projectName: string
  client: string
  allotment: string
  title: string
  scopeLabel: string
  /** The on-screen diagram, rasterised. */
  image: { dataUrl: string; width: number; height: number }
  cpm: CpmData
  fileStem: string
}

export async function generateCpmLandscapePdf(d: CpmPdfInput) {
  // A3 landscape: 420 × 297 mm
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a3' })
  const W = 420, H = 297, M = 15
  const NAVY = '#0a1e28'
  const dateStr = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
  const variance = describeVariance(d.cpm.contractVarianceDays)

  pdf.setFillColor(NAVY); pdf.rect(0, 0, W, 26, 'F')
  const tx = (await headerLogo(pdf, M))(true)
  pdf.setTextColor('#ffffff'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(15)
  pdf.text('KHILARI INFRASTRUCTURE PVT. LTD. (KIPL)', tx, 11)
  pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); pdf.setTextColor('#9DB4C6')
  pdf.text(`${d.projectName}  ·  ${d.title.toUpperCase()}`, tx, 19)
  pdf.setFontSize(8.5)
  pdf.text(`Client: ${d.client}   ·   Allotment: ${d.allotment}`, W - M, 11, { align: 'right' })
  pdf.text(`Clause 17 programme   ·   Generated ${dateStr}`, W - M, 19, { align: 'right' })

  // Key dates strip
  pdf.setFillColor('#f8fafc'); pdf.rect(0, 26, W, 14, 'F')
  pdf.setDrawColor('#e2e8f0'); pdf.line(0, 40, W, 40)
  const facts: [string, string, string?][] = [
    ['Data date', fmt(d.cpm.dataDate)],
    ['Contract completion', fmt(d.cpm.contractCompletion)],
    ['Forecast completion', fmt(d.cpm.forecastFinish), variance.tone === 'late' ? '#b91c1c' : '#047857'],
    ['Against the contract', variance.text, variance.tone === 'late' ? '#b91c1c' : '#047857'],
    ['Longest path', `${d.cpm.longestPath.length} activities`],
    ['Showing', d.scopeLabel],
  ]
  facts.forEach(([k, v, c], i) => {
    const x = M + i * 66
    pdf.setFont('helvetica', 'normal'); pdf.setFontSize(7); pdf.setTextColor('#64748b'); pdf.text(k.toUpperCase(), x, 31)
    pdf.setFont('helvetica', 'bold'); pdf.setFontSize(9.5); pdf.setTextColor(c ?? NAVY); pdf.text(v, x, 37)
  })
  if (d.cpm.contractDatesSource === 'default') {
    pdf.setFont('helvetica', 'normal'); pdf.setFontSize(7.5); pdf.setTextColor('#b45309')
    pdf.text('Contract dates are the built-in defaults — set them on the project record.', W - M, 44, { align: 'right' })
  }

  fitImage(pdf, d.image, M, 46, W - 2 * M, H - 46 - 16)

  pdf.setDrawColor('#dbe6e0'); pdf.line(M, H - 12, W - M, H - 12)
  pdf.setFontSize(7.5); pdf.setTextColor('#6b8592'); pdf.setFont('helvetica', 'normal')
  pdf.text('Generated by KIPL ProjectOS — dates calculated from activity logic and durations (CPM), not typed in.', M, H - 6)
  pdf.text('A3 landscape', W - M, H - 6, { align: 'right' })

  pdf.save(`${d.fileStem}.pdf`)
}

