import { jsPDF } from 'jspdf'
import * as echarts from 'echarts'
import { cpmOption, pertOption, ganttOption } from './WbsCharts'

// Render an echarts option into an off-screen canvas and return a PNG data URL
async function renderChart(option: any, w: number, h: number): Promise<string> {
  const div = document.createElement('div')
  div.style.cssText = `position:fixed;left:-99999px;top:0;width:${w}px;height:${h}px;background:#fff;`
  document.body.appendChild(div)
  const chart = echarts.init(div, undefined, { renderer: 'canvas', width: w, height: h })
  chart.setOption(option)
  await new Promise(r => setTimeout(r, 350)) // let layout/animation settle
  const url = chart.getDataURL({ pixelRatio: 2, backgroundColor: '#ffffff' })
  chart.dispose(); div.remove()
  return url
}

export interface ReportInput {
  projectName: string
  client: string
  allotment: string
  projectStart: string
  gantt: any[]
  cpm: any        // cpmData: { allTasks, criticalPath }
  pert: any       // pertData: { projectExpectedDuration, projectStdDeviation, probability68, probability95 }
  kpis: { overallProgress: number; contractPct: number; daysRemaining: number; completed: number; total: number; milestonesHit: string }
}

// A3 landscape: 420 × 297 mm
export async function generateMonthlyReport(d: ReportInput) {
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a3' })
  const W = 420, M = 15
  const month = new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })
  const NAVY = '#0a1e28'

  const header = (title: string) => {
    pdf.setFillColor(NAVY); pdf.rect(0, 0, W, 26, 'F')
    pdf.setTextColor('#ffffff'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(15)
    pdf.text(d.projectName, M, 12)
    pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); pdf.setTextColor('#9DB4C6')
    pdf.text(`${title}  ·  ${month}`, M, 20)
    pdf.setTextColor('#9DB4C6'); pdf.setFontSize(8)
    pdf.text(`Client: ${d.client}   ·   Allotment: ${d.allotment}`, W - M, 12, { align: 'right' })
    pdf.text('kiplstpsrinagar.com', W - M, 20, { align: 'right' })
  }
  const footer = () => {
    pdf.setDrawColor('#dbe6e0'); pdf.line(M, 285, W - M, 285)
    pdf.setFontSize(7.5); pdf.setTextColor('#6b8592')
    pdf.text('Generated by KIPL ProjectOS — Clause 17 schedule submission (CPM · PERT · Gantt)', M, 291)
    pdf.text(new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }), W - M, 291, { align: 'right' })
  }

  // ── Page 1 · Cover + KPIs ──
  header('Monthly Progress Report — Schedule')
  pdf.setTextColor('#0a1e28'); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(30)
  pdf.text('Project Schedule Report', M, 70)
  pdf.setFont('helvetica', 'normal'); pdf.setFontSize(13); pdf.setTextColor('#3f5763')
  pdf.text('Critical Path Method (CPM) · PERT Analysis · Gantt Chart', M, 82)
  const kpiRows: [string, string][] = [
    ['Contract time elapsed', d.kpis.contractPct + '%'],
    ['Physical work done', d.kpis.overallProgress + '%'],
    ['Tasks completed', `${d.kpis.completed} / ${d.kpis.total}`],
    ['Milestones achieved', d.kpis.milestonesHit],
    ['Days remaining', String(d.kpis.daysRemaining)],
    ['Critical tasks', String(d.cpm?.criticalPath?.length ?? 0)],
    ['PERT expected duration', d.pert?.projectExpectedDuration + ' days'],
    ['Std deviation (σ)', d.pert?.projectStdDeviation + ' days'],
  ]
  let ky = 110
  kpiRows.forEach((r, i) => {
    const col = i % 2, x = M + col * 200, y = ky + Math.floor(i / 2) * 34
    pdf.setDrawColor('#dbe6e0'); pdf.setFillColor('#f4f7f5'); pdf.roundedRect(x, y, 190, 26, 3, 3, 'FD')
    pdf.setFontSize(9); pdf.setTextColor('#6b8592'); pdf.text(r[0].toUpperCase(), x + 8, y + 10)
    pdf.setFont('helvetica', 'bold'); pdf.setFontSize(16); pdf.setTextColor('#0a1e28'); pdf.text(r[1], x + 8, y + 21)
    pdf.setFont('helvetica', 'normal')
  })
  footer()

  // ── Page 2 · Gantt ──
  const ganttImg = await renderChart(ganttOption(d.gantt, d.projectStart), 1500, 900)
  pdf.addPage(); header('Gantt Chart — Programme')
  pdf.addImage(ganttImg, 'PNG', M, 34, W - 2 * M, 240)
  footer()

  // ── Page 3 · CPM network ──
  const cpmImg = await renderChart(cpmOption(d.cpm?.allTasks ?? []), 1500, 850)
  pdf.addPage(); header('Critical Path Method — Activity Network')
  pdf.setFontSize(9); pdf.setTextColor('#7f1d1d')
  pdf.text(`Critical path in red — ${d.cpm?.criticalPath?.length ?? 0} critical activities; any delay extends completion.`, M, 32)
  pdf.addImage(cpmImg, 'PNG', M, 38, W - 2 * M, 232)
  footer()

  // ── Page 4 · PERT ──
  const pertImg = await renderChart(pertOption({ mean: d.pert?.projectExpectedDuration, sigma: d.pert?.projectStdDeviation, p68: d.pert?.probability68, p95: d.pert?.probability95 }), 1500, 750)
  pdf.addPage(); header('PERT — Completion Probability')
  pdf.setFontSize(9); pdf.setTextColor('#3f5763')
  pdf.text('Expected completion (TE) with 68% (green) and 95% (blue) confidence bands.', M, 32)
  pdf.addImage(pertImg, 'PNG', M, 40, W - 2 * M, 200)
  footer()

  pdf.save(`KIPL-Schedule-Report-${month.replace(' ', '-')}.pdf`)
}
